### ISSUE TITLE
Issues with portal2.sh

### ISSUE THREAD

**Issue by fasmat** [ValveSoftware/portal2#10]
Portal2 does not start as its launcher is encoded with Windows line endings resulting in an error about an unknown interpreter /bin/bash^M.

dos2unix should solve the issue, but Linux seems to miss an executable; I see "portal2.exe" and "portal2_osx" but no "portal2_linux".

**Comment by 0x726f62** [comment]
Are you sure you opted-in to the beta?

```
You may do this by right-clicking on Portal 2 (Beta) in Steam, clicking Properties -> Betas and then select 'beta' from the drop-down. 
If you do not do this, Portal 2 will not run on Linux.
```

**Comment by egelmex** [comment]
I think this is still an issue, it should at least tell you your not part of the beta instead of just doing nothing...

**Comment by Tele42** [comment]
@egelmex this is one of those transitive issues, once there's a version worth keeping around, they will move it into the main branch, making it just work for everybody. We have to pay attention to the setting because we are early adopters to help test.
