### ISSUE TITLE
Spinning mouse in intro 

### ISSUE THREAD

**Issue by brealorg** [ValveSoftware/portal2#100]
I tested the first level and the mouse kept returning to the roof and spinning round and round and round.

Tried to record a demo file, not sure if it's working or not. https://drive.google.com/file/d/0B8pYA1GggIAhSDgtY29LYWFBdzA/edit?usp=sharing

**Comment by timjp87** [comment]
Duplicate of #16

**Comment by Tele42** [comment]
I disagree, does not match the issue described in #16. This resembles https://github.com/ValveSoftware/halflife/issues/642.

**Comment by davidw-valve** [comment]
Does this reproduce consistently on your machine?

**Comment by davidw-valve** [comment]
I believe this should be fixed with updates since the report. It is hard to tell though since I couldn't reproduce this exactly.

I am closing the bug. Please re-open it if you can still repro it.

**Comment by Tele42** [comment]
@davidw-valve just a friendly reminder that users can not reopen issue reports by themselves which have been closed by a dev or moderator
