### ISSUE TITLE
Trying to start portal 2 while being offline will crash Steam

### ISSUE THREAD

**Issue by fasmat** [ValveSoftware/portal2#103]
Yesterday I didn't have connection to the internet and I started steam in offline mode. As soon as I started Portal 2 (or better right after the intro movie) both Portal 2 and Steam crashed. I retried 2 or 3 times, every time the same result.

**Comment by kevincroissant** [comment]
This worked for me every time I tried. Try running steam in a command line (just "steam"), and then see if there's error messages in the terminal when it crashes.

**Comment by rmsrepliedtomeonce** [comment]
It's not a bug -- it's a feature™

**Comment by davidw-valve** [comment]
I cannot reproduce this -- as long as Steam is open, even if it's offline Portal 2 starts up just fine. Can you reproduce this consistently, even after restarting Steam?

**Comment by fasmat** [comment]
Sorry for being unresponsive for so long, I didn't have the time to test it again. On Thursday it definitely didn't work, but after the last update (just installed) playing Portal 2 in offline mode does not crash Steam any longer, so I'll close this ticket.

**Comment by timkerk** [comment]
I am getting this also, it runs fine in offline mode but only when there is still net connection. Start steam with no net connection in offline mode and it ctd's and crashed steam. Running it in a console the two outputs (offline mode no network vs offline mode net up) diverges after the line: "Game.dll loaded for "Half-Life 2""

the console output  from the one that fails then gives:

steam: host.cc:97: const talk_base::Host& talk_base::LocalHost(): Assertion `gLocalHost->networks().size() > 0' failed.

i could post up the rest of it if you guys need it

**Comment by timkerk** [comment]
It still wont work offline for me, Half life 2 and left for dead 2 work fine completely offline. So did DOTA2 when i had it last year. Every time i try it completely offline it crashes steam and i have to start steam again offline and shut it down properly before going online or it downloads itself again. 
Alas, ill just keep playing it online in offline mode, the game runs flawlessly otherwise.
