### ISSUE TITLE
Raw input doesn't work

### ISSUE THREAD

**Issue by jazztickets** [ValveSoftware/portal2#11]
Setting 'Ignore Windows Mouse Speed' to Enabled doesn't stick.

m_rawinput 1 doesn't seem to work either.

System info:
https://gist.githubusercontent.com/jazztickets/ec290c38deb7fa8db404/raw/6b13c8269f3aabda0675b8339f40307eaeba876d/gistfile1.txt

Mouse is Logitech G400

**Comment by amlib** [comment]
Is that also related to the heavy mouse filtering I'm noticing? I can't do fine movements because the game barely registers slow mouse movement, and there is a lot of "angle snapping" when trying to deviate a few degrees from horizontal and vertical movement.

**Comment by davidw-valve** [comment]
We have released an update which makes raw mouse input work.

**Comment by jazztickets** [comment]
Raw Input now works in-game, but the option in the menu always shows disabled.
