### ISSUE TITLE
New game fails to initiate: Black Screen

### ISSUE THREAD

**Issue by shivak7** [ValveSoftware/portal2#110]
When I start a new game, I see an empty menu list with no text. If I hit play, I get a black screen with the background music playing. Nothing else happens.

Running the game on: SteamOS(beta x86_64) on the Steam Machine Prototype (core i5, gtx 780, 16gb RAM).

**Comment by shivak7** [comment]
Testing further, I found that I had the same problem even for workshop singleplayer levels. I investigated a little and found that a number of i386 library dependancies (for vguimatsurface.so) were missing such as: libfontconfig and libfreetype. I installed them but still no luck. The game's logs give me:

```
steam@steamos:~/.steam/steam/SteamApps/common/Portal 2$ cat portal2_dump.txt 
SDL video target is 'x11'
SDL failed to create GL compatibility profile (whichProfile=0!
This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system supports the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system supports the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system supports the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system supports the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system supports the OpenGL extension GLX_EXT_swap_control_tear.
Setup file 'GameInfo.txt' doesn't exist in subdirectory 'hl2'.
Check your -game parameter or VCONFIG setting.
```

**Comment by timjp87** [comment]
Does the menu without text look similar to #134? In the referenced issue it looks like it is an issue with the driver. The creator mentions that it doesn't work on his Intel Graphics setup but on his NVIDIA PC. If you don't have text with NVIDIA that would rule that out.

**Comment by shivak7** [comment]
Well it's close but not the same. I get text on the main screen but when I hit new game I get something like bug #134 . Not sure what to make of this. 
EDIT: Attaching screenshot of new game. After hitting play I just get a blackscreen while the portal 2 menu music continues playing. I can bring up the developer console but nothing else happens. 

![portal2_menu](https://f.cloud.github.com/assets/6822038/2317220/c94f5f9e-a347-11e3-9708-25d4e2ce0e2c.jpg)

**Comment by shivak7** [comment]
Another update: I am able to enter the test chamber editor and create and play on my own chambers. I get a loading screen for this part but it doesn't work for the main game or any of the workshop chambers. Really weird.

**Comment by shivak7** [comment]
UPDATE: The latest 10.9 MB update on March 4th, seems to have fixed the text on the new game screen and the game finally works! I am curious as to what the issues were.
