### ISSUE TITLE
Placing a portal took ~3 seconds

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/portal2#111]
The game froze for about 3 seconds when I shot a portal.
This only happened to me _once_ in 10 hours of play and I was not able to reproduce it by shooting another portal in the same spot.

Otherwise the game performs great.

**Comment by davidw-valve** [comment]
There are many possible reasons for an isolated 3 second delay, many of which might be outside of the control of the game. Without reproducibility or other clues there is no way we are going to be able to do anything about this. So I am closing it. Please feel free to file a bug report with more information if you ever find any.

**Comment by ghost** [comment]
Understandable. I'll let you know if I ever manage to reproduce
