### ISSUE TITLE
portal2.exe installed?

### ISSUE THREAD

**Issue by machinaeZER0** [ValveSoftware/portal2#12]
Going through the local files, I noticed that portal2.exe was installed in the linux beta. Instentional? It's not a big file, but if it doesn't need to be there it probably wouldn't need to be included.

There also is (I think?) a mac executable, portal2_osx. Anyway. If those are supposed to be there then IGNORE MEEEEEEEEEEE

**Comment by Half-Shot** [comment]
There is a whole bunch of stuff like vbsp_osx for compiling maps in mac. Its probably just leftovers due to this being an unpolished alpha. They could probably be removed :+1:

**Comment by jacobmischka** [comment]
I honestly don't know how Steam handles different platforms, but this is definitely not the only game where this happens. Heck, every install of Starbound includes Windows, OSX, and Linux binaries, you can literally just copy the install from windows, make the Linux binary executable, and run the game. So I'm not sure if this is a "bug" with Portal 2 per se.

**Comment by machinaeZER0** [comment]
Huh. Interesting! Maybe this is intentional, then. Probably helps them test
too, to make sure they're not breaking anything on other OSes.

**Comment by davidw-valve** [comment]
These binaries are super light and we ship them on all platforms. You can safely ignore them. :)

**Comment by machinaeZER0** [comment]
Cool. Thanks for clarifying!
