### ISSUE TITLE
Changing the master volume has no effect on some video-clips.

### ISSUE THREAD

**Issue by JuliusZet** [ValveSoftware/portal2#121]
If I change the master volume in Portal 2, is has no effect on the following ending clips of Portal 2:
- the clip, where the player is in the lift to surface and the "turret-orchestra" is playing.
- the clip, where Wheatly is in space.

The Volume is 100% in those clips, even if you adjusted the master volume differently.

I have also noticed, that the clips are still continue playing, when you pause the game.

I'm using Linux.

**Comment by Arbitrary007** [comment]
I can vouch for the volume bit. I know that some of the other videos had audio issues similar to this one as well. I may have also seen #92 related to this...
