### ISSUE TITLE
.desktop file does not include proper icon

### ISSUE THREAD

**Issue by panzi** [ValveSoftware/portal2#124]
The .desktop files put in `~/Desktop` and `~/.local/share/applications` don't include the proper icon. There is a windows icon file (`~/.local/share/Steam/SteamApps/common/Portal 2/portal2.ico`). One could extract the icons from there and install them as png under `~/.local/share/icons/hicolor/${WIDTH}x${HEIGHT}/apps/portal2.png` and then add `Icon=portal2` to the .desktop files, or one could simply only extract the biggest icon to `~/.local/share/Steam/SteamApps/common/Portal 2/portal2.png` and use the absolute path in the .desktop files (`Icon=$HOME/.local/share/Steam/SteamApps/common/Portal 2/portal2.png` where `$HOME` is to be replaced with the user's home directory). I did the later manually.

**Comment by jacobmischka** [comment]
What icon does it use? Just the standard basic one?

**Comment by panzi** [comment]
The steam icon (I think it simply was `Icon=steam`).

**Comment by jacobmischka** [comment]
Oh, I never create desktop/application shortcuts for Steam games, so I'm not sure, but whenever I run most (I think all actually) steam games it simply uses the Steam icon for me. Is that not the case when you create .desktop shortcuts normally?

**Comment by panzi** [comment]
I just installed "Half-Life 2: Lost Coast", which got the Half-Life 2 icon (`Icon=steam_icon_340`). Another game which installed the icon to `~/.local/share/icons` but for some reason didn't reference it in the .desktop file is Osmos.

**Comment by MichaelAquilina** [comment]
There are some other valve games that suffer from this problem (Dota2 for example). The [SteamDB website](http://steamdb.info/linux/) tracks all the games that have this problem (Marked with "No Linux Icon"). Hopefully they'll fix this for all their games because it is a bit inconvenient to stay manually setting the icon yourself each time.

**Comment by prcastro** [comment]
Why this issue is closed? The problem won't be fixed?

**Comment by MichaelAquilina** [comment]
The issue has been fixed, if you try create a desktop shortcut now it will
show.

On Sat, Mar 8, 2014 at 3:50 PM, brk00 notifications@github.com wrote:

> Why this issue is closed? The problem won't be fixed?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ValveSoftware/portal2/issues/124#issuecomment-37101113
> .

## 

Michael Aquilina

**Comment by davidw-valve** [comment]
This problem is fixed now -- new icons you create will work.
