### ISSUE TITLE
[Feature request] Redesign the options menu hints

### ISSUE THREAD

**Issue by stevethepocket** [ValveSoftware/portal2#129]
I know you're probably only interested in squashing real bugs at this point, and Linux specific ones at that, but this is something that's been bugging me ever since the game was released, and I know it bugs a lot of other people too. Those hints that pop up whenever we try to change any setting in the advanced video options. They're annoying. They're obtrusive. And they do not ever go away. I know you wanted to acclimate PS3 players who got a free copy of the game on Steam and were playing a real PC game for the first time, but this was the wrong way to do it.

There is a huge space over on the right where you could have these pop up when we highlight or mouse over a line in the menu. Please, please consider revising the menu design to do this instead of making the entire menu disappear and get replaced by a pop-up we have to manually dismiss whenever we try to click on anything. Even the TF2 interface's popups go away forever once you've dismissed them the first time.

**Comment by dscharrer** [comment]
I agree, this is especially annoying when what setting is killing perf, as the forced hint reappears after every apply.

**Comment by Vash63** [comment]
Unfortunately, CS:GO has this same issue. It's definitely not Linux specific, it seems most of the newer Valve games are doing that.

**Comment by Cabanur** [comment]
Completely agree. The game asumes I don't know what the optios are for and forces me to read this hints. It's almost insulting my knowledge, and definetely annoying. Hope you fix this.

**Comment by JoshuaJB** [comment]
I concur. The setting should change when I click on the arrow and show the hint when I click the name/current setting (I always thought I must have been missing the hit target every first click).

**Comment by stevethepocket** [comment]
Here's a quick-and-dirty mockup of what I had in mind, more or less.

![menu_mockup](https://cloud.githubusercontent.com/assets/3085348/2691059/1667f53a-c372-11e3-94ab-d6aa5e43c13b.jpeg)

**Comment by Cabanur** [comment]
That's awesome, I wish they did something like your mockup.

Un saludo,
Pau Gisbert

2014-04-14 3:14 GMT+02:00 stevethepocket notifications@github.com:

**Comment by j5lx** [comment]
:+1:

**Comment by kisak-valve** [comment]
Hello, per "- Improved advanced video settings descriptions." in the [2021-02-18](https://store.steampowered.com/oldnews/81067) Portal 2 update, please retest this issue.

**Comment by Cabanur** [comment]
I am positively surprised that you guys went and improved the game after all these years. 

The new graphics UI indeed solved this issue for me, hope more people tag along to give more feedback.

**Comment by j5lx** [comment]
I second what Cabanur said. Thanks for fixing this and thanks for showing this game some love even after all those years. I just went in to check the fix and before I knew it I found myself playing for almost two hours. Such a great game ^^

**Comment by stevethepocket** [comment]
Wow, this might just beat out the Half-Life expansions' soundtracks for the weirdest thing Valve has addressed this far past release. But thank you! Yes, this is quite acceptable.

If you don't mind my asking, before we close this and never look at it again, is this patch the brainchild of one Joshua Ashton, who was [also working on a _Portal 2_ standalone mod](https://www.gamingonlinux.com/2020/12/portal-2-desolation-standalone-mod-gets-a-first-proper-teaser-coming-to-linux) that runs off DXVK? Because my first thought when I saw that article last year was "Ooh, what if he convinces Valve to let him do that to the base game too? That would rule."

**Comment by kisak-valve** [comment]
Thanks for retesting. I don't have insight to give on your question.
