### ISSUE TITLE
[Solved] Can't launch the game.

### ISSUE THREAD

**Issue by benbristow** [ValveSoftware/portal2#13]
Fully downloaded the game. Get the error when trying to run it in the Terminal:

/bin/sh: 1: /home/ben/.local/share/Steam/SteamApps/common/Portal 2/portal2.sh: not found

**Comment by timjp87** [comment]
What command did you launch in terminal? Are you opted into the beta for Portal 2 (Beta)?

**Comment by benbristow** [comment]
I ran Steam in the terminal to see the error messages. Yes, I am opted into the beta.

**Comment by benbristow** [comment]
Oh damn it I'm an idiot. I opted into the Steam client beta and not the beta for Portal 2 beta. This is confusing. O_o

**Comment by LiamDawe** [comment]
This can be closed, not a bug.

**Comment by eikesauer** [comment]
I still consider this a bug. I downloaded the game (one or two hours), started it and got no error message in the GUI and the same cryptic error message after going to console. It shouldn't let me download without opting in in the first place or tell clearly why it won't start.

**Comment by LiamDawe** [comment]
That is not a bug within portal 2.

This is not a bug.
