### ISSUE TITLE
GLaDOS' Eye

### ISSUE THREAD

**Issue by WillMcDade** [ValveSoftware/portal2#133]
At the part of Wheatly waking GLaDOS, GLaDOS' eye has not got the orange light like in Windows.

SPEC:
HP dx5150 MT
AMD Athlon 64 X2 2.0GHz
3GB RAM
80GB Western Digital Caviar, 250GB Western Digital Caviar, 250GB Seagate Momentus
MSi GeForce GT N210
Arch Linux KDE

I was recording at the time so I can cut a clip out and post it if you want.

**Comment by timjp87** [comment]
Duplicate of #27

**Comment by WillMcDade** [comment]
Sorry about that @blackout24. Hadn't scrolled through. :)
