### ISSUE TITLE
No cyrillic text in menus

### ISSUE THREAD

**Issue by artemklevtsov** [ValveSoftware/portal2#134]
Hi.

Problem appeareence on my laptop Acer V3-771G (on desktop with nvidia it's all right).

![3](https://f.cloud.github.com/assets/603798/2304356/32a4b63c-a218-11e3-83b9-755174b39b45.png)
![2](https://f.cloud.github.com/assets/603798/2304358/36d488fe-a218-11e3-8bb3-f34cfc3059d9.png)

``` bash
lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)
01:00.0 VGA compatible controller: NVIDIA Corporation GK107M [GeForce GT 650M] (rev a1)
```

Software versions:

``` bash
pacman -Qs nvidia
community/bumblebee 3.2.1-3
    NVIDIA Optimus support for Linux through VirtualGL
multilib/lib32-libcl 1.1-1
    OpenCL library and ICD loader from NVIDIA (32-bit)
multilib/lib32-nvidia-utils 331.49-1
    NVIDIA drivers utilities (32-bit)
multilib/lib32-opencl-nvidia 331.49-1
    OpenCL implemention for NVIDIA (32-bit)
extra/libcl 1.1-3
    OpenCL library and ICD loader from NVIDIA
extra/libvdpau 0.7-1
    Nvidia VDPAU library
extra/nvidia 331.49-1
    NVIDIA drivers for linux
extra/nvidia-lts 331.49-1
    NVIDIA drivers for linux-lts
extra/nvidia-utils 331.49-1
    NVIDIA drivers utilities
extra/opencl-nvidia 331.49-1
    OpenCL implemention for NVIDIA

pacman -Qs intel
community/iasl 20140114-1
    Intel ACPI Source Language compiler
extra/intel-dri 10.0.3-1
    Mesa drivers for Intel
community/intel-gpu-tools 1.5-1
    Tools for development and testing of the Intel DRM driver
extra/intel-ucode 20140122-1
    Microcode update files for Intel CPUs
multilib/lib32-intel-dri 10.0.3-1
    Mesa DRI drivers for Intel (32-bit)
extra/libva-intel-driver 1.2.2-2
    VA-API implementation for Intel G45 and HD Graphics family
extra/xf86-video-intel 2.99.910-1 (xorg-drivers xorg)
    X.org Intel i810/i830/i915/945G/G965+ video drivers

pacman -Qs mesa
extra/glu 9.0.0-2
    Mesa OpenGL Utility library
extra/intel-dri 10.0.3-1
    Mesa drivers for Intel
multilib/lib32-glu 9.0.0-2
    Mesa OpenGL utility library (32 bits)
multilib/lib32-intel-dri 10.0.3-1
    Mesa DRI drivers for Intel (32-bit)
multilib/lib32-libtxc_dxtn 1.0.1-5
    S3 Texture Compression (S3TC) library for Mesa (32-bit)
multilib/lib32-mesa 10.0.3-1
    an open-source implementation of the OpenGL specification (32-bit)
multilib/lib32-mesa-libgl 10.0.3-1
    Mesa 3-D graphics library (32-bit)
extra/libtxc_dxtn 1.0.1-5
    S3 Texture Compression (S3TC) library for Mesa
extra/mesa 10.0.3-1
    an open-source implementation of the OpenGL specification
extra/mesa-demos 8.1.0-1
    Mesa demos and tools
extra/mesa-libgl 10.0.3-1
    Mesa 3-D graphics library

pacman  -Qs steam
multilib/steam 1.0.0.47-1
    Digital distribution client bootstrap package

```

I tried luanch game on intel and nvidia cards with same effect. For start with nvidia card I used following game launch command: `primusrun %command% -w 1920 -h 1080`

After start game in console appears following messages (may be it's related):

```
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 70: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 78: saw unknown, expected number
```

**Comment by timjp87** [comment]
Do you use the same desktop enviroment on both machines (desktop and laptop) with the same default font, installed fonts, locale and fontconfiguration? The font rendering seems to be different from person to person. See: #35 and #57 It could be influcened by your system fonts. If you have the same Arch install on both but with different drivers that could help explain it.

**Comment by artemklevtsov** [comment]
Yes, DE (KDE) and locales (ru_RU.UTF-8) are equal. I'm not sure about fonts. On desktop I have nvidia GTS 450. On laptop nvidia GT 650M (optimus). Driver versions are equal.
I'll try read your links.

**Comment by timjp87** [comment]
I remember an issue with Kerbal Space Program on Linux where the menu would not have any fonts unless the system has the "Arial" font installed, which is a Windows font. On my system I have "ttf-ms-fonts" installed from AUR, which provides a lot of fonts that you'd expect to find on a Windows system. Do you have this installed aswell on any of your two machines? Do your fonts on the NVIDIA machine look like mine in the second repsonse to #57?

**Comment by artemklevtsov** [comment]
I install ttf-ms-fonts 2.0-10 from AUR without effect.

**Comment by artemklevtsov** [comment]
Addition info from laptop:

``` bash
ls -1 /etc/fonts/conf.d/
09-texlive-fonts.conf
10-scale-bitmap-fonts.conf
11-lcdfilter-default.conf
20-unhint-small-dejavu-sans-mono.conf
20-unhint-small-dejavu-sans.conf
20-unhint-small-dejavu-serif.conf
20-unhint-small-vera.conf
30-metric-aliases.conf
30-ttf-liberation-mono.conf
30-ttf-liberation-sans.conf
30-ttf-liberation-serif.conf
30-urw-aliases.conf
30-win32-aliases.conf
40-nonlatin.conf
45-latin.conf
49-sansserif.conf
50-user.conf
57-dejavu-sans-mono.conf
57-dejavu-sans.conf
57-dejavu-serif.conf
60-latin.conf
65-fonts-persian.conf
65-nonlatin.conf
69-unifont.conf
70-yes-bitmaps.conf
80-delicious.conf
90-synthetic.conf
99pdftoopvp.conf
README

pacman -Qs ttf
extra/ttf-dejavu 2.34-1
    Font family based on the Bitstream Vera Fonts with a wider range of characters
community/ttf-droid 20121017-2
    General-purpose fonts released by Google as part of Android
extra/ttf-freefont 20120503-2
    Set of free outline fonts covering the Unicode character set
community/ttf-liberation 2.00.1-3
    Red Hats Liberation fonts.
local/ttf-ms-fonts 2.0-10
    Core TTF Fonts from Microsoft
local/ttf-pt-mono 20120417-1
    A set of free public TrueType fonts with support of national alphabets Russia
local/ttf-pt-sans 20110102-1
    A set of free public TrueType fonts with support of national alphabets Russia
local/ttf-pt-serif 20110612-1
    A set of free public TrueType fonts with support of national alphabets Russia

```

**Comment by davidw-valve** [comment]
Do you have the gsfonts package installed on your system? Does installing that resolve this?

**Comment by artemklevtsov** [comment]
gsfonts already installed.

**Comment by davidw-valve** [comment]
Portal 2 uses Nimbus Sans, do you have that font in other programs (e.g. Open Office)? I would expect it to be installed with gsfonts.

**Comment by artemklevtsov** [comment]
``` bash
locale -a
C
POSIX
en_US.utf8
ru_RU.utf8

fc-list | grep Nimbus
/usr/share/fonts/Type1/n019003l.pfb: Nimbus Sans L:style=Regular
/usr/share/fonts/Type1/n021003l.pfb: Nimbus Roman No9 L:style=Regular
/usr/share/fonts/Type1/n019044l.pfb: Nimbus Sans L:style=Bold Condensed
/usr/share/fonts/Type1/n021024l.pfb: Nimbus Roman No9 L:style=Medium Italic
/usr/share/fonts/Type1/n021004l.pfb: Nimbus Roman No9 L:style=Medium
/usr/share/fonts/Type1/n022003l.pfb: Nimbus Mono L:style=Regular
/usr/share/fonts/Type1/n019004l.pfb: Nimbus Sans L:style=Bold
/usr/share/fonts/Type1/n022023l.pfb: Nimbus Mono L:style=Regular Oblique
/usr/share/fonts/Type1/n019043l.pfb: Nimbus Sans L:style=Regular Condensed
/usr/share/fonts/Type1/n022024l.pfb: Nimbus Mono L:style=Bold Oblique
/usr/share/fonts/Type1/n019023l.pfb: Nimbus Sans L:style=Regular Italic
/usr/share/fonts/Type1/n019063l.pfb: Nimbus Sans L:style=Regular Condensed Italic
/usr/share/fonts/Type1/n019064l.pfb: Nimbus Sans L:style=Bold Condensed Italic
/usr/share/fonts/Type1/n021023l.pfb: Nimbus Roman No9 L:style=Regular Italic
/usr/share/fonts/Type1/n019024l.pfb: Nimbus Sans L:style=Bold Italic
/usr/share/fonts/Type1/n022004l.pfb: Nimbus Mono L:style=Bold

fc-match Nimbus
DejaVuSans.ttf: "DejaVu Sans" "Book"
```

**Comment by davidw-valve** [comment]
Do you have Portal 2 configured to play in English or Russian? If you configure it to play in English does this change anything?

**Comment by artemklevtsov** [comment]
English text display correctly:

![3](https://f.cloud.github.com/assets/603798/2328884/ae7501c0-a409-11e3-9418-4b3802793410.png)

**Comment by davidw-valve** [comment]
For Portal 2 we use Nimbus Sans Condensed as the UI font. Does this font on your system display cyrillic characters in other programs?

I tested it here and Portal 2 displays fine in Russian for me.

**Comment by artemklevtsov** [comment]
In LibreOffice works.

![4](https://f.cloud.github.com/assets/603798/2349520/0836be68-a565-11e3-9f5a-3fa46556f11d.png)

**Comment by timjp87** [comment]
@unikum I wonder why your fontconfig matches Nimbus (which you have installed) to DeJaVu Sans. Could that be the problem? I don't have Nimbus Sans installed at all and fc-match returns "Arial" which I have installed through mscorefonts. My ingame text also looks like Arial which is fine for me.

**Comment by stevethepocket** [comment]
The problem, as I've mentioned over in #35, is that the correct font, Univers, isn't being recognized. It's in the game, and the format is readable (Consolas, the end-credits font, is working correctly), but that particular file isn't getting read.

**Comment by timjp87** [comment]
@stevethepocket The correct font is Nimbus Sans as davidw-valve has mentioned.

**Comment by lexxus-lex** [comment]
Это баг, который возникает при кривых руках.
Скажи какую ОС ты юзаешь, точнее дистр?

**Comment by mhobbs-8B** [comment]
I don't know if this helps troubleshooting this problem or not, but I'll second what @stevethepocket has already said. The font used on Windows _is_ Univers, not Nimbus Sans.

From one of the many screenshots at https://www.google.com/search?q=portal+2+menu&tbm=isch :
![image](https://f.cloud.github.com/assets/611195/2379856/9b4358fe-a8a0-11e3-8afc-bdddd33d8ba9.png)

From myfonts.com:
![image](https://f.cloud.github.com/assets/611195/2379875/e9d3221a-a8a0-11e3-9d32-eb54bea81115.png)

![image](https://f.cloud.github.com/assets/611195/2379882/0a03bbee-a8a1-11e3-960f-fc34070bd484.png)

**Comment by artemklevtsov** [comment]
It's strange but on my Desktop cyrillic text miss when 09-texlive-fonts.conf is activated and return when disabled:

``` bash
ln -s /etc/fonts/conf.avail/09-texlive-fonts.conf /etc/fonts/conf.d/
```

``` bash
rm /etc/fonts/conf.d/09-texlive-fonts.conf
```

I'll test it on the laptop later.

`09-texlive-fonts.conf` content:

``` xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <dir>/usr/share/texmf-dist/fonts/opentype</dir>
  <dir>/usr/share/texmf-dist/fonts/truetype</dir>
  <dir>/usr/local/share/texmf/fonts/opentype</dir>
  <dir>/usr/local/share/texmf/fonts/truetype</dir>
</fontconfig>


```

In addition:

``` bash
fc-list | grep Univers
```

And game launch always with STEAM_RUNTIME enabled.

**Comment by davidw-valve** [comment]
Does the latest update fix this?

**Comment by artemklevtsov** [comment]
@davidw-valve after patch text also not displayed. Now remove `09-texlive-fonts.conf` solved my problem on the both computers.

**Comment by alexws54tk** [comment]
Russian text display incorrectly.
![Screen 1](https://cloud.githubusercontent.com/assets/5887243/3808820/65a62d5c-1c7c-11e4-8acc-9bfd44f74535.jpg) ![Screen 2](https://cloud.githubusercontent.com/assets/5887243/3808821/65a8fdac-1c7c-11e4-8cd9-d140cfccd219.jpg) ![Screen 3](https://cloud.githubusercontent.com/assets/5887243/3808822/65c6df48-1c7c-11e4-8864-a1afc1d07ed5.jpg)

English text display correctly
![620_2014-08-05_00005](https://cloud.githubusercontent.com/assets/5887243/3809134/492ce676-1c80-11e4-90e3-cebd46032700.png)
![620_2014-08-05_00004](https://cloud.githubusercontent.com/assets/5887243/3809133/4918ae68-1c80-11e4-900d-6ade5823171d.png)

[System info](https://gist.github.com/alexws54tk/82e32ccb96bd17a1b7d5#file-some-system-info)

**Comment by alexws54tk** [comment]
Solved.
Remove from system «Adobe Helvetica» font.

**Comment by ghost** [comment]
I had the same issue on openSUSE Tumbleweed. And confirm what it is Adobe Helvetica messing all up.
Some additional info in Russian about this(for people who will find this issue in Google) can be found [here](https://www.linux.org.ru/forum/games/10245767). This thread helped me a lot.

**Comment by ghost** [comment]
In my case problem was with package `fonts-texgyre` which was installed with 0ad.
To find the cause of problem just look in game's console or type in terminal
`fc-match Helvetica`

**Comment by xaionaro** [comment]
Seems the workaround "deinstall `fonts-texgyre`" works (on Debian Jessie):

```
dpkg -P fonts-texgyre
```

@grin-sv, thanks!

**Comment by remove-akk** [comment]
@grin-sv , thanks!

"sudo apt-get remove fonts-texgyre" (ubuntu) solved problem with Russian

**Comment by artemrizhov** [comment]
Same problem on Kubuntu 16.04: no cyrillic texts in the menu. The methods described above do not help.

$ fc-match "Nimbus Sans"
n019003l.pfb: "Nimbus Sans L" "Regular"

**Comment by htower** [comment]
@artemrizhov, add this to your ~/.fonts.conf :

```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>

... old content ... 

  <!-- fix Portal 2 cyrillic menu -->
  <match target="pattern">
    <test name="family" qual="any" >
      <string>Helvetica</string>
    </test>
    <edit name="family" mode="assign" binding="same">
      <string>Nimbus Sans L</string>
    </edit>
  </match>
</fontconfig>
```

You can replace "Nimbus Sans L" with other font, for example "Arial".

$ fc-match Helvetica
n019003l.pfb: "Nimbus Sans L" "Regular"

**Comment by cherrot** [comment]
I have the same problem if language is set to Simplified Chinese (English is OK). All the menu items are black (not tofu, just blank). 

I don't have ` fonts-texgyre` installed on my Archlinux (package name is `tex-gyre-fonts` on Arch)

```bash
$ fc-match Helvetica
NimbusSans-Regular.otf: "Nimbus Sans" "Regular"
```

**Comment by cherrot** [comment]
https://wiki.archlinux.org/index.php/Steam/Game-specific_troubleshooting#Missing_non_Latin_font

That fixes my issue. Paste here:

> Portal and Portal2 use Helvetica, add the following lines to ~/.config/fontconfig/fonts.conf:
> ```xml
> <match target="pattern">
>     <test qual="any" name="family">
>         <string>Helvetica</string>
>     </test>
>     <edit name="family" mode="assign" binding="same">
>         <string>Source Han Sans CN</string>
>     </edit>
> </match>
> ```
