### ISSUE TITLE
Silhouettes of portals in coop

### ISSUE THREAD

**Issue by mkalte666** [ValveSoftware/portal2#138]
While playing coop there are sometimes silhouettes of portals visible on - i  think - random places. 
That looks like that:
![bug](https://f.cloud.github.com/assets/3924804/2308716/700cb456-a2c3-11e3-8954-6a56262122a8.jpg)

My OS is Ubuntu 13.10 64 bit with Gnome3, 8GB ram and a nvidia gforce gtx 555m.

**Comment by mariodonofrio** [comment]
I've not been able to repro this - are you still experiencing it with the latest updates?

**Comment by mkalte666** [comment]
No, its gone. I was able to reproduce this on another linux computer, but not since one of the newer updates.
