### ISSUE TITLE
Texture problem

### ISSUE THREAD

**Issue by elbunuelo** [ValveSoftware/portal2#140]
I've been able to play the game up to GLADOS' chamber and it runs pretty well, however, some textures look pretty weird.

Here are some screenshots to illustrate my point.

![textures2](https://f.cloud.github.com/assets/735791/2317365/cfb76bc6-a34a-11e3-8c59-d6c8008e503c.jpg)
![textures3](https://f.cloud.github.com/assets/735791/2317367/d0ba420a-a34a-11e3-9c1a-6913f2ec98d7.jpg)
![textures4](https://f.cloud.github.com/assets/735791/2317368/d1e88f4c-a34a-11e3-8c27-33a74ccfea60.jpg)

Thanks and keep up the good work.

**Comment by timjp87** [comment]
It would help to know what hardware and drivers you use. ;-)

Please go to Help -> System Information in the Steam client and copy all the data and post it here.

**Comment by elbunuelo** [comment]
I believe this was with the nouveau driver, after installing bumblebee-nvidia, the textures worked fine.

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  3100 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Fedora release 20 (Heisenbug)" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.5-200.fc20.x86_64
    X Server Vendor:  Fedora Project
    X Server Release:  11404000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2014-02-05

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Sandybridge Mobile 

```
Driver Version:  3.0 Mesa 9.2.5
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0xdf4
Number of Monitors:  2
Number of Logical Video Cards:  2
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 3286 x 1080
Primary Display Size: 20.04" x 11.26"  (22.95" diag)
                                        50.9cm x 28.6cm  (58.3cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel CougarPoint HDMI

Memory:
    RAM:  7879 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  245947 Mb
    Largest Free Hard Disk Block:  84570 Mb

Installed software:

Recent Failure Reports:

**Comment by davidw-valve** [comment]
I think this is likely a bug with the nouveau drivers. We recommend using Nvidia's drivers.
