### ISSUE TITLE
Shadows look like they're z-fighting in some spots

### ISSUE THREAD

**Issue by stevethepocket** [ValveSoftware/portal2#141]
I wish I had a better way to describe this. All I can really do is show some screenshots.

![sp_a1_intro10001](https://f.cloud.github.com/assets/3085348/2318876/3ee0f44c-a371-11e3-9e81-9f67de15a5d9.jpg)
![sp_a1_intro10002](https://f.cloud.github.com/assets/3085348/2318877/3ee283a2-a371-11e3-818f-a82f6a979ac2.jpg)
![sp_a1_intro10003](https://f.cloud.github.com/assets/3085348/2318878/3ee2c0a6-a371-11e3-9625-0bb1f743aa04.jpg)
![sp_a2_bts50004](https://f.cloud.github.com/assets/3085348/2318875/35da990c-a371-11e3-9e95-99519a5902d3.jpg)
![sp_a2_bts50005](https://f.cloud.github.com/assets/3085348/2318882/4e9ad88a-a371-11e3-8403-9890c16c3ff1.jpg)
![sp_a2_bts50006](https://f.cloud.github.com/assets/3085348/2318883/4e9bce20-a371-11e3-847f-09c648c83bb4.jpg)

All of these flicker wildly even when I'm standing completely still. You need to pull up some of these in full-size and flip through them to get the full effect. I haven't spotted this anywhere else, but I managed to miss the ones in the intro the first time around, so there may be more. No idea what's causing this.

OS: Kubuntu 14.04 x64 Alpha 2, Kernel 3.13.0-14-generic
Video card: ATI Radeon HD 4850
Video driver: X.Org Gallium 0.4, 3.0 Mesa 10.1.0-rc1 whatever that means

Maps exhibiting this behavior: sp_a1_intro.bsp (as Wheatley opens the cryo-pod door and then when it comes to a stop), sp_a2_bts.bsp (the neurotoxin chamber)

**Comment by mariodonofrio** [comment]
Hi steve, any chance you can try the latest amd catalyst driver?

**Comment by stevethepocket** [comment]
Sadly, no. They stopped supporting the 4000 series cards after Catalyst 13.1 last year, and even that version is no longer available on their site. Lack of support for Source under that driver (no AA without crashing, untenable framerates, the random appearance of additional visual errors over the ensuing months) is why I switched to the open-source driver recently.

**Comment by stevethepocket** [comment]
Well, it looks like the change to the shadows made in the recent patch fixed this somehow. Ran the intro map and the neurotoxin map and both were looking correct. I suspect what was happening before involved identical copies of a dynamic prop overlapping (the animated and non-animated version). I'm not sure how improving the shadow generating code would fix that, but there you are. Just to point out, though, that if any setups are designed to still use the old code for backward compatibility purposes (e.g. if the Mac version isn't updated to the new code), they'll probably still be experiencing this.

**Comment by davidw-valve** [comment]
I believe this is fixed, so closing this out. Let us know if it still occurs.
