### ISSUE TITLE
Ping tool not working

### ISSUE THREAD

**Issue by marekjedrzejewski** [ValveSoftware/portal2#142]
When playing co-op with stranger (didn't test with friend, but probably it's the same) on community maps when you click E you just hear the sound, but nothing show on screen. Guy I played with claimed that he didn't see it either. Also when E is held no menu appears.

**Comment by SleepyAkubi** [comment]
Are you pressing the right button? The default is F.

**Comment by marekjedrzejewski** [comment]
woooops, stupid me :D
