### ISSUE TITLE
Rating chambers ingame not working

### ISSUE THREAD

**Issue by marekjedrzejewski** [ValveSoftware/portal2#145]
After I finish community chamber or when I click evaluate test chamber in the menu loading with portal2 logo takes forever and when i click thumb up or down, nothing happens.
![zrzut ekranu z 2014-03-04 21 16 00](https://f.cloud.github.com/assets/6793160/2325803/62ebfddc-a3da-11e3-8b2f-917cb59e286e.png)

**Comment by ItsMeOnly** [comment]
looks like I accidentally was a few minutes faster #144

**Comment by davidw-valve** [comment]
Closing as duplicate of #144
