### ISSUE TITLE
Keyboard navigation in community chambers not working

### ISSUE THREAD

**Issue by marekjedrzejewski** [ValveSoftware/portal2#148]
I can navigate through menu using keyboard until I enter single or coop community chambers. Then I have to use mouse, because highlighted choice is not moving when pressing arrows.

**Comment by davidw-valve** [comment]
The behavior across platforms is consistent and I can't see any regressions as part of the port to Linux.

The in-game menus are navigable by mouse with some items accessible by keyboard for convenience and are also navigable by controller.
