### ISSUE TITLE
No voices in game

### ISSUE THREAD

**Issue by powdermilkman** [ValveSoftware/portal2#15]
None of the voice tracks are playing. Wheatley's voice worked for the beginning sequence after he picks the room up until the wall breaks and you enter the testing facility. No voices before that part or after have played. 

When Wheatley is talking I can hear his head movements.

I have tried to change my audio settings both in pulseaudio and in-game with no results.

My systems audio device is:
Audio device: Advanced Micro Devices, Inc. [AMD/ATI] SBx00 Azalia (Intel HDA) (rev 40)

and I am using pulseaudio on Elementary OS Luna.

**Comment by LiamDawe** [comment]
Come on dude, search. Duplicate bug report.

https://github.com/ValveSoftware/portal2/issues/5

**Comment by powdermilkman** [comment]
Yeah, sorry. Just figured out how to view all issues on github (never used it before). Any way to delete it?

**Comment by LiamDawe** [comment]
Just click the close button.
