### ISSUE TITLE
Shader problem

### ISSUE THREAD

**Issue by marekjedrzejewski** [ValveSoftware/portal2#150]
Again prison escape (act1) ( http://steamcommunity.com/sharedfiles/filedetails/?id=80745172 )

Toilet, table and the button in the beginning of the chamber are very dark. Table and the button may also have missing textures. Toilet texture can be seen when close to it, but still very dark.

Here's screenshot of this compared with windows version.
![notitle](https://f.cloud.github.com/assets/6793160/2336889/e7b661cc-a495-11e3-93af-db434b62d10a.jpg)

**Comment by marekjedrzejewski** [comment]
## Such things can be seen all throughout 'prison escape' for example when carying a cube in more shadowed areas.

Update: levels 4 and 5 doesn't have this issue

**Comment by mariodonofrio** [comment]
Should be resolved in the next build

**Comment by marekjedrzejewski** [comment]
Glad to hear that :)

**Comment by davidw-valve** [comment]
This should be fixed now.
