### ISSUE TITLE
Portal 2 crash on loading second test chamber

### ISSUE THREAD

**Issue by douglasjacobsen** [ValveSoftware/portal2#153]
While playing portal 2, the game crashes when in the first elevator and trying to load the next section. This is immediately following the "Box and button" testing room (First test room).

Here is the error log:
https://gist.github.com/douglasjacobsen/2429adcc1edead37ef65

Here is my hardware information log:
https://gist.github.com/douglasjacobsen/e22f52d43126d464611c

For reference, I previously reported this [here](https://github.com/ValveSoftware/steam-for-linux/issues/3182#issuecomment-36583006) but was asked to move it to the portal2 tracker.

This happens every time I try to pass this level, so I haven't been able to test if it happens on any other levels.

I read through the https://github.com/ValveSoftware/portal2/issues/4 and https://github.com/ValveSoftware/portal2/issues/54 bug reports, and they sound similar but they aren't quite the same. If someone decides these are the same however, feel free to make this as a duplicate and close it.

It seemed like both of the other two didn't happen all the time and the players were able to make it through at least 2 levels before their game crashed while I can't make it past the first one.

**Comment by davidw-valve** [comment]
Can you try upgrading your system to the latest version of the Nvidia drivers and see if that changes anything?

**Comment by ullgren** [comment]
I experienced the same problem at the same place in the game.  Upgrading to the latest Nvidia driver from geforce.com (for me 3.3.0 NVIDIA 331.49) and restart did help.

However now it does crash while loading the second level in Chapter 2 The Cold Bot

**Comment by davidw-valve** [comment]
@ullgren: do you have a minidump ID from the crash you can give me to look at?

**Comment by ullgren** [comment]
The funny thing is that after another full reboot (the complete cycle power off and start) I was able to play about half of chapter 2 before another crash. Two more power cycles and I am at chapter 3. (Seems we managed to implement another long awaited windows feature in Linux.) 
I also think I noted a update to the game yesterday. And after that session I actually quit the game myself. 

So I will look up a id for you after the next crash, if there is one.

**Comment by ullgren** [comment]
Recent Failure Reports:
    Tue Mar 11 13:02:56 2014 GMT: file ''/tmp/dumps/crash_20140311133242_1.dmp'', upload yes: ''CrashID=bp-0405b4b7-2329-460b-a8e9-bdbcc2140311''

**Comment by douglasjacobsen** [comment]
I haven't had a chance to update my drivers yet, but I tried with the latest updated version, and it still fails after the first test chamber.

```
Recent Failure Reports:
    Fri Mar 14 19:01:00 2014 GMT: file ''/tmp/dumps/crash_20140314130052_16.dmp'', upload yes: ''CrashID=bp-124f1ee4-7d60-4e73-be89-3c9e22140314''
    Fri Mar 14 19:07:28 2014 GMT: file ''/tmp/dumps/crash_20140314130509_1.dmp'', upload yes: ''CrashID=bp-e9a5dd1d-b685-4714-83ec-a63c12140314''
```

**Comment by jhg03a** [comment]
I've seen this error as well.  After upgrading to the latest video drivers, it still was occuring.  I dug around to see what I could find in the error log and found this.

http://askubuntu.com/questions/405656/firefox-doesnt-start-in-ubuntu-13-10

It allowed me to get through level 2.  It crashed again at level 3, simply starting up again and beating level 2 crashed.  If I reran the chown commands after each crash at the end of the level, I can get past one level at a time.

**Comment by douglasjacobsen** [comment]
I just tested the same thing. Seems like the chown commands allowed me to get through level 3, and then it died in the elevator after level 3.

**Comment by douglasjacobsen** [comment]
The weird thing is, prior to running the commands, my ~/.gnome2 dir was in root:root, and even after it crashed it was just user:user.

**Comment by kisak-valve** [comment]
Hello, is anyone still experiencing this issue on an up to date system?

**Comment by kisak-valve** [comment]
Closing as outdated.
