### ISSUE TITLE
Blue gel during scripted sequence does not appear - sp_a4_finale2

### ISSUE THREAD

**Issue by GlacialTurtle** [ValveSoftware/portal2#157]
During a sequence where a pipe breaks and falls through a walkway in front of you, blue gel is supposed to spray up and cover the end of the broken walkway to jump across. This does not happen, and instead the gel covering the end of the walkway appears out of nowhere shortly after the pipe and walkway have fallen.

First time playing through this it worked, after dying once in this area it hasn't worked since.

Screenshots:
![portal2-bluegelbug](https://f.cloud.github.com/assets/4281886/2367822/3eb6d03e-a77e-11e3-985d-dfc661ab9f54.png)

![portal2-bluegelbug2](https://f.cloud.github.com/assets/4281886/2367826/51d68c04-a77e-11e3-8c41-3270c937628c.png)

System info:

https://gist.github.com/GlacialTurtle/4de36032216a74da3d06

**Comment by SleepyAkubi** [comment]
Works fine for me. Cannot confirm.

**Comment by dizietsma** [comment]
i've just played through p2 on linux, i had the same, first time all animated fine, but i died and the second time the blue gel just magically appeared on the path instead of spurting from the pipe

diziet

**Comment by GlacialTurtle** [comment]
Appears this has been fixed as of the most recent update. Re-playing this and it now works, though the gel consistently misses the very edge of the platform (lands, just beyond the edge where it should), not sure whether that counts as a bug considering the nature of the effect is somewhat inconsistent.

Can anyone else confirm? Make sure to die at least once in that immediate area.

**Comment by dizietsma** [comment]
yep, seems fixed for me too

diziet
