### ISSUE TITLE
[DELETE PLEASE] Crash on start on Arch

### ISSUE THREAD

**Issue by Vash63** [ValveSoftware/portal2#160]
EDIT: Please close this bug. Issue occurred during update leading to unrelated crash - redownloaded game to fix that bug and when I did that Steam removed me from the Beta. Unsure what original crashing was but it appears to be fixed now that I redownloaded it and got back into the beta.

As of the latest update (BuildID: 85354) I'm unable to start the game - seems to be a problem in the portal2.sh file. When starting either directly or through Steam I get:

```
Game update: AppID 620 "Portal 2 (Beta)", ProcID 7485, IP 0.0.0.0:0
ERROR: ld.so: object '/home/vash/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
CGameStreamThread: Added instance ID 7485 for appid 620
CGameStreamThread: Set render instance ID 7485 for appid 620
/bin/sh: /home/vash/.local/share/Steam/SteamApps/common/Portal 2/portal2.sh: /bin/bash^M: bad interpreter: No such file or directory
Game removed: AppID 620 "Portal 2 (Beta)", ProcID 7485 
CGameStreamThread: Added instance ID 7486 for appid 620
```

Strangely, copying the entire document in vim, deleting the file, and then pasting it into a new file changes the error to (possibly an issue with EOLs?): 

```
./portal2.sh: line 40: /home/vash/.local/share/Steam/SteamApps/common/Portal 2/: Is a directory
```

System info:

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2d
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  5700 Mhz
    12 logical processors
    6 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.6-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11500000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2014-02-05

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 780 Ti/PCIe/SSE2

    Driver Version:  4.4.0 NVIDIA 334.21
    OpenGL Version: 4.4
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x100a
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 3760 x 1920
    Primary Display Size: 23.50" x 13.23"  (26.97" diag)
                                            59.7cm x 33.6cm  (68.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 3072 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: AV200

Memory:
    RAM:  15997 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  111420 Mb
    Largest Free Hard Disk Block:  28517 Mb

Installed software:

Recent Failure Reports:
    Tue Mar 11 02:48:41 2014 GMT: file ''/tmp/dumps/crash_20140310194823_1.dmp'', upload yes: ''CrashID=bp-f9e83e61-c205-4208-ab8d-316f32140310''
```

**Comment by GottZ** [comment]
this sh file has \r\n line termination. thats a bit wrong isnt it?

i have not tried yet to reinstall this game since 6.6 gb are quite heavy to download. i will try to get it running.. right now i experience the same issue with line 40 were ${GAMEEXE} does not refer to the actual binary but the directory

**Comment by davidw-valve** [comment]
@GottZ: Have you opted into the beta in Steam? You have to opt in to the Beta otherwise Portal 2 will not run on Linux.

**Comment by GottZ** [comment]
yes i have opted into the beta. i also revalidated the game files.

about the .sh issue: it seems like portal2.sh sure is terminated by <CR><LF> wich makes it impossible to find /bin/bash<CR> to execute the sh file.

after changing line termination to unix standard (<LF>) it runs fine.

however, line 40 resolves into this:
`/home/gottz/.local/share/Steam/SteamApps/common/Portal 2/`
wich means, it tries to do the following:

`${DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"` where `"${GAMEROOT}"/${GAMEEXE}` resolves into the path i stated above.

btw. i'm missing a binary like portal2_linux or something like that. all i see in that directory is a windows executable and one for mac os

**Comment by davidw-valve** [comment]
How did you opt in to the beta? This issue looks like you aren't opted in.

If you right-click on Portal 2 in Steam and go Properties -> Betas what setting is "Select the beta you would like to opt into" set to?

**Comment by GottZ** [comment]
oh. i thought the steam beta is enough to run it. thanks. now it updated portal 2. and successfully started it.
