### ISSUE TITLE
Game saves in test mode of editor.

### ISSUE THREAD

**Issue by andOlga** [ValveSoftware/portal2#162]
As of now, the game saves whenever you test a chamber you made in the editor. Not sure whether this is the intended behaviour, probably not considering those saves can't be loaded if the chamber changes or you discard it.

**Comment by davidw-valve** [comment]
Is this different behavior on Linux than on Windows?

**Comment by andOlga** [comment]
I am unsure, I have no Windows machine to test. Would like someone to
confirm.

**Comment by SleepyAkubi** [comment]
This is normal behaviour.
