### ISSUE TITLE
Game won't start even after opting into Portal 2 (Beta) [beta]

### ISSUE THREAD

**Issue by nycki93** [ValveSoftware/portal2#167]
YES. I have opted in.

When I run the game from the Steam Library, my icon turns green, then back to blue without any new windows opening.

When I run portal2.sh from the terminal, I get the error "Failed to load the launcher (libuuid.so.1: cannot open shared object file: No such file or directory)."

I'm running 64-bit Linux Mint 16 with AMD graphics.

**Comment by tazhate** [comment]
try this (under root):
apt-get update && apt-get install ia32-libs -y

**Comment by STurtle75** [comment]
I had exactly the same problem. However, I needed to install the package `libtxc_dxtn` instead.

If running the command `force_s3tc_enable=true steam` gets you any further, then installing this package should help. This got the game running, albeit with many graphics errors, which went away for me after installing the package above (and switching to the proprietary nVidia driver, which I did simultaneously, so I don't know which one was truly responsible).

You can also determine if this is the case by running `steam` from a console, so that you see all kinds of messages displayed. If the error message `GL_EXT_texture_compression_s3tc` (or something with `s3tc`) is among them, then installing `libtxc_dxtn` ought to help.

_(PS: Another issue that I then found is that Portal2 desires `glibc` in version 2.19 or above, but from what I read, a lower version might only cause crashes later on during the game.)_

**Comment by davidw-valve** [comment]
@nupanick: Steam should provide libuuid.so.1 in a path much like ~/.local/share/Steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libuuid.so.1

Can you please locate this file (just do a "find ~/.local -name libuuid.so.1" if necessary) and then run ldd on it and post the results?

**Comment by nycki93** [comment]
@davidw-valve Okay, before doing anything else, I ran ldd libuuid.so.1, and this was the output:

```
linux-gate.so.1 =>  (0xf772a000)
libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf7556000)
/lib/ld-linux.so.2 (0xf772b000)
```

I will now try the update recommended by @tazhate and see if that solves it.

Update: After doing apt-get install ia32-libs -y, the output from ldd libuuid.so.1 changed to

```
linux-gate.so.1 =>  (0xf779e000)
libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf75c4000)
/lib/ld-linux.so.2 (0xf779f000)
```

And the error message from portal2.sh changed to

```
SDL video target is 'x11'
SDL video target is 'x11'

SDL failed to create GL compatibility profile (whichProfile=0!
SDL failed to create GL compatibility profile (whichProfile=0!

This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system DOES NOT support the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system DOES NOT support the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system DOES NOT support the OpenGL extension GL_EXT_direct_state_access.
This system DOES NOT support the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system DOES NOT support the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system DOES NOT support the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system DOES NOT support the OpenGL extension GL_EXT_texture_compression_s3tc.
This system DOES NOT support the OpenGL extension GL_EXT_texture_compression_dxt1.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system DOES NOT support the OpenGL extension GLX_EXT_swap_control_tear.
This application requires either the GL_EXT_texture_compression_s3tc, or the GL_EXT_texture_compression_dxt1 + GL_ANGLE_texture_compression_dxt3 + GL_ANGLE_texture_compression_dxt5 OpenGL extensions. Please install S3TC texture support.
This application requires either the GL_EXT_texture_compression_s3tc, or the GL_EXT_texture_compression_dxt1 + GL_ANGLE_texture_compression_dxt3 + GL_ANGLE_texture_compression_dxt5 OpenGL extensions. Please install S3TC texture support.
```

After installing libtxc-dxtn-s2tc0 and libtxc-dxtn-s2tc0:i386, I am able to launch from Steam. So this particular issue appears to be closed.
