### ISSUE TITLE
Game won't launch

### ISSUE THREAD

**Issue by noahmartinwilliams** [ValveSoftware/portal2#168]
I click on the "play" button and a window comes up telling me it's preparing to launch the game, but it never launches the game. I've tried running .local/share/Steam/SteamApps/common/Portal\ 2/portal2.sh directly but it gives me a bad interpreter error (probably uses DOS line endings instead of Unix line endings.) Also I don't see any Linux compatible executable there.

**Comment by davidw-valve** [comment]
Please read the readme at https://github.com/ValveSoftware/portal2/ in particular this part:

"Important: To play Portal 2 on Linux you must opt-in to the beta. You may do this by right-clicking on Portal 2 (Beta) in Steam, clicking Properties -> Betas and then select 'beta' from the drop-down. If you do not do this, Portal 2 will not run on Linux"
