### ISSUE TITLE
Cannot start Portal 2 at all

### ISSUE THREAD

**Issue by MaddieM4** [ValveSoftware/portal2#169]
When I hit the "Play" button in the Steam interface, I get a _very brief_ view of a popup that the game is being started, and then the popup goes away, and the game never starts.

If I run Steam via terminal to catch errors, I this:

```
Game update: AppID 620 "Portal 2 (Beta)", ProcID 5796, IP 0.0.0.0:0
 ERROR: ld.so: object '/home/philip/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
CGameStreamThread: Added instance ID 5796 for appid 620
CGameStreamThread: Set render instance ID 5796 for appid 620
/bin/sh: 1: /home/philip/.local/share/Steam/SteamApps/common/Portal 2/portal2.sh: not found

(steam:5685): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent. <- repeated numerous times

OnFocusWindowChanged to window type: k_EWindowTypeNonSteamDesktop, 0
```

**Comment by MaddieM4** [comment]
When attempting to run the game directly via the shell script, there are a few problems. The immediate one is that bash is choking on the DOS-style line endings, so I converted it to UNIX-style, as per http://vim.wikia.com/wiki/File_format

But the next problem is that $GAMEEXE is not set - maybe Steam is supposed to be setting it, but it ends up being an empty string. Should it be pointing to portal2_osx?

**Comment by ItsMeOnly** [comment]
Did you opt-in to beta? This has been fixed quite a while ago: in fact, here the game is starting fine.

**Comment by timjp87** [comment]
"Portal 2 is now available on Linux as a beta.

Important: To play Portal 2 on Linux you must opt-in to the beta. You may do this by right-clicking on Portal 2 (Beta) in Steam, clicking Properties -> Betas and then select 'beta' from the drop-down. If you do not do this, Portal 2 will not run on Linux"

https://github.com/ValveSoftware/portal2/blob/master/README.md

**Comment by MaddieM4** [comment]
Ah, I thought the fact that there was (Beta) in the game name meant I was already set up with the Linux beta. Now I feel like a dumbass for failing to RTFM, but hey, I have a working beta of Portal 2, so I can live without an ego for a few days.
