### ISSUE TITLE
Unable to change ingame audio language

### ISSUE THREAD

**Issue by SymLynks** [ValveSoftware/portal2#177]
When changing the audio language in the ingame audio settings, there is a message pop-up that notifies me that I need to restart the game to change the language. Accepting this message will close the game but won't restart it. When starting the game manually the audio language setting is back to it's default value.
Arch Linux x64, German client, trying to switch from German to English audio.

**Comment by davidw-valve** [comment]
Thank you for reporting this. Expect it to be fixed in the next update.

**Comment by davidw-valve** [comment]
Should be fixed now. Please let us know if it doesn't work for you.

**Comment by DevinWatson** [comment]
Slightly unrelated, would it be possible to get update change log announcements on the official Portal 2 group? Like ya'll were doing for other Valve games: http://steamcommunity.com/app/220/announcements

**Comment by ghost** [comment]
Same problem here, i think the bug is still present :/
Arch linux x64, Spanish Client

**Comment by davidw-valve** [comment]
This problem should definitely be fixed.

Now if you change the audio language in-game it will close the game, then most likely require downloading an update before re-launching the game. Then the game will be using the language you chose.

**Comment by SymLynks** [comment]
Sorry for the late reply, I've got no update notification.
It's still not working for me.
Change audio language from German to English -> game has to re-launch and closes -> automatic re-launch without getting an update -> audio language is back to German again.

**Comment by ghost** [comment]
System crashed so i had to reinstall everything.
Even after the update it's still not working at all
The game is in Spanish, i wanted the english voices and spanish subtitles
