### ISSUE TITLE
segmentation fault at 1st elevator

### ISSUE THREAD

**Issue by amarao** [ValveSoftware/portal2#179]
After 1st elevator, when next stage is loading, game crashing:

/home/amarao/.local/share/Steam/SteamApps/common/Portal 2/portal2.sh: line 46:  4861 Segmentation fault      ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@

Crashdump: http://stashbox.org/1447077/crash_20140327220205_1.dmp

Linux x220 3.13-1-amd64 #1 SMP Debian 3.13.7-1 (2014-03-25) x86_64 GNU/Linux
ii  glx-alternative-nvidia               0.4.1                          i386         allows the selection of NVIDIA as GLX provider
ii  libgl1-nvidia-glx:i386               331.49-1                       i386         NVIDIA binary OpenGL libraries
ii  libnvidia-ml1:i386                   331.49-1                       i386         NVIDIA Management Library (NVML) runtime library
ii  nvidia-alternative                   331.49-1                       i386         allows the selection of NVIDIA as GLX provider
ii  nvidia-driver                        331.49-1                       i386         NVIDIA metapackage
ii  nvidia-installer-cleanup             20131102+1                     i386         cleanup after driver installation with the nvidia-installer
ii  nvidia-kernel-3.13-1-amd64           331.49+1+1+3.13.4-1            i386         NVIDIA binary kernel module for Linux 3.13-1-amd64
ii  nvidia-kernel-common                 20131102+1                     i386         NVIDIA binary kernel module support files
ii  nvidia-kernel-dkms                   331.49-1                       i386         NVIDIA binary kernel module DKMS source
rc  nvidia-settings                      319.82-1                       i386         tool for configuring the NVIDIA graphics driver
ii  nvidia-support                       20131102+1                     i386         NVIDIA binary graphics driver support files
ii  nvidia-vdpau-driver:i386             331.49-1                       i386         NVIDIA vdpau driver
ii  xserver-xorg-video-nvidia            331.49-1                       i386         NVIDIA binary Xorg driver
ii  steam-launcher                       1.0.0.47                       all          Launcher for the Steam software distribution service
hardware:

cpu:
model name      : Intel(R) Core(TM)2 Quad CPU    Q8300  @ 2.50GHz
microcode       : 0xa07

01:00.0 VGA compatible controller: NVIDIA Corporation G94 [GeForce 9600 GT](rev a1) (prog-if 00 [VGA controller])
        Subsystem: ASUSTeK Computer Inc. Device 82ad
        Flags: bus master, fast devsel, latency 0, IRQ 46
        Memory at fd000000 (32-bit, non-prefetchable) [size=16M]
        Memory at d0000000 (64-bit, prefetchable) [size=256M]
        Memory at fa000000 (64-bit, non-prefetchable) [size=32M]
        I/O ports at ac00 [size=128]
        [virtual] Expansion ROM at fc000000 [disabled] [size=512K]
        Capabilities: <access denied>
        Kernel driver in use: nvidia

**Comment by davidw-valve** [comment]
Which version of the Nvidia drivers do you have installed on your system?

**Comment by amarao** [comment]
331

**Comment by amarao** [comment]
Today (28-04-2014) update fix the problem. Thanks!
