### ISSUE TITLE
Portal 2 Beta will not open

### ISSUE THREAD

**Issue by imjustjoshua** [ValveSoftware/portal2#181]
I don't know enough specifics to know exactly what the issue is (or if it's been reported already) - I just know my Portal 2 won't open.

I tried running steam and then the game in Terminal, and this is what I got:

joshua@speedy:~$ steam
Running Steam on ubuntu 13.04 64-bit
STEAM_RUNTIME is enabled automatically
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Gtk-Message: Failed to load module "overlay-scrollbar"
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
[0329/165542:WARNING:proxy_service.cc(958)] PAC support disabled because there is no system implementation
Unable to apply SteamVR update because source path is empty
Unable to apply SteamVR update because source path is empty
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Generating new string page texture 2: 48x256, total string texture memory is 49.15 KB
Generating new string page texture 3: 384x256, total string texture memory is 442.37 KB
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
`menu_proxy_module_load': /media/storage/joshua/Steam/ubuntu12_32/steam: undefined symbol: menu_proxy_module_load

(steam:10365): Gtk-WARNING **: Failed to load type module: (null)

Adding licenses for the following package(s): 0, 34, 216, 469, 1787, 4560, 7932, 8500, 8535, 8538, 12158, 12328, 13391, 13632, 13698, 14476, 14545, 14871, 15147, 16373, 16549, 16610, 16705, 17172, 17250, 17641, 17793, 18359, 18485, 18856, 18978, 19223, 25544, 25597, 26266, 26862, 27035, 27227, 27248, 27602, 28021, 29547, 29760, 29909, 30033, 30542, 31974, 31975, 32889
roaming config store loaded successfully - 213 bytes.
migrating temporary roaming config store
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
ExecCommandLine: "/media/storage/joshua/Steam/ubuntu12_32/steam"
System startup time: 16.59 seconds
OnFocusWindowChanged to window type: k_EWindowTypeSteamDesktop, 0
Running Steam on ubuntu 13.04 64-bit
STEAM_RUNTIME has been set by the user to: /media/storage/joshua/Steam/ubuntu12_32/steam-runtime
Generating new string page texture 72: 256x256, total string texture memory is 704.51 KB
Generating new string page texture 73: 128x256, total string texture memory is 835.58 KB
Generating new string page texture 74: 128x256, total string texture memory is 131.07 KB
Generating new string page texture 75: 64x256, total string texture memory is 901.12 KB
Generating new string page texture 76: 8x256, total string texture memory is 909.31 KB
Generating new string page texture 77: 32x256, total string texture memory is 942.08 KB
ExecCommandLine: "/home/joshua/.steam/root/ubuntu12_32/steam steam://open/driverhelperready"
ExecSteamURL: "steam://open/driverhelperready"
Generating new string page texture 90: 256x256, total string texture memory is 393.22 KB
Generating new string page texture 91: 128x256, total string texture memory is 1.07 MB
Generating new string page texture 101: 128x256, total string texture memory is 1.20 MB
Generating new string page texture 102: 256x256, total string texture memory is 1.47 MB
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
Game update: AppID 620 "Portal 2 (Beta)", ProcID 10460, IP 0.0.0.0:0
ERROR: ld.so: object '/media/storage/joshua/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
/bin/sh: 1: /media/storage/joshua/Steam/SteamApps/common/Portal 2/portal2.sh: not found
CGameStreamThread: Added instance ID 10460 for appid 620
CGameStreamThread: Set render instance ID 10460 for appid 620
CGameStreamThread: Added instance ID 10461 for appid 620

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
Game removed: AppID 620 "Portal 2 (Beta)", ProcID 10460 
Starting SteamVR runtime update on exit from app 620
Unable to apply SteamVR update because source path is empty

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.

(steam:10365): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
Installing breakpad exception handler for appid(steam)/version(1393366296_client)
OnFocusWindowChanged to window type: k_EWindowTypeNonSteamDesktop, 0

**Comment by dscharrer** [comment]
You need to opt into the beta for Portal 2 under Properties → Betas.

If done, the game should show up as "Portal 2 (Beta) [Beta]" in the library.

**Comment by imjustjoshua** [comment]
Worked great! Thanks!

**Comment by dscharrer** [comment]
Cool, don't forget to close this issue then (there's a "Close" button below the comment box).
