### ISSUE TITLE
Graphics faulty [Intel HD 3000]

### ISSUE THREAD

**Issue by drgeek95** [ValveSoftware/portal2#183]
The game starts normally, no errors until a new (singleplayer) game is started: There is a mostly black screen, only the instructions ("look up/down", "walk") are visible.
Also, when creating a new test chamber, the chamber itself is all black, only when adding elements (which are displayed as black squares in the selection menu) the elements can be seen.
When running steam in a terminal, I can see this message while creating a test chamber (i. e.):
`Reference Count for Material models/props_map_editor/palette/budget_error (1) != 0`
System is a newly installed Linux Mint 16, all updates applied. 
GPU: Intel HD 3000, RAM: 4GB

**Comment by Tele42** [comment]
There is a high probability you are missing 32 bit s2tc which is needed for proper rendering of source games on intel. This is a duplicate of #84, #166.
I'm guessing that you're looking for:
<code> sudo apt-get install libtxc-dxtn-s2tc0 libtxc-dxtn-s2tc0:i386 </code>

**Comment by drgeek95** [comment]
Yes, that solved it.

**Comment by piranna** [comment]
I have the same issue. Shouldn't Steam has this packages as dependencies, or install them when a game that needs them?

**Comment by piranna** [comment]
Ok, yes, the trick was to install the i386 version of the package :-)
