### ISSUE TITLE
Co‐op chapter numbers are cropped

### ISSUE THREAD

**Issue by johndrinkwater** [ValveSoftware/portal2#19]
Replaced with 0..
http://steamcommunity.com/sharedfiles/filedetails/?id=232204598

**Comment by davidw-valve** [comment]
I could never reproduce this, but is it fixed for you with the latest update?

**Comment by johndrinkwater** [comment]
This appears fixed with the latest update, thanks http://steamcommunity.com/id/johndrinkwater/screenshot/612793117694125409
