### ISSUE TITLE
Credits display goofy in 1440p

### ISSUE THREAD

**Issue by aus4000** [ValveSoftware/portal2#191]
Um.... yeah :)

![2014-04-10_00001](https://cloud.githubusercontent.com/assets/2880687/2676541/0026e184-c13b-11e3-8945-27a8382c863a.jpg)
![2014-04-10_00002](https://cloud.githubusercontent.com/assets/2880687/2676542/03ec948a-c13b-11e3-85e9-bd6b54cac59f.jpg)

**Comment by aus4000** [comment]
My graphics card is a GTX 650 and the driver the blob version 334.21. Arch Linux x86_64 and GNOME Shell 3.10. Let me know if you need anything else from me.

**Comment by kisak-valve** [comment]
Hello @aus4000, per "- Fixed the credits being corrupted on Linux." in the [2021-02-18](https://store.steampowered.com/oldnews/81067) Portal 2 update, please retest this issue.

**Comment by kisak-valve** [comment]
Closing as fixed.
