### ISSUE TITLE
Portals shine through things in the environment. Blue portal goes through the chair

### ISSUE THREAD

**Issue by kosiara** [ValveSoftware/portal2#193]
When you look at the portals through other things (like chair, walls etc.) it's still visible. In other words - walls do not hide/mask portals.

http://i.imgur.com/wBoFdbB.jpg

http://i.imgur.com/XyEUUC6.jpg

Ubuntu 14.04, 64-bit

Intel® Core™2 Duo CPU E8500 @ 3.16GHz × 2 
Gallium 0.4 on AMD RV770
AMD HD 4870

**Comment by kosiara** [comment]
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x17
    CPU Stepping:  0x6
    CPU Type:  0x0
    Speed:  3166 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 14.04 LTS (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-24-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11501000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2014-02-05

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD RV770

```
Driver Version:  3.0 Mesa 10.1.0
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x9440
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1680 x 1050
Desktop Resolution: 1680 x 1050
Primary Display Size: 18,66" x 11,65"  (21,97" diag)
                                        47,4cm x 29,6cm  (55,8cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC888

Memory:
    RAM:  3952 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  70960 Mb
    Largest Free Hard Disk Block:  9365 Mb

Installed software:

Recent Failure Reports:
    Fri Apr 18 15:04:11 2014 GMT: file ''/tmp/dumps/crash_20140418170357_2.dmp'', upload yes: ''CrashID=bp-990c7157-350a-4d3f-abe9-2f0002140418''

**Comment by mariodonofrio** [comment]
This is 'as designed', it's not a bug - it's to help you see where you've placed the portals, very useful in the more complex maps (a smooth outline of the portal and square corner elements are drawn on top of everything else, you're not seeing the actual portal itself). I believe there is a convar or menu option to turn that feature off but don't have a running build to confirm.
