### ISSUE TITLE
Co‐op cutscene video audio peaks

### ISSUE THREAD

**Issue by johndrinkwater** [ValveSoftware/portal2#20]
Completed last few levels of co‐op, the audio during the cutscene and credits is too loud. It occurs in other videos too, just to a lesser extent.

**Comment by leinardi** [comment]
I can confirm this, same problem in the Community Test Chambers intro video.

**Comment by Arbitrary007** [comment]
I have noticed this as well. Turning down the volume in the audio settings to half does not affect the video volume.

EDIT: And if I didn't mention it, it happens in all the bonus videos, too. EG: The Aperture Turrets video.
