### ISSUE TITLE
portal2.sh breaks because of DOS line ending

### ISSUE THREAD

**Issue by jleclanche** [ValveSoftware/portal2#202]
`
/bin/sh: /home/adys/.local/share/Steam/SteamApps/common/Portal 2/portal2.sh: /bin/bash^M: bad interpreter: No such file or directory
`

**Comment by dscharrer** [comment]
https://github.com/ValveSoftware/portal2/search?q=portal2.sh%3A+%2Fbin%2Fbash^M%3A+bad+interpreter%3A+No+such+file+or+directory&ref=cmdform&type=Issues

**Comment by jleclanche** [comment]
Right, didnt search, only looked in the open issues.... nvm.
