### ISSUE TITLE
Cannot start Portal 2 at all under 64-bit Debian, no output in console

### ISSUE THREAD

**Issue by knuta** [ValveSoftware/portal2#208]
When I try to launch the Portal 2 beta, it just displays “Preparing to launch Portal 2 (beta)...” for a split second, and then closes the window. I see the color of the Portal 2 entry change briefly in the list of games, and Steam says I've played Portal 2 for 1 minute today.

I have opted into the Steam 2 beta.

The console output mentions nothing about Portal 2 (in fact it prints nothing after steam has started), and I have been unsuccessful in my search for a log file with anything helpful in it. I tried adding --verbose to steam hoping that that would make a difference, but that didn't do anything either.

I also tried moving the whole ~/.steam folder away, thus reinstalling everything, but it didn't make a difference. I am running on an i5-4670K using the built-in graphics processor (HD Graphics 4600).

This is all the output I'm getting from Steam:

> knuta@obelisk ~ $ steam
> Running Steam on debian  64-bit
> STEAM_RUNTIME is enabled automatically
> [2014-05-04 10:40:54] Startup - updater built May  1 2014 15:18:29
> [2014-05-04 10:40:54] Opted in to client beta 'publicbeta' via beta file
> You are in the 'publicbeta' client beta.
> [2014-05-04 10:40:54] Verifying installation...
> [2014-05-04 10:40:54] Verification complete
> Running Steam on debian  64-bit
> STEAM_RUNTIME has been set by the user to: /home/knuta/.steam/ubuntu12_32/steam-runtime

At first I was suspicious of the reference to ubuntu12_32, but it seems this is always the case on Debian. I did have the Ubuntu package installed briefly before one for Debian was available, though, but I uninstalled it using apt before installing the official Debian package.

Is there any way I can make Steam or Portal 2 output any kind of debugging info?

**Comment by jimmyhon** [comment]
Check /tmp/dumps/knuta_stdout.txt, that may give you more info.

**Comment by knuta** [comment]
Thanks for the tip! There is a /tmp/dumps folder, but unfortunately it doesn't contain anything.

**Comment by Plagman** [comment]
You need to opt into the Portal 2 Beta branch as well from the game properties. It should read "Portal 2 (Beta) [beta]" in your library.

**Comment by davidw-valve** [comment]
You need to opt in to the Portal 2 Beta. The game should then be listed as Portal 2 (beta) [beta] in your Steam library.
