### ISSUE TITLE
No source code available on github

### ISSUE THREAD

**Issue by cemeyer** [ValveSoftware/portal2#21]
Abusing github as an issue tracker for a closed source project is pretty gross. Why should github host your project's issue-tracking infrastructure if your repository consists of a single README file?

**Comment by Ads20000** [comment]
ERM, there's nothing stopping them and quite a few Linux users are familiar with GitHub anyway so why use a different issue tracker? They are helping improve the quality of the game for us Linux users and so help us to stick to our favourite OS. I see nothing wrong with this. If GitHub really hated this they would remove it.

**Comment by martinml** [comment]
GitHub advises exactly that: https://help.github.com/articles/issues-only-access-permissions

**Comment by Ads20000** [comment]
Haha, lol.

**Comment by cemeyer** [comment]
@Martinml Do they actually (pay to) host private repositories with Github? That's what that help text is referring to.

**Comment by Ads20000** [comment]
Ah good point, we don't know for sure. The article only details how to have a private repo with a public issues tracker. I reiterate my previous point though - if GitHub doesn't take this down (which they didn't with Data 2), then this is a perfectly acceptable use of GitHub and should encourage more people to use it for issue logging and hopefully code hosting.

**Comment by cemeyer** [comment]
@Ads20000 Yeah, I am making an assumption. Apologies if it's wrong. But Github is not a charity and Valve is quite profitable :-).

**Comment by ghost** [comment]
I believe in assumption from taken pictures from Valve's offices on open doors days that Valve hosts their own private Git repository outside of GitHub. They use that internal Git server to track issues privately. This GitHub repository was opened to give players a chance of reporting issues more conveniently.
There's nothing wrong with this GitHub repository, it contributes to a software project (although a proprietary one). GitHub welcomes projects like these. I've seen some long-standing abuse that still remains up on GitHub, such as storing personal information and CVs that should fall out of scope and GitHub's interests.
Regardless, this issue ticket is pretty silly and should be closed.

**Comment by hikari-no-yume** [comment]
To be fair, Valve _is_ using GitHub to host actual source code, just not for Portal 2. Note the Half-Life and Source 2013 SDKs.

**Comment by frewsxcv** [comment]
> But Github is not a charity and Valve is quite profitable

@cemeyer What makes you think GitHub isn't profitable?

**Comment by mimoo** [comment]
@cemeyer just my 2cents before this gets out of control: this is good publicity for github. People get to use it only for "commenting", which takes near to zero resource (negligible) for github, and it introduces github to people who've never heard of it before.

**Comment by davidw-valve** [comment]
We have been using GitHub for some time to manage bug tracking for a variety of our SteamOS related projects. We talked to GitHub before opening our repositories and they are very happy with our usage model.

**Comment by anaisbetts** [comment]
We don't mind, rows in a database are cheap :sparkles:

**Comment by cemeyer** [comment]
Apologies for the noise, folks. Keep on rocking on :).
