### ISSUE TITLE
Portal 2 black screen with Xmonad.

### ISSUE THREAD

**Issue by thinkallabout** [ValveSoftware/portal2#211]
I am using Xmonad as my WM and when I try to launch Portal 2, I just get a black screen. 
I can still move the mouse however I can't actually do anything else. Alt-Tab won't switch windows and I can't move to different workspaces.

I can successfully launch the game if I use the "-windowed" launch option.  I am running the latest version of Xmonad and Debian Wheezy stable.

**Comment by ItsMeOnly** [comment]
all Valve apps are very picky about window manager. Believe me, I'm using legacy MWM (and 5Dwm) and having the same issue.

**Comment by thinkallabout** [comment]
Hmm..  must be a universal problem with the source engine in general so I guess this isn't a Portal 2 specific issue then.
