### ISSUE TITLE
OS X [not linux specific]: cannot go through a particular portal

### ISSUE THREAD

**Issue by jeanlain** [ValveSoftware/portal2#215]
In the 2nd test chamber where you are supposed to press 3 different buttons (to first get the cube and then place it on the super button), the portal associated with the button on the left part of the chamber (leading to the super button) cannot be used. I just can't go through it and the cube disappears if I try to pass through it with the cube.

OS X 10.9.3. Latest beta as of 16th May.

**Comment by davidw-valve** [comment]
Thank you for reporting this. We want to make sure that when we take the current version out of beta it doesn't regress other platforms so we greatly appreciate your testing on OS X.

The bug is fixed in the latest update. I would greatly appreciate you testing again and confirming the fix though!

**Comment by jeanlain** [comment]
Yes it appears to be fixed. But notice how the shadows change when going through portals in this room (https://github.com/ValveSoftware/portal2/issues/194).
