### ISSUE TITLE
Portal 2 BETA @Linux_x86_64

### ISSUE THREAD

**Issue by ibuk01** [ValveSoftware/portal2#220]
Hi!

First "problem" : I had to do a script-conversion using "dos2unix" because the shell-script "portal2.sh" was formatted the wrong way. But also after converting the script there is no call for an ELF/Linux-executable set inside the script. The "$GAMEEXE" will only be set if the script runs on a MAC. I did a "find . -type f -exec file {} \; | grep ELF" from the Portal-2-gamedirectory but there even is not even one elf-binary installed.

Please help.

Regards,
Ingo

**Comment by dscharrer** [comment]
You need to opt into the beta, as described in [the readme](https://github.com/ValveSoftware/portal2#readme).
