### ISSUE TITLE
 `GLIBCXX_3.4.20' not found (required by /usr/lib/llvm/libLLVM-3.4.so)

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/portal2#223]
This is related to the cherry picking of the right lib version and symbols of the c++ standard lib.

steam beta client log extract:
https://gist.github.com/sylware/718f5bc7afc2b58b87aa

Running an up-to-date x86_64 fedora rawhide

**Comment by sylware** [comment]
The temporary fix is as usual:
in $(you_dir)/Steam/SteamApps/common/Portal 2/bin/ to rename libstdc++.so.6 to libstdc++.so.6.wait_for_elf_dyn_loading_fix

**Comment by ItsMeOnly** [comment]
You are using LLVM linked libs for your linux installation whereas steam does not. Therefore your fix isn't just temporary - it's a required action - otherwise you can also set LD_PRELOAD to your libstdc++

**Comment by sylware** [comment]
On Mon, Jun 30, 2014 at 10:27:48AM -0700, ItsMeOnly wrote:

> You are using LLVM linked libs for your installation whereas
> steam does not. Therefore your fix isn't just temporary - it's
> a required action - otherwise you can also set LD_PRELOAD to
> your libstdc++

The underlying issue seems to be that steam is using a version of
the libstdc++ and the GFX stack which pulls llvm then the system
version of the libstdc++. Pb: both components pulls the same
major version fo the libstdc++ (need to check), but there is a
symbol version mismatch.
To avoid that, the steam runtime should be able to link to its
version of the libstdc++ and let llvm (pulled by the use of
the GFX stack) pulls its libstdc++.

Are you telling me that LD_PRELOAD (or LD_LIBRARY_PATH) value
syntax is able to tell the ELF dynamic linker how explicitely do
that?

**Comment by ItsMeOnly** [comment]
Ughhh, somehow all of my reply got lost, so here's an abridged version ;-)

> To avoid that, the steam runtime should be able to link to its version of the libstdc++ and let llvm (pulled by the use of the GFX stack) pulls its libstdc++

This is basically impossible as you cannot map two sets of the same symbols within one stack (if you try, you get segfault'ed immediately). What puzzles me is why the game doesn't barf on loading MESA's libGL immediately, but only on loading DRI modules.

> Are you telling me that LD_PRELOAD (or LD_LIBRARY_PATH) value syntax is able to tell the ELF dynamic linker how explicitely do that?

LD_PRELOAD is simply a better way of dealing with multiple versions of the same library - you just force your own to be loaded first to resolve any symbols. Consider that you'd need otherwise to delete libstdc++ from game repository after every update. LD_LIBRARY_PATH is useless, because steam overwrites it when creating game environment.

**Comment by sylware** [comment]
On Thu, Jul 03, 2014 at 04:41:22PM -0700, ItsMeOnly wrote:

> > To avoid that, the steam runtime should be able to link to
> > its version of the libstdc++ and let llvm (pulled by the use
> > of the GFX stack) pulls its libstdc++
> 
> This is basically impossible as you cannot map two sets of the
> same symbols within one stack (if you try, you get segfault'ed
> immediately). What puzzles me is why the game doesn't barf on
> loading MESA's libGL immediately, but only on loading DRI
> modules.

Well, steam could dynamically load its libstdc++ and get
pointers to the symbol it needs, then leave any "downstream" 
libstdc++ being linked. Since its libstdc++ is bundle with it,
then could "manually" init it.
What seems the best solution is proper versioned symbols to
allow more than one version of the libstdc++ in a process.

> > Are you telling me that LD_PRELOAD (or LD_LIBRARY_PATH) value
> > syntax is able to tell the ELF dynamic linker how explicitely
> > do that?
> 
> LD_PRELOAD is simply a better way of dealing with multiple
> versions of the same library - you just force your own to be
> loaded first to resolve any symbols. Consider that you'd need
> otherwise to delete libstdc++ from game repository after every
> update. LD_LIBRARY_PATCH is useless, because steam overwrites
> it when creating game environment.

Then it's a no to my question.

**Comment by sylware** [comment]
portal2 has no elf issue anymore on my custom system.
