### ISSUE TITLE
Linux version of Portal 2 crashes on 'A Beam Too Far' map

### ISSUE THREAD

**Issue by hxka** [ValveSoftware/portal2#224]
[Link to the map](http://steamcommunity.com/sharedfiles/filedetails/?id=98548469).

Game crashes when both buttons in the first room are pressed.

I'm using x86-64 Chakra.

**Comment by NeoTheFox** [comment]
Can confirm on Mint 17 amd64.

**Comment by hxka** [comment]
The map doesn't cause game to crash anymore after it's been updated today.
