### ISSUE TITLE
Portal 2 can not start on linux out of the box: libtmalloc_minimal and S3TC texture support

### ISSUE THREAD

**Issue by benelot** [ValveSoftware/portal2#227]
Hello,

I just wanted to point out an issue and the fix that I found for it, but probably it would help if the problem could be fixed directly in portal 2 so that the game would run out of the box.

When I installed portal two and first tried to run it (with the beta opted in), it did not start, so I search for the executable and ran it from the terminal. So I found that the problem was this:
./portal2_linux: error while loading shared libraries: libtcmalloc_minimal.so.4: cannot open shared object file: No such file or directory

The problem here is that libtcmalloc_minimal4 is not installed by default. The library originally belonging to the gperftools has its own package in several linux distributions and on my x86 architecture machine with linux mint on it, I could fix this by installing the package via apt-get install libtcmalloc_minimal4.

When I tried to apply my fix on my other computer with an am64 architecture, the fix did not work properly. The problem was that now my libtcmalloc_minimal4 package had the wrong ELF class. Which makes sense as I am no longer in an x86 environment and the game was obviously compiled against the x86 version of it.

I installed the x86 version of libtcmalloc_minimal4 by:

*downloading the package directly from here:
http://packages.ubuntu.com/raring/i386/libtcmalloc-minimal4/download

*following this procedure (taken from http://community.linuxmint.com/tutorial/view/370)

---

First we are going to install some 32-Bit libraries which are needed to run 32-Bit applications:

Open up Terminal and type:
sudo apt-get install ia32-libs

and enter your password if it asks

Now we are going to open in the Folder were you 32-Bit deb files is by using the command:
cd 'Folder Location'

Were folder location is (Of course enter the folder location) or go to the folder, right click and click 'Open In Terminal'.

Now we are going to force the 32-Bit deb to be forced into installing for the 64-Bit Linux Mint:

sudo dpkg -i --force-architecture package.deb

---

Now portal 2 could be started, but I had the problem that it had this problem:

"Required OpenGL extension "GL_EXT_texture_compression_s3tc" is not supported. Please install S3TC texture support."

In my case, I checked these links:
http://steamcommunity.com/app/221410/discussions/0/864959336401282074/
http://askubuntu.com/questions/231176/how-do-i-install-s3tc

and the second proposed solution was working for me:
me@terminal> force_s3tc_enable=true steam

By this I could startup steam and then run portal 2 from there, which made the game start.

I also documented this problem and the solution here:
http://steamcommunity.com/app/620/discussions/0/540734792346277708/?insideModal=1

Now my questions: can this be solved within the beta so that people do not have to fiddle around with this? And now that I am already here, why do you have portal 2 beta and then you have to opt into a beta [beta] to even try to play the game on linux? I mean without the opt-in beta, the script (portal2.sh is not even correctly finished to run on linux.) (as aslready discussed here: https://github.com/ValveSoftware/steam-for-linux/issues/3174).

I just want to help you guys to fix it. So please ask me any detail I missed out here that you need.

**Comment by ItsMeOnly** [comment]
Actually: the S3TC is a well known issue when you're using MESA GL, for some reason it's not installed by default but as separate package - so that's for Ubuntu packagers.

The second issue - TCMalloc should have been supplied with portal2, at least I have it in my portal2 cache:
-rwxr-xr-x 1 rambo rambo 968800 Feb 26 21:30 libtcmalloc_minimal.so.4

**Comment by davidw-valve** [comment]
Yes, libtcmalloc_minimal.so.4 is shipped with Portal 2. Try validating your cache or redownloading if you don't see it.

**Comment by benelot** [comment]
S3TC was installed actually,all I had to do is to force steam to use it. I did not install it,it was already there. TCMalloc is never shipped with me, no matter how many times I redownload it. I download it inside of steam and then opt-in to the beta. But it is not there.

**Comment by benelot** [comment]
I mean portal 2 is there but TCMalloc is not.

**Comment by ItsMeOnly** [comment]
well, I just did a full re-download, and...
-rwxr-xr-x 1 rambo rambo 968800 Feb 26 21:30 libtcmalloc_minimal.so.4
appeared in my Portal 2 cache.

As for S3TC not being enabled, it seems to be related to Intel video drivers on x64 arch, otherwise, if you have GL compiled with texture compression, it should be enabled automatically - you can see that from other people's success. You don't list your hardware - maybe we should start from there.

**Comment by peldax** [comment]
Hi guys,
I am running 64 opensuse tumbleweed and I am having problem with tcmalloc.

peldax@openSUSE:~/.local/share/Steam/SteamApps/common/Portal 2> ./portal2_linux
./portal2_linux: error while loading shared libraries: libtcmalloc_minimal.so.4: cannot open shared object file: No such file or directory

I have tcmalloc_minimal.so.4 shipped in /Portal 2/bin directory
I have installed gperftools from repositories as well.

Could anyone help me with this issue please?

**Comment by ItsMeOnly** [comment]
you are trying to start portal2 manually: to do that you need to set environment, at least you could set LD_LIBRARY_PATH (or LD_LIBRARY64_PATH).

peldax@openSUSE:~/.local/share/Steam/SteamApps/common/Portal 2> LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./portal2_linux

**Comment by peldax** [comment]
aaaaah :)
thank you for your advice, i knew i was missing something stupid.

good job and thank you

peldax

**Comment by ghost** [comment]
Does any of this work for the new Portal 2 mod, Portal Stories: Mel?

**Comment by phiresky** [comment]
@Deraj82901 for me, going into the Portal Stories Mel folder and copying the libraries from Portal 2 with `cp ../Portal\ 2/bin/*.so bin` worked

**Comment by ghost** [comment]
Yeah, i ended up doing that the other day. Thanks a bunch though!

**Comment by nathanph** [comment]
This answer provided a working solution for me running on Ubuntu 16.10 x64.

http://superuser.com/a/1130577

---

Today's Debian testing on amd64 doesn't seem to have an ia32-libs package so I had to:

install `libuuid1:i386`
remove Portal 2's copy of `libstdc++.so.6` from `~/.steam/steam/steamapps/common/Portal 2/bin`
install `libfontconfig1:i386`
install `libfreetype6:i386`
install `libopenal1:i386`
