### ISSUE TITLE
Controller: Cannot apply video settings

### ISSUE THREAD

**Issue by Terin** [ValveSoftware/portal2#23]
When you change a video option in the settings menu, you have to press the "Apply Changes" button with the mouse. When using a controller, you can change settings, but pressing B will only give you the option to discard the settings, or change them again.

The Y button could be used as an "Apply Changes" button, perhaps, since the X button is set to "Use Defaults".

**Comment by Skiski** [comment]
I confirm that I have the exact same problem and that I have to use the mouse to apply the changes each time I go into this menu. The button Start could be used to valid.

**Comment by davidw-valve** [comment]
This is fixed in the latest update (press Y on the controller to apply changes).

**Comment by Terin** [comment]
The update added the ability to apply settings on the main video menu with the Y button, but not on the advanced video settings menu, so it's not quite there.

Thank you for implementing the button, though, this was a little issue with using a controller that was quite problematic.
