### ISSUE TITLE
Puzzle maker compiles a map once, then fails forevermore

### ISSUE THREAD

**Issue by jerome1232** [ValveSoftware/portal2#234]
When I build a test champer with puzzlemaker it works the first time, compiles the map fine. Upon rebuilds it fails with the following error:

Could not execute the command:
   /home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/bin/vbsp_linux -entity_limit 1750 -game /home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/portal2/ /home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/sdk_content/maps/preview.vmf 
error message:
   ""

VBSP failed.

Failed to start process ("/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/bin/vbsp_linux" -entity_limit 1750 -game "/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/portal2/" "/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/sdk_content\maps/preview.vmf") with working dir (/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/bin/)

Verifying game cache is succesfull, the only way I've found to get it to compile again (and it works only once) is to uninstall and reinstall the game.

**Comment by davidw-valve** [comment]
Can you try running the command it gives manually? These steps:

(1) open a terminal
(2) cd "/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/sdk_content\maps/preview.vmf"
(3) "/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/bin/vbsp_linux" -entity_limit 1750 -game "/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/portal2/" "/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/sdk_content\maps/preview.vmf"

**Comment by jerome1232** [comment]
That may be part of the problem actually, I just noticed that first command has one backslash where it should have a forward slash in between sdk_content and maps.

ie

/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/sdk_content/maps/preview.vmf

instead of

/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/sdk_content\maps/preview.vmf

**Comment by jerome1232** [comment]
I get this:

jeremy@jeremy-132-CK-NF79:~$ cd /home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/bin/
jeremy@jeremy-132-CK-NF79:~/.local/share/Steam/SteamApps/common/Portal$ "/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/bin/vbsp_linux" -entity_limit 1750 -game "/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/portal2/" "/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/sdk_content/maps/preview.vmf"
/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/bin/vbsp_linux: error while loading shared libraries: libtcmalloc_minimal.so.4: cannot open shared object file: No such file or directory

Edit: I tried installing libtcmalloc_minimal and now I get the error:

error while loading shared libraries: libtcmalloc_minimal.so.4: wrong ELF class: ELFCLASS64

I'm trying to find out if there is a 32 bit version of this library...

**Comment by jerome1232** [comment]
Ok I have installed the 32 bit version 
[code]sudo apt-get install libtcmalloc_minimal4:i386[/code]

and now I"m on to another library libteir0.so, I can't figure out what package would provide that library. if this is a 64 bit/32 bit issue I'm vastly confused about how it worked once....

**Comment by Tele42** [comment]
For the sake of timely troubleshooting, you may want to add steam's base set of libraries to your LD_LIBRARY_PATH.

Maybe something like this as step 3:

```
LD_LIBRARY_PATH=~/.local/share/Steam/ubuntu12_32/:$LD_LIBRARY_PATH "/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/bin/vbsp_linux" -entity_limit 1750 -game "/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/portal2/" "/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/sdk_content\maps/preview.vmf"
```

note: this is not a permanent change to LD_LIBRARY_PATH, it's just for this one command.

**Comment by jerome1232** [comment]
`~/.local/share/Steam/SteamApps/common/Portal/bin$ LD_LIBRARY_PATH=~/.local/share/Steam/ubuntu12_32/:$LD_LIBRARY_PATH "/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/bin/vbsp_linux" -entity_limit 1750 -game "/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/portal2/" "/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/sdk_content/maps/preview.vmf"`

gets me:

`/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/bin/vbsp_linux: Symbol``g_VProfCurrentProfile' has different size in shared object, consider re-linking
/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/bin/vbsp_linux: symbol lookup error: /home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/bin/vbsp_linux: undefined symbol: g_pMemAlloc
`

**Comment by jerome1232** [comment]
Okay, so if I set LD_LIBRARY_PATH to ~/.local/share/STeam/SteamApps/common/Portal\ 2/bin/, the command runs from the commandline.

```
"/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/bin/vbsp_linux" -entity_limit 1750 -game "/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/portal2/" "/home/jeremy/.local/share/Steam/SteamApps/common/Portal 2/sdk_content/maps/preview.vmf"
Valve Software - vbsp.exe (Jul  9 2014)
1 threads
Could not start the empty shader (shaderapiempty)!
```

So I guess the question is how can I get that to set automatically when I launch portal, and why isn't it looking in the right spots for libraries in the first place?

**Comment by Tele42** [comment]
You can set env variables per game in the launch options ( VARIABLE=value %command% ) of the game, but Portal should already be looking to that directory in normal operation.

**Comment by jerome1232** [comment]
Setting it inside launch options didn't seem to work. :(

I did implement a work around by creating a ld.so.conf file which adds directories for ld to look in for libraries.

`sudo nano /etc/ld.so.conf.d/portal2libs.conf`

Inside that text file I placed the absolute path to the libraries vbsp_linux needs.

`/home/jeremy/.local/share/Steam/SteamApps/common/Portal\ 2/bin`

Saved the file then ran ldconfig to add the changes

`sudo ldconfig`

It worked, at least last night it did. But for some reason today, it's not working again. vbsp_linux can find it's libraries now due to my workaround, running it manually from a command line still works as expected, but when I load up portal 2 and try to compile a map it fails with the same old error message as before.

Why is vbsp_linux dynamically linked any ways? If all the libraries ship with portal, shouldn't it be static linked to them?

**Comment by dreznichuk** [comment]
I was trying to compile maps for Team Fortress 2, and compilers for Portal 2, as I know, the only compilers for Linux
I was getting all the same errors, as for me setting LD_LIBRARY_PATH is not a problem because i'm running it in script, maybe you can write some script to launch Portal too

But i still had problem with "Could not start the empty shader (shaderapiempty)!"

thats why i started searching in proc fs 
i wrote simple script to copy information about process (cmd line args, environ) while portal comipe map (vbsp do his work very fast)

Then i noticed very interesting environment variable PORTAL2_NO_LAUNCHERMGR_REQUIRED_IN_MATERIAL_SYSTEM=1
I added this var to my script, and vbsp compiled successfully

I did not have much time to test all others compilers, and compile complete map, but i hope this will help

**Comment by jerome1232** [comment]
The issue seems to have been resolved in updates, it is no longer an issue for me.
