### ISSUE TITLE
Scripted events not always working

### ISSUE THREAD

**Issue by ksthiele** [ValveSoftware/portal2#24]
Sometimes nothing is happening until I hit ESC twice, then it usually works

**Comment by davidw-valve** [comment]
Can you give an example of this? A place in-game it happens with steps on how to repro?

**Comment by ksthiele** [comment]
It happens, by just starting the game, e.g. It says I should move with WASD forever, until I press ESC, or the first time we land in the small glass cabin, where portal 1 started, nothing happens there until I press ESC. next time I will start it over the terminal or with the ingame command line and see if there is something weird happening.

I also noticed that the voice of the robot didn't work the first few minutes. (Edit: ok you already clarified that on the github page)

**Comment by ksthiele** [comment]
I couldn't reproduce it anymore. can be closed, I'll post the bug once I encounter it again, but next time with substantial information
