### ISSUE TITLE
cannot start anymore

### ISSUE THREAD

**Issue by sylware** [ValveSoftware/portal2#244]
up-to-date fedora rawhide on x86_64, non-beta steam client, radeon R9 280X (tahiti xt).
(dota2 and CSGO start fine)

I get in steam log:

libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  80
  Current serial number in output stream:  81
Game removed: AppID 620 "Portal 2", ProcID 2764 
crash_20150221042030_5.dmp[2759]: Finished uploading minidump (out-of-process): success = yes
crash_20150221042030_5.dmp[2759]: response: CrashID=bp-d80bed29-ff3b-4011-9927-42fcb2150220
crash_20150221042030_5.dmp[2759]: file ''/tmp/dumps/crash_20150221042030_5.dmp'', upload yes: ''CrashID=bp-d80bed29-ff3b-4011-9927-42fcb2150220'

**Comment by davidw-valve** [comment]
You imply that you once were able to start Portal 2. Do you know when it started failing for you?

**Comment by sylware** [comment]
On Fri, Feb 20, 2015 at 08:43:47PM -0800, davidw-valve wrote:

> You imply that you once were able to start Portal 2. Do you know when it started failing for you?

I haven't played portal 2 for a great while and I just noticed it stopped
working yesterday. (I was able to finish portal2 from A to Z, 60 fps 1920x1200
without any glitch)

Sorry that's all I can tell. I'm a dev (kernel included), you can ask me
hardcore troubleshooting stuff.
Only bad thing: I still use mainstream fedora with all its kludge which can be a
show stopper for me.

regards,

## 

Sylvain

**Comment by ase1590** [comment]
i can confirm this also happens on Arch using the OSS radeon driver. 
however, portal 2 has never worked for me out of the box. 

libGL error: unable to load driver: r600_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: r600
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  78
  Current serial number in output stream:  79

it seems starting steam by using:

DRI_PRIME=1 LD_PRELOAD="/usr/lib/libstdc++.so.6 /usr/lib32/libstdc++.so.6 /usr/lib/libgcc_s.so.1 /usr/lib32/libgcc_s.so.1" ~/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh steam

at least allows portal 2 to launch and run for me.

gcc version: 4.9.2

**Comment by zack6849** [comment]
same here

Game update: AppID 620 "Portal 2", ProcID 26712, IP 0.0.0.0:0
libGL error: unable to load driver: r600_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: r600
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  80
  Current serial number in output stream:  81
Game removed: AppID 620 "Portal 2", ProcID 26712

**Comment by sylware** [comment]
On Thu, May 07, 2015 at 05:32:08PM -0700, Zack Craig wrote:

> same here
> 
> Game update: AppID 620 "Portal 2", ProcID 26712, IP 0.0.0.0:0
> libGL error: unable to load driver: r600_dri.so
> libGL error: driver pointer missing
> libGL error: failed to load driver: r600
> libGL error: unable to load driver: swrast_dri.so
> libGL error: failed to load driver: swrast
> X Error of failed request:  BadValue (integer parameter out of range for operation)
>   Major opcode of failed request:  155 (GLX)
>   Minor opcode of failed request:  3 (X_GLXCreateContext)
>   Value in failed request:  0x0
>   Serial number of failed request:  80
>   Current serial number in output stream:  81
> Game removed: AppID 620 "Portal 2", ProcID 26712 

I have a near full git stack now (still need to add the linux git directly from
AMD radeon devs). Portal 2 does start again, but hangs after a while and tons
of glitch.

I'm currently trying to figure out what's wrong.

## 

Sylvain

**Comment by sylware** [comment]
I have everything from git now.

The radeon driver for SI (tahiti xt) is heavily broken:
- tons of artefacts/glitches on the screen
- choppy action (unplayable)

**Comment by sylware** [comment]
portal2 is quite fine now.
