### ISSUE TITLE
Crash at start any level with 32 cores

### ISSUE THREAD

**Issue by toalex77** [ValveSoftware/portal2#252]
I recently upgraded my workstation from 2x 8 cores Opteron to 2x 16 cores Opteron and Portal 2 started to crash at entering in any level after loading it.
If I disable some core, lowering the total amount of cores below 32, the game back to work again without any problem.
Curiously this map http://steamcommunity.com/sharedfiles/filedetails/?id=462188663&searchtext=bigger start without problems even with 32 cores enabled.

**Comment by toalex77** [comment]
My system informations from Steam client:

> Processor Information:
>     Vendor:  AuthenticAMD
>     CPU Family:  0x15
>     CPU Model:  0x2
>     CPU Stepping:  0x0
>     CPU Type:  0x0
>     Speed:  2000 Mhz
>     32 logical processors
>     16 physical processors
>     HyperThreading:  Supported
>     FCMOV:  Supported
>     SSE2:  Supported
>     SSE3:  Supported
>     SSSE3:  Supported
>     SSE4a:  Supported
>     SSE41:  Supported
>     SSE42:  Supported
> 
> Network Information:
>     Network Speed:  
> 
> Operating System Version:
>     "openSUSE 13.2 (Harlequin) (x86_64)" (64 bit)
>     Kernel Name:  Linux
>     Kernel Version:  4.1.0-2.ga2813fe-desktop
>     X Server Vendor:  The X.Org Foundation
>     X Server Release:  11601000
>     X Window Manager:  KWin
>     Steam Runtime Version:  steam-runtime-release_2015-01-06
> 
> Video Card:
>     Driver:  ATI Technologies Inc. AMD Radeon (TM) R9 200 Series
> 
>    Driver Version:  4.4.13372 Compatibility Profile Context 15.101.1001
>     OpenGL Version: 4.4
>     Desktop Color Depth: 24 bits per pixel
>     Monitor Refresh Rate: 60 Hz
>     VendorID Not Detected
>     DeviceID Not Detected
>     Number of Monitors:  1
>     Number of Video Cards Not Detected
>     Primary Display Resolution:  1920 x 1080
>     Desktop Resolution: 1920 x 1080
>     Primary Display Size: 20.51" x 11.54"  (23.50" diag)
>                                             52.1cm x 29.3cm  (59.7cm diag)
>     Primary VRAM Not Detected
> 
> Sound card:
>     Audio device: 
> 
> Memory:
>     RAM:  32105 Mb
> 
> Miscellaneous:
>     UI Language:  English
>     LANG:  en_US.UTF-8
>     Microphone:  Not set
>     Total Hard Disk Space Available:  9388827 Mb
>     Largest Free Hard Disk Block:  1676544 Mb
> 
> Installed software:

**Comment by toalex77** [comment]
Temporarily, a simple work-around can be to run this command:

> for c in $(seq 1 2 31) ; do echo 0 > /sys/devices/system/cpu/cpu${c}/online ; done

as root, before start the game.
And this

> for c in $(seq 1 2 31) ; do echo 1 > /sys/devices/system/cpu/cpu${c}/online ; done

to re-enable the disabled cores.

**Comment by toalex77** [comment]
Ok, it's enough even if I disable just 4 cores.
So the workaround become:

> for c in {28..31} ; do echo 0 > /sys/devices/system/cpu/cpu${c}/online ; done

and

> for c in {28..31} ; do echo 1 > /sys/devices/system/cpu/cpu${c}/online ; done

to re-enable them.

**Comment by dimitertodorov** [comment]
Still an issue. Just built a rig with AMD Threadripper. 
This helps on windows.
https://github.com/b-desconocido/portal2start

**Comment by kisak-valve** [comment]
Closing per "Fixed crashes on multi-core and multi-CPU systems that can allocate more than 32 threads." in the [2018-03-05](http://www.thinkwithportals.com/blog.php?id=37827) Portal 2 update.
