### ISSUE TITLE
Voice audio is broken

### ISSUE THREAD

**Issue by picandocodigo** [ValveSoftware/portal2#26]
Using Debian, Portal 2 beta audio doesn't work for voice acting. When Wheatley starts talking in the first scene, the audio is all scrambled. I had to enable the captions to see what he was saying. His voice does sound at a part where the music starts, but then goes away again. The Narrator voice can't be heard either.

Music and other FX sounds are ok.

Please let me know what other info -if any- can help.

**Comment by dscharrer** [comment]
Duplicate of #5 

See [this comment](https://github.com/ValveSoftware/portal2/issues/5#issuecomment-36083539) for manual steps required to fix it.

**Comment by picandocodigo** [comment]
Thanks! I am now downloading an update so I'll wait to see if it's fixed or if I should do the manual fix.
