### ISSUE TITLE
Rock shader broken?

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/portal2#265]
This is in the condemned testing facility. The shader for the rocky surface surrounding everything looks way different from what I remember. It is much glossier and light in color. It does not look correct at all. Is this intentional or a bug? I don't like it.

https://www.youtube.com/watch?v=mABLFlRecP0

I'm on Linux.
**Kernel:** Linux 4.4.1
**Graphics card:** Radeon R9 Fury X
**Driver:** The new fglrx

**Comment by Plagman** [comment]
That doesn't look normal, but we haven't seen this issue before so it might be specific to your graphics driver. Are others seeing this as well?

**Comment by netfab** [comment]
Yes, while playing a new game I'm seeing this on gentoo with :
Kernel : 4.4.6
GPU : GeForce GTX 560
Drivers : nvidia-drivers-361.28

Edit : screenshots :
![20160502113337_1](https://cloud.githubusercontent.com/assets/1150555/14951570/33283f4a-105a-11e6-903b-640182c7acc9.jpg)
![20160502113419_1](https://cloud.githubusercontent.com/assets/1150555/14951572/3cc6c62a-105a-11e6-8b95-9d8fd85655d3.jpg)

**Comment by Tynach** [comment]
I'm on Linux, but this isn't a Linux-only problem. Here are a couple threads that include Windows users having this problem too:

http://steamcommunity.com/app/620/discussions/0/483368526576322856/
http://steamcommunity.com/sharedfiles/filedetails/?id=594483209

**Comment by vfjpl** [comment]
Confirmed.

**Comment by MatteoRagni** [comment]
I'm seeing this too:
with shader **Very High**
![screenshot from 2016-08-07 11-20-14](https://cloud.githubusercontent.com/assets/4260219/17461542/0f899380-5c91-11e6-8f20-83c4b7722eb8.png)
With shader **Medium**
![screenshot from 2016-08-07 11-26-36](https://cloud.githubusercontent.com/assets/4260219/17461575/fce87600-5c91-11e6-868d-1cdd0391d69b.png)

Kernel : Linux  4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux
GPU : GeForce GTX 750m X2 in SLI
Drivers : nvidia-drivers-367.35 + libtxc_dxtn

**Comment by mark101tay** [comment]
I'm guessing that it is a problem with the material file when the bumpmap is applied to the surface. Maybe it makes it changes the shader to a GenericUnlit? I'm sure Valve could easily fix if they looked at it.

**Comment by kisak-valve** [comment]
Per "- Fixed a full-bright material in cavern areas." in the [2017-01-24 Portal 2](http://store.steampowered.com/news/27045/) update, please retest.

**Comment by netfab** [comment]
Seems to work fine for me now, thanks.

**Comment by KuriKai** [comment]
Also seems to work fine for me too. Thanks

**Comment by kisak-valve** [comment]
Thanks for retesting, closing.
