### ISSUE TITLE
Steam controller via in-home streaming: Configs broken

### ISSUE THREAD

**Issue by b3nn0** [ValveSoftware/portal2#277]
Hi,
I'm trying to play Portal 2 via in-home streaming with my steam controller. Host and client are both Linux.
I don't have a Windows machine to double check if the issue exists there.

General procedure seems to work. When I select one of the "Configuration Templates" for the steam controller config, things seem to work mostly (well, the configs are bad, but they work).

However, when I select e.g. Valve's recommended steam controller config (or one of the community configs), the input isn't recognized.

The main difference I noticed (and this is why I report it as a Portal bug - even though I'm not sure if that's 100% correct, might also be a steam controller API bug. Please forward it to the respecitve team in that case) is:
While the config templates use a generic gamepad mapping (i.e. button X mapped to gamepad button X, button Y mapped to gamepad button Y, etc), the community/Valve configs seem to be aware of the game's capabilities. In the controller config overlay, the buttons are mapped to their actions (e.g. X = jump, Y = crouch, ...). However, this doesn't seem to work at all - input is not recognized.

**Comment by kisak-valve** [comment]
Hello @b3nn0, as far as I can tell this issue is being tracked at https://github.com/ValveSoftware/steam-for-linux/issues/3786. Closing in favor of that issue report.
