### ISSUE TITLE
Portal 2: Sound loops, then freezes, then crashes

### ISSUE THREAD

**Issue by tbo77** [ValveSoftware/portal2#278]
Portal 2 starts normal, it freezes after about 1 minute during gameplay. (No problems in menu.) When graphics freezes, the sound begins to loop the last 300ms or so. After 20 to 30 seconds the game crashes (or steam shuts it down, idk). 

This is happening on a new laptop, some specs:

OS: Ubuntu 16.04.2
Intel® Core™ i7-7500U CPU @ 2.70GHz × 4
Intel® HD Graphics 620 (Kabylake GT2)

Other games like Civ 5, The Talos Principle, Trine 2  and Cities: Skylines run without problems. (Okay, with Cities it's more like slowly walking, but never the less, it doesn't crash :-) )

I'd gladly attach more information, please tell me what you need and where I can find it. 

Thanks!

**Comment by kisak-valve** [comment]
Hello @tbo77, Mesa 12.0.6 provided by Ubuntu 16.04 updates is from 2017-01-24 and was branched from development on 2016-05-30 seems awfully close to Kabylake's shipping date of 2017-01-03. Can you re-test with a newer version of mesa? I suggest trying [Padoka's stable mesa PPA](https://launchpad.net/~paulo-miguel-dias/+archive/ubuntu/pkppa) for the latest point release of mesa.

**Comment by tbo77** [comment]
Wow, thank you, worked perfectly. Only thing I'm wondering: Will Ubuntu 16.04 eventually (in the next point release?) include this? And, will I be able to remove this PPA then and get back to 'stock' packages? And how?

I guess I will find out then. Thanks again!

**Comment by kisak-valve** [comment]
You should check with your distro's community for questions like that. Personally, I doubt that there will be many more official mesa updates on a LTS branch of Ubuntu.

**Comment by worldofgeese** [comment]
This is still an issue in Ubuntu 20.04 on a Dell XPS 13 9380.
