### ISSUE TITLE
ubuntu 17.04 crash before launch

### ISSUE THREAD

**Issue by tatsujb** [ValveSoftware/portal2#280]
Hello

trying to ru portal2 on my newly installed ubuntu 17.04 i get this : 
t@ts:/media/t/e9f70369-a3af-4c6e-b2cf-57ade77c38de/SteamLibrary/steamapps/common/Portal 2$ ./portal2.sh 
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: radeonsi_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: radeonsi
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request: BadValue (integer parameter out of range for operation)
Major opcode of failed request: 155 (GLX)
Minor opcode of failed request: 3 (X_GLXCreateContext)
Value in failed request: 0x0
Serial number of failed request: 84
Current serial number in output stream: 85

I know there exists the AMDGPU-PRO driver but only for 16.04 currently. will this be patched or is it not even a driver-related issue

thank you

**Comment by kisak-valve** [comment]
Hello @tatsujb, this issue is being tracked at #248. The libstdc++ library which is bundled with the game is too old to be used with your version of mesa. Either LD_PRELOAD the system variant or remove the bundled library. Closing as a duplicate.
