### ISSUE TITLE
Game Crash: intel_do_flush_locked

### ISSUE THREAD

**Issue by SustainingTherapies** [ValveSoftware/portal2#281]
Hello!

I am trying to run Portal 2, but whenever I start the game, it works correctly until the second awakening in the first level, whereupon the audio starts to loop the last ~0.5 seconds, and the game crashes about ~45 seconds thereafter. I have already looked through the tickets described here, and none of the fixes seem to help. When the game crashes, there is a message in the terminal:

```
intel_do_flush_locked failed: Input/output error
/home/my_username/.local/share/Steam/steamapps/common/Portal 2/portal2.sh: line 51:  3097 Segmentation fault      (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
Game removed: AppID 620 "Portal 2", ProcID 3097 
```

I am on Ubuntu 16.04, using kernel 4.8.0-54-generic.

I tried several fixes to work around this issue. The only one that worked was setting LIBGL_ALWAYS_SOFTWARE=1 before starting steam. This option, however, results in unplayably low frame rates, for obvious reasons.

I am using a Lenovo Ideapad 700. Below is the output of lspci, for specific hardware information:

```
00:00.0 Host bridge: Intel Corporation Sky Lake Host Bridge/DRAM Registers (rev 07)
00:01.0 PCI bridge: Intel Corporation Sky Lake PCIe Controller (x16) (rev 07)
00:02.0 VGA compatible controller: Intel Corporation Skylake Integrated Graphics (rev 06)
00:14.0 USB controller: Intel Corporation Sunrise Point-H USB 3.0 xHCI Controller (rev 31)
00:14.2 Signal processing controller: Intel Corporation Sunrise Point-H Thermal subsystem (rev 31)
00:16.0 Communication controller: Intel Corporation Sunrise Point-H CSME HECI #1 (rev 31)
00:17.0 SATA controller: Intel Corporation Sunrise Point-H SATA Controller [AHCI mode] (rev 31)
00:1c.0 PCI bridge: Intel Corporation Sunrise Point-H PCI Express Root Port #5 (rev f1)
00:1c.5 PCI bridge: Intel Corporation Sunrise Point-H PCI Express Root Port #6 (rev f1)
00:1d.0 PCI bridge: Intel Corporation Sunrise Point-H PCI Express Root Port #9 (rev f1)
00:1e.0 Signal processing controller: Intel Corporation Sunrise Point-H LPSS UART #0 (rev 31)
00:1f.0 ISA bridge: Intel Corporation Sunrise Point-H LPC Controller (rev 31)
00:1f.2 Memory controller: Intel Corporation Sunrise Point-H PMC (rev 31)
00:1f.3 Audio device: Intel Corporation Sunrise Point-H HD Audio (rev 31)
00:1f.4 SMBus: Intel Corporation Sunrise Point-H SMBus (rev 31)
01:00.0 3D controller: NVIDIA Corporation GM107M [GeForce GTX 950M] (rev a2)
02:00.0 Network controller: Intel Corporation Intel Dual Band Wireless-AC 3165 Plus Bluetooth (rev 99)
03:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15)
04:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller (rev 01)
```

I have tried using the stable mesa packages, as suggested in #278, as well as trying with both noveau and the proprietary Nvidia drivers.

Please ask if you need more details, and thank you for your support.

**Comment by kisak-valve** [comment]
Hello @SustainingTherapies, after this issue occurs, can you check dmesg for a report of a gpu hang? This is most likely a video driver issue.

Since you are experiencing this issue with a new version of mesa, this issue should be brought to the attention of the mesa devs. [Possible upstream bug reports](https://bugs.freedesktop.org/buglist.cgi?quicksearch=intel_do_flush_locked%20failed).

-separately-

Your report hints that you have an Optimus laptop, and you may have better luck looking into setting up bumblebee.

**Comment by SustainingTherapies** [comment]
Dmesg says:

```
[timestamp] [drm] GuC firmware load skipped
[timestamp] [drm] RC6 on
[timestamp] drm/i915: Resetting chip after gpu hang
```

Does this indicate a driver issue?

Upstream bugs have similar issues already reported; I'll add my observations there.

**Comment by kisak-valve** [comment]
Yes, this is an Intel driver issue.

**Comment by SustainingTherapies** [comment]
In that case, thank you for the help, and I will go track down Intel's driver's bug tracking system.
