### ISSUE TITLE
Portal 2 does'nt open

### ISSUE THREAD

**Issue by McConha** [ValveSoftware/portal2#284]
**I've searched for a solution for my issue but I don't got it
So if this is duplicated, sorry
I use Manjaro 64-bits**
CPU: _Intel core i3-4170 @ 3.70Ghz_
GPU: _Intel HD graphics_
OpenGL: _3.0_
MESA: _17.1.3_
Memory: _8GB_

**I try to open the game but it doesn't opens
Steam says that the game is running and I found 2 process on ksysguard but this is only**

Sorry for bad english

**Comment by kisak-valve** [comment]
Hello @McConha, this issue is being tracked at #248. Remove the game bundled libstdc++.so.6 in `~/.local/share/Steam/steamapps/common/Portal 2/bin`. Closing as a duplicate.
