### ISSUE TITLE
Native linux exec hangs instead of launching (but fine under wine)

### ISSUE THREAD

**Issue by Abscissa** [ValveSoftware/portal2#285]
When I try to launch the Linux version of Portal 2 on my Linux machine (all software and drivers are up-to-date), the portal 2 executable hangs without ever actually starting (ie, I can see the executable and a launch script for it in my process manager, but no window, sound or visuals ever start. It just stays on the desktop and I have to manually sigkill it).

However, very ironically, on the exact same Linux installation, running the Windows version of Portal2 under Wine works fine. (The linux version of Half-Life 2 also works fine.) It would be nice to get the native Linux version of Portal 2 working though, at the very least so it's one less game I have to switch over to steam-wine (or reboot into Win10) to play.

https://help.steampowered.com/en/wizard/HelpRequest/HT-5JCX-QYNV-B563

**Comment by Plagman** [comment]
Hi,

Can you post your system information as per the issue template? Can you try attaching to the portal2 process when it's sitting there and getting a backtrace for all threads?

**Comment by Abscissa** [comment]
>Can you try attaching to the portal2 process when it's sitting there and getting a backtrace for all threads?

How do I do that? (I'm familiar with the commandline, so no worries there.)

>Can you post your system information as per the issue template?

```
Computer Information:
    Manufacturer:  Unknown
    Model:  Unknown
    Form Factor: Laptop
    No Touch Input Detected

Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i3-4030U CPU @ 1.90GHz
    CPU Family:  0x6
    CPU Model:  0x45
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  1900 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    "Manjaro Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  4.4.75-1-MANJARO
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11903000
    X Window Manager:  KWin
    Steam Runtime Version:  <Runtime disabled>

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Haswell Mobile x86/MMX/SSE2
    Driver Version:  3.0 Mesa 17.1.4
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x8086
    DeviceID:  0xa16
    Revision Not Detected
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 35.04" x 19.69" (40.16" diag)
                                            89.0cm x 50.0cm (102.0cm diag)
    Primary VRAM Not Detected

Sound card:
    Audio device: Intel Haswell HDMI

Memory:
    RAM:  7911 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Total Hard Disk Space Available:  921130 Mb
    Largest Free Hard Disk Block:  524105 Mb
    VR Headset: None detected

Recent Failure Reports:
```

**Comment by kisak-valve** [comment]
Hello @Abscissa, this issue is being tracked at #248. You should be able to remove the game-bundled libstdc++.so.6 to work around this issue. Closing as a duplicate.
