### ISSUE TITLE
Can't Start Portal 2

### ISSUE THREAD

**Issue by jeteokeeffe** [ValveSoftware/portal2#29]
(steam:3244): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
/bin/sh: 1: /home/jete/Steam/SteamApps/common/Portal 2/portal2.sh: not found
CGameStreamThread: Added instance ID 3543 for appid 620
Game removed: AppID 620 "Portal 2 (Beta)", ProcID 3542

**Comment by jeteokeeffe** [comment]
Going to delete and reinstall, hopefully that fixes it

**Comment by dscharrer** [comment]
#10, #13 and http://steamcommunity.com/games/221410/announcements/detail/1585569369676516320

**Comment by jeteokeeffe** [comment]
yah, just read the readme in the issues section. my bad
