### ISSUE TITLE
Segfault in libstdc++ upon launch

### ISSUE THREAD

**Issue by Webbeh** [ValveSoftware/portal2#292]
[  743.468061] portal2_linux[4346]: segfault at f7ca0e9c ip 00000000f7ca0e9c sp 00000000ffba0bdc error 15 in libstdc++.so.6.0.24[f7ca0000+6000]

Latest portal 2 update.
GCC 7.2.0.3
GLIBC 2.26.5
Binutils 2.29.1-1
(same version for their 32 bit counterparts)

Downgrading to GCC libs 7.2.0.1, binutils 2.28.0.4 and GLIBC 2.25.7 doesn't fix it, and this was the latest known working version here. I suspect the latest portal update breaks something.

**Comment by Webbeh** [comment]
Related ? 
https://github.com/ValveSoftware/csgo-osx-linux/issues/565

**Comment by kisak-valve** [comment]
Hello @Webbeh, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. In particular, if you can find any CrashIDs or minidumps related to this issue, please include them in this issue report.

**Comment by Webbeh** [comment]
Well, upgrading to the latest linux kernel fixed it.

Sorry about that.
