### ISSUE TITLE
Portal 2 "engine error"

### ISSUE THREAD

**Issue by GmanRO** [ValveSoftware/portal2#294]
Whenever i launch Portal 2 it goes to the screen where its shown Chell vs Glados / P-Body on a light bridge screen , then it crashes and says in a letterbox named "Engine Error" : "Steam is not running . You must start steam in order to play this game" .
I have installed a cracked version just to see if that runs on my laptop and sure enough it worked perfectly {i only did it for test purposes i do not have it installed} . I have tried everything [ and yes i did launch through Steam ] . When i tried compatibility mode it wont even come up .
I did do a file cache this is the 3rd time i am installing it and the same error appears . Yes i tried exiting and going back into steam . I did try out a mod for it {time machine game/mod} which needs it in order to run and it worked perfect even on higher settings with 720p
Specs :
Laptop
-intel core i3
-intel hd 5500 family graphics
-4 gb ram
-A ssd
-Windows 10
NOTES :
-Other games that run on source work , like cs:go/gmod . 
-Also i have a issue with tf2 since the jungle inferno update and it states im not connected to the Team fortress 2 server coordintator .
-I only bought the game about 3/4 days ago with cs:go and gmod .

**Comment by kisak-valve** [comment]
Hello @GmanRO, this issue tracker is limited to Portal 2 on Linux. You'll want to use [Steam Support](https://help.steampowered.com/en/) to get help with your issue.
