### ISSUE TITLE
Aiming with mouse does not work

### ISSUE THREAD

**Issue by gitoso** [ValveSoftware/portal2#297]
When start the game, mouse buttons and the scrolling works well, but mouse movement does not move the aim. If I pause the game, mouse does work normally in the menu.

I am actually using Arch Linux with i3 desktop.

**Comment by kisak-valve** [comment]
Hello @gitoso, two things to try, first, does enabling raw mouse input in the settings help?

If not, then what input system are you using (xf86-input-mouse, xf86-input-evdev, or libinput) and does adding `SDL_VIDEO_X11_DGAMOUSE=0 %command%` to Portal 2's launch options help?

**Comment by gitoso** [comment]
Enabling raw mouse input does not help. Adding SDL_VIDEO_X11_DGAMOUSE=0 %command% to Portal 2's launch options does not help either. I am currently using libinput.
