### ISSUE TITLE
Look at local split screen coop

### ISSUE THREAD

**Issue by Plagman** [ValveSoftware/portal2#3]
The Coop menu has a prompt 'press X on controller 2 for local coop'. Does that work on Windows? Look at bringing it up on Linux if it does.

**Comment by marekjedrzejewski** [comment]
If it's not working the text simply shouldn't be there. If it's not working on both Linux and Windows that's even worse.

**Comment by stevethepocket** [comment]
Was splitscreen a recent addition on the PC version? I don't recall it having been there before.

**Comment by tvannahl** [comment]
It seems that this issue has been wiped out by accident?!

I can reproduce this Bug on an Arch Linux with:
- Kernel 3.13
- Xorg 1.15.0
- Gnome-Shell 3.10
- Nvidia Driver 334.21
- xboxdrv 0.8.5
  (started with `/usr/bin/xboxdrv --detach-kernel-driver --mimic-xpad`)

Steam Big Picture seems to work without any flaws (thanks to `--mimic-xpad`)
but I can't start the split screen coop in "Portal 2 (Beta) [Beta]" by pressing
the X-button nor by pressing any other button.

Navigating with the the wireless xbox controller is possible as well as playing
single-player. It is possible that the online multiplayer works as well, but
was not tested.

**Comment by PVince81** [comment]
I have a very specific config in which it works:
1) Controller 1: Xbox 360 gamepad
2) Controller 2: Non-Xbox gamepad, remapped buttons using xboxdrv (evdev device with `--mimic-xpad`).

Regardless of the order of the `/dev/input/js*` devices, the Xbox 360 joystick always appears as the first controller, and the other one appears as second controller.

So on that screen I am able to start coop mode by hitting X on the second controller. Then it is possible to play coop with the two controllers. (or player 1 can use the keyboard + mouse instead)

Edit: typos

**Comment by ebardie** [comment]
Ubuntu trusty.
xboxdrv 0.8.5 driving two Microsoft Xbox360 wireless controllers via:

   `sudo xboxdrv  --type xbox360 --mimic-xpad-wireless --dbus disabled --wid 0 --controller-slot 0`
   `sudo xboxdrv  --type xbox360 --mimic-xpad-wireless --dbus disabled --wid 1 --controller-slot 1`

and various other CLA combinations. Seems to work fine according stdout.

Installed Portal2 a few days back, working fine except for inability to start split screen mode. Nada.

Is there any progress on this bug?

**Comment by piedar** [comment]
I would like to play splitscreen co-op with Player 1 on KB/mouse and Player 2 on PS3 controller, but that entire mode is unplayable thanks to this bug.

**Comment by GiantSox** [comment]
Is this going to be fixed? When I use my 360 controller it always sets it as player 1.
