### ISSUE TITLE
Poor shadow quality compared to Windows build

### ISSUE THREAD

**Issue by Vash63** [ValveSoftware/portal2#30]
Noticed while testing it that the shadow filtering seems to be much lower quality than the Direct3D build on Windows. I have included a screenshot comparing the same area with maxed out settings in both builds. Both are 4xAA / 16xAF with everything else maxed out.

Windows:
![p2win](https://f.cloud.github.com/assets/3086017/2266861/fce908c4-9ea5-11e3-89b0-1d32fb60222e.jpg)
Linux:
![p2lin](https://f.cloud.github.com/assets/3086017/2266862/fce9c908-9ea5-11e3-918c-bed269c3a3eb.jpg)

I'm on the latest Nvidia driver, detailed specs:

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2d
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  5700 Mhz
    12 logical processors
    6 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.5-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11500000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2014-02-05

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 780 Ti/PCIe/SSE2

    Driver Version:  4.4.0 NVIDIA 331.38
    OpenGL Version: 4.4
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 59 Hz
    VendorID:  0x10de
    DeviceID:  0x100a
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 3760 x 1920
    Primary Display Size: 23.50" x 13.23"  (26.97" diag)
                                            59.7cm x 33.6cm  (68.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 3072 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: AV200

Memory:
    RAM:  15997 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  111420 Mb
    Largest Free Hard Disk Block:  41040 Mb

Installed software:

Recent Failure Reports:
```

**Comment by her001** [comment]
I have had the same experience from playing on wine vs playing native.

**Comment by jacobmischka** [comment]
Confirming that it happens to me as well.

**Comment by elad661** [comment]
Same problem here with mesa radeonsi on Fedora Rawhide.

**Comment by stevethepocket** [comment]
Didn't this game used to have a shadow quality setting in the options menu? Maybe it's defaulting to a lower quality and not giving you the option to change it.

**Comment by jacobmischka** [comment]
There is a setting, and it looks like it does in the OP's second image even when set to its highest value. I haven't tried lowering it, but I assume it looks the same?

**Comment by mariodonofrio** [comment]
We'll be enabling the higher cost/quality shadow filtering in the next update. The current build had a more optimal/lower quality solution (the same one as Mac), which isn't tied to any other video settings (it was tied to support for shader model 2/2b vs shader model 3 - the newer build will support shader model 3). We'll keep an eye on any knock-on issues.

**Comment by davidw-valve** [comment]
This is fixed in the latest update.
