### ISSUE TITLE
Game freezes randomly (Arch Linux, don't ask for version, it's rolling release.)

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/portal2#300]
*Everything is latest version*

Playing Portal 2, after about ten minutes the game freezes, no Source Engine signature sound loop, nothing. I can walk around blindly but the only way to fix it is to switch windows and come back to it. When I do that I can the see the changes I've made (walking around blindly). Then it happens again every ~2 minutes.

**Comment by kisak-valve** [comment]
Hello @sirtomato999, please copy your system information from steam (```Steam``` -> ```Help``` -> ```System Information```) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by ghost** [comment]
`Steam` menu has no help option
