### ISSUE TITLE
X360 controller on SteamOS has no dead zone, uncontrollable

### ISSUE THREAD

**Issue by littlegamer87** [ValveSoftware/portal2#302]
#### Your system information

* Steam client version (build number or date): 
* Distribution (e.g. Ubuntu): SteamOS 2.151 beta
* Opted into Steam client beta?: No
* Have you checked for system updates?: Yes

#### Please describe your issue in as much detail as possible:
After applying the latest patches for SteamOS and Portal 2 and giving the game another go, I noticed a significant change in how the game responds to the Xbox 360 controller.

The left analog stick appears to have no dead zone. The controller is a little worn and the analog stick is nearly impossible to center precisely. Game is suddenly very hard/impossible to control with a lot of unintended movement. There is no option in the controller configuration to do something about this.

The right analog stick suddenly is ridiculously fast, and swings the camera around on the lightest touch. This can be tweaked a little in the controller configuration, but the default setting is clearly way off.

I am guessing that these issues have been introduced somewhere this year. This game used to work flawlessly with an X360 controller. No issues with the buttons or with other games.

#### Steps for reproducing this issue:

1. Apply all latest patches and play the game with an X360 controller

**Comment by Plagman** [comment]
Hi,

Is it a wired or wireless 360 controller? Is Xbox controller configuration support enabled or disabled in controller options?

**Comment by littlegamer87** [comment]
Hi Pierre-Loup, the wireless one. 360 controller support is enabled globally (a lot of games cannot be controlled if this is disabled) and opening the portal 2 controller options brings up the overlay with a 360 layout. 

Portal 2 follows global preference for controller support. I tried forcing that to other options which causes the controller not to respond, or only the analog stick not to respond. It did not result in a playable game.

**Comment by austinp-valve** [comment]
If you reset to the current official configuration for Xbox this should be resolved. LMK if you still have issues.

**Comment by kisak-valve** [comment]
Closing per the last comment.
