### ISSUE TITLE
Game does not remeber resolution settings

### ISSUE THREAD

**Issue by nroach44** [ValveSoftware/portal2#31]
Like #2 

The game doesn't remember Resolution and fullscreen settings.
On my machine, it defaults to Fullscreen 1366x768. I manually set it to Windowed (Bordered) 1280x720, and restart the game, it is back in maximum/default resolution.

Debian Jessie amd64, Linux 3.13.3, Intel i3-3210m, using integrated GFX.

**Comment by nroach44** [comment]
Using the "launch options" to set the resolution as follows,

```
-window -w 1280 -h 720
```

works fine though.

**Comment by Tynach** [comment]
For me, it keeps the resolution setting, but doesn't keep the fullscreen setting.

I prefer it at 1152x864 in a window, but it then goes to 1152x864 fullscreen. The fullscreen doesn't change the actual resolution; it just uses a lower resolution buffer or something for displaying graphics... So the mouse and steam interface look the correct resolution but the game does not.

If I set it to use my native resolution and fullscreen, it changes and keeps the changes accordingly - but it won't save the fullscreen setting.

**Comment by davidw-valve** [comment]
This is fixed in today's update.
