### ISSUE TITLE
Repeating Cave Johnson Line in Community Test Chambers

### ISSUE THREAD

**Issue by tochgl** [ValveSoftware/portal2#327]
Whenever I start a community map, it always plays the Cave Johnson line that I think is supposed to play the first time you ever play a community test chamber, even though I have played more than one community test chamber. It also only displays the animal king takeover image on the screens around the elevator. I will leave a picture example of this below.
Update: It seems this only occurs in the quick play mode, when I started up a queued map, it worked as usual.
I don't use Linux, I use Windows 10, My graphics card is a Nvidia RTX 2060 Super, and is a founder's edition, with driver 451.67. 
![Screenshot (2)](https://user-images.githubusercontent.com/40646750/93792990-3788c380-fc04-11ea-8649-1fea06dbe771.png)

**Comment by FrozenDragon0** [comment]
This problem was fixed with Portal 2's latest update.

**Comment by kisak-valve** [comment]
Closing per "- Fixed Cave Johnson's lines not progressing when playing queued workshop levels." in the [2021-02-18](https://store.steampowered.com/oldnews/81067) Portal 2 update.
