### ISSUE TITLE
Portal 2 crashes on create chambers 

### ISSUE THREAD

**Issue by RazorLaser26** [ValveSoftware/portal2#328]
Hello this usually doesn’t happen and it is fine I have a lot of custom levels made by me anyway, this does happen sometimes, like every few months or so and it chose to happen today, what happens is I click on create chambers from within the main menu from the community chambers section and it crashes the game, I tried earlier validating the files, I even deleted lots of my puzzles (.p2c files) and a lot more but it didn’t change anything, I had the idea to fully reinstall Portal 2 to see if that works but it is annoying having to do all that again, but that is the only other solution I have thought of, also I have all my .p2c files on my computer still anyway backed up. When I saw it started crashing when I clicked create chambers once again I wasn’t very happy. Once it has happened now it probably won’t happen again probably. Is there an easier way to fix that actually fixes it for real instead of reinstalling it fully. Thanks.

**Comment by landswellsong** [comment]
Will #331 help?

**Comment by RazorLaser26** [comment]
Thanks for replying. This was put here in October. It is fine now, all working fine. Thanks. I worked out how to fix this myself a while ago. It is all working now. Thanks anyway.

**Comment by kisak-valve** [comment]
Was it the same issue or something else?

**Comment by RazorLaser26** [comment]
It is a similar issue. Not all the same though. Thanks anyway.

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
