### ISSUE TITLE
Console font is extremely tiny

### ISSUE THREAD

**Issue by jacobmischka** [ValveSoftware/portal2#33]
While the actual text for the game itself is fine, any console or engine-related text is very small, bordering on unreadable. To my knowledge none of my other Source games on Linux exhibit this problem. 
![2014-02-26_00001](https://f.cloud.github.com/assets/3939997/2267141/6db75968-9eae-11e3-8a88-c50a5590b7c9.jpg)

Edit: I didn't realize GitHub puts images inline like this, instead of simply linking to them, but here's an example of Portal 1 with much more readable font. 

![2014-02-26_00001](https://f.cloud.github.com/assets/3939997/2267150/d2af9c0e-9eae-11e3-8953-6ee08c497e0f.jpg)

**Comment by BKPepe** [comment]
Yes! I have same problem.

On wine, I have exactly this problem with DotA 2, CS:GO's consoles, but i don't think its related.

**Comment by timjp87** [comment]
Same problem here. I thought that was because of my 1440p monitor.

**Comment by dimgel** [comment]
+1. Gentoo / amd64.

**Comment by ivoanjo** [comment]
I have this issue with P2, no problems on DotA 2.

**Comment by cartman-2000** [comment]
same problem here as well.

**Comment by stevethepocket** [comment]
This bug is present in all Source games on Linux, I believe. I think it's because they're trying to use one of the built-in open source fonts instead of Verdana and it happens to be underscaled. It affects server browsers too. There's a report for it somewhere over in the Source 1 hub, if anyone can find it. (I could swear there used to be a way to search bug reports, but I can't find it anymore either.)

**Comment by jacobmischka** [comment]
Like I said, this isn't a problem for me on any other Source game than Portal 2. Here's Left 4 Dead 2 (which I believe is closest to Portal 2 in terms of the engine) and you can see it's perfectly fine on my machine.

![2014-03-01_00001](https://f.cloud.github.com/assets/3939997/2303260/66c6f498-a1af-11e3-9ec7-d4856e98f008.jpg)

**Comment by Half-Shot** [comment]
Seems to be an issue with any drawn font apart from ingame/menu stuff. cl_showfps also gives a very very small font.

**Comment by jacobmischka** [comment]
Yeah, you can see cl_showfps running in my original screenshot (hardly).

**Comment by davidw-valve** [comment]
The console font has been made larger in the latest update.

**Comment by Brli** [comment]
can you try to come up with a solution that can be defined by users instead of updating a "larger" font...

'cause it is totally not large enough for me.

**Comment by AdrGeorgescu** [comment]
I have the same problem on windows 10. 4k tv resolution and 300% (recommended) font scale. It's not really a linux only problem. It would be nice to have an option (a config file or something) to manually change the font size.

**Comment by joridiculous** [comment]
2024 and this is still a problem. (console) Text is completely unreadable being stupidly tiny.
ups, didn't notice this was Portal2 Console Port. Anyway im on Win11.
