### ISSUE TITLE
-vulkan switch requires GLIBCXX_3.4.26

### ISSUE THREAD

**Issue by dsalt** [ValveSoftware/portal2#336]
Setting the launch command to `%command% -vulkan` then trying to launch the game causes it to exit quickly, No window appears.

Setting the launch command to `xterm` then running `./portal2.sh -game portal2 -steam -vulkan` causes the following output:

```
 failed to dlopen /home/user/.steam/Steam/steamapps/common/Portal 2/bin/shaderapivk.so error=/usr/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/user/.steam/Steam/steamapps/common/Portal 2/bin/libdxvk_d3d9.so)
```

The game binary consequently segfaults.

**The relevant package is libstdc++6 8.3.0-6 from Devuan beowulf (equivalent to Debian buster).** Clearly, shaderapivk.so has been compiled against a newer libstdc++6 (Ubuntu?).

**Comment by TTimo** [comment]
It's likely the `portal2.sh` script is not, or incompletely setting up for the steam runtime environment, try to wrap the command in `~/.steam/steam/ubuntu12_32/steam-runtime/run.sh` first:

`~/.steam/steam/ubuntu12_32/steam-runtime/run.sh ./portal2.sh -game portal2 -steam -vulkan`

**Comment by dsalt** [comment]
No change. The same error is reported.

**Comment by TTimo** [comment]
Thanks. We think the next Portal2 update may address this.

**Comment by dsalt** [comment]
Working now after yesterday's update.

**Comment by andrebadaia** [comment]
It's not working here. 

~/.steam/steam/ubuntu12_32/steam-runtime/run.sh ./portal2.sh -game portal2 -steam -vulkan

failed to dlopen /home/badaia/.steam/steam/steamapps/common/Portal 2/bin/shaderapivk.so error=/home/badaia/.steam/steam/steamapps/common/Portal 2/bin/libdxvk_d3d9.so: undefined symbol: SDL_Vulkan_GetInstanceExtensions
 failed to dlopen /home/badaia/.steam/steam/steamapps/common/Portal 2/bin/shaderapivk.so error=/home/badaia/.steam/steam/steamapps/common/Portal 2/bin/libdxvk_d3d9.so: undefined symbol: SDL_Vulkan_GetInstanceExtensions

 failed to dlopen shaderapivk.so error=/home/badaia/.steam/steam/steamapps/common/Portal 2/bin/libdxvk_d3d9.so: undefined symbol: SDL_Vulkan_GetInstanceExtensions
 failed to dlopen shaderapivk.so error=/home/badaia/.steam/steam/steamapps/common/Portal 2/bin/libdxvk_d3d9.so: undefined symbol: SDL_Vulkan_GetInstanceExtensions

/home/badaia/.steam/steam/steamapps/common/Portal 2/portal2.sh, linha 51: 30214 Falha de segmentação  (imagem do núcleo gravada) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"

--------------------------------------------------------------------------------------------------
PC Specs:
Linux Mint Ulyssa - Mate
Kernel 5.10.19-xanmod1
Filesystem: BTRFS
CPU: Ryzen 7 1700 
GPU: NVIDIA GTX 1070 (Driver 460.39)
32 GB RAM

**Comment by kisak-valve** [comment]
Hello @andrebadaia, your issue is unrelated to the issue reported here. Please open a new issue report.

**Comment by andrebadaia** [comment]
> Hello @andrebadaia, your issue is unrelated to the issue reported here. Please open a new issue report.

Yes, it's true. I'm sorry.
