### ISSUE TITLE
Cannot view any keybindings

### ISSUE THREAD

**Issue by kiroma** [ValveSoftware/portal2#339]
You can still reassign keys but it's not possible to view what is already bound.
![image](https://user-images.githubusercontent.com/5281819/108773505-be005300-755e-11eb-9ef5-2d8135158c7c.png)

This also extends to in-game prompts that display the keys to press. I've reassigned the jump key to R to demonstrate:
![Screenshot_20210222_224131](https://user-images.githubusercontent.com/5281819/108773890-467ef380-755f-11eb-9ac3-299b2cb5d803.png)

**Comment by kisak-valve** [comment]
Hello @kiroma, please copy your system information from Steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by kiroma** [comment]
[System Info](https://gist.github.com/kiroma/4cfa51a5fd3a32153aa76ab8ed8f7bee)

**Comment by ghost** [comment]
This is related to my #321 issue. The exact thing happened for me.

**Comment by kiroma** [comment]
This is solved by installing the `glibc-locale-base-32bit` package
