### ISSUE TITLE
Strange text in the Community Test Chambers menu

### ISSUE THREAD

**Issue by eriktorbjorn** [ValveSoftware/portal2#340]
I haven't played Portal 2 in quite a while, so I don't know if this is an old bug or not, but after yesterday's update I noticed that when I open the Community Test Chambers menu there is garbled text. For instance, in the single player maps where I think it should say "My Queue", it instead says "$&()*,-+./0123...". Like this:

![p2-text](https://user-images.githubusercontent.com/601765/109621354-26d96380-7b3b-11eb-86c8-56857a953bb9.jpg)

I thought maybe this was what the "Fixed text corruption in challenge mode UI on Linux" was supposed to fix, but I took this screenshot after a full reinstall of the game, so maybe not?

I'm running the "unstable" version of Debian, so I know I'm not running an official supported Linux distribution. So if you can't reproduce the problem on your end, I fully understand that I'm on my own. I just thought I'd mention it anyway. Also, my graphics driver does not support Vulkan, so it's presumably using OpenGL. I don't know if that makes any difference.

**Comment by misyltoad** [comment]
This is fixed now.

**Comment by kisak-valve** [comment]
Thanks @Joshua-Ashton, closing as fixed per "- Fixed a bug with broken text on the PeTI map selection" in the [2021-03-02](https://steamcommunity.com/games/portal2/announcements/detail/3030330956962137598) Portal 2 update.

**Comment by eriktorbjorn** [comment]
Thanks, I can confirm that the latest update fixes the problem for me.
