### ISSUE TITLE
Portal 2 does not open with -vulkan switch

### ISSUE THREAD

**Issue by andrebadaia** [ValveSoftware/portal2#341]
I tried to open Portal 2 using the -vulkan switch, but it didn't work. I also tried to use Linux Steam Runtime, with no success. Finally, I tried to open it directly from console. Same result. Has anyone had the same problem?

Console feedback

~/.steam/steam/ubuntu12_32/steam-runtime/run.sh ./portal2.sh -game portal2 -steam -vulkan

failed to dlopen /home/badaia/.steam/steam/steamapps/common/Portal 2/bin/shaderapivk.so error=/home/badaia/.steam/steam/steamapps/common/Portal 2/bin/libdxvk_d3d9.so: undefined symbol: SDL_Vulkan_GetInstanceExtensions
failed to dlopen /home/badaia/.steam/steam/steamapps/common/Portal 2/bin/shaderapivk.so error=/home/badaia/.steam/steam/steamapps/common/Portal 2/bin/libdxvk_d3d9.so: undefined symbol: SDL_Vulkan_GetInstanceExtensions

failed to dlopen shaderapivk.so error=/home/badaia/.steam/steam/steamapps/common/Portal 2/bin/libdxvk_d3d9.so: undefined symbol: SDL_Vulkan_GetInstanceExtensions
failed to dlopen shaderapivk.so error=/home/badaia/.steam/steam/steamapps/common/Portal 2/bin/libdxvk_d3d9.so: undefined symbol: SDL_Vulkan_GetInstanceExtensions

/home/badaia/.steam/steam/steamapps/common/Portal 2/portal2.sh, linha 51: 30214 Falha de segmentação (imagem do núcleo gravada) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"

PC Specs:
Linux Mint Ulyssa - Mate
Kernel 5.10.19-xanmod1
Filesystem: BTRFS
CPU: Ryzen 7 1700
GPU: NVIDIA GTX 1070 (Driver 460.39)
32 GB RAM

**Comment by misyltoad** [comment]
Hello! It looks like when you updated the game, the old libsdl2.so was not removed from your Portal2/bin folder.

Would you be able to go to Portal 2/bin and delete libsdl2.so? Thanks!

**Comment by andrebadaia** [comment]
> Hello! It looks like when you updated the game, the old libsdl2.so was not removed from your Portal2/bin folder.
> 
> Would you be able to go to Portal 2/bin and delete libsdl2.so? Thanks!

It works!!! Thanks a lot!

![image](https://user-images.githubusercontent.com/42654336/109709888-c61e4b00-7b7b-11eb-9d36-fb7d7fafb04b.png)

**Comment by kisak-valve** [comment]
Glad to hear you got it working @andrebadaia. It looks like `bin/libSDL2-2.0.so.0` is no longer bundled with the game, so future installs will not be affected.

**Comment by andrebadaia** [comment]
> Glad to hear you got it working @andrebadaia. It looks like `bin/libSDL2-2.0.so.0` is no longer bundled with the game, so future installs will not be affected.

That's right! I tried to install a new SDL2.0 via PPA (version 2.0.12), without success... 

It seems like a good way to make ports using vulkan via dxvk... I'll check the performance!
