### ISSUE TITLE
Portal 2 Authoring Tools Model Viewer NOT WORKING

### ISSUE THREAD

**Issue by N0TaD0G** [ValveSoftware/portal2#344]
![picture](https://user-images.githubusercontent.com/80046889/109971233-4963ac00-7cf6-11eb-8b45-50938e8b2f18.PNG)

BUG:
Since the newest update (2021.March.02) the Portal 2 Authoring tools Model Viewer won't start.

Additional context: not linux specific, it seem this problem only occur on Windows 10.
I tried to fixing it by doing the verify game cache, but it did nothing.
Also i does not give any error message, it just not loading in, but Hammer and the Faceposer works just fine.

**Comment by KrisCatboy** [comment]
The model viewer works fine for me, which is strange. Maybe the issue is OS/hardware specific? I'm running Windows 7.

**Comment by N0TaD0G** [comment]
That is maybe the case... im on Win 10.

**Comment by darvil82** [comment]
I'm also experiencing this issue in Windows 10.

**Comment by misyltoad** [comment]
This should be fixed in the next update.

**Comment by N0TaD0G** [comment]
Cool ... looks like its working again, great job guys! :D
