### ISSUE TITLE
demo playback fails to find map in workshop folder

### ISSUE THREAD

**Issue by Mitia514** [ValveSoftware/portal2#350]
Portal 2 
The file recording goes well the recording file is large. But during playback the game freezes in the game menu.It happened after the last update of the game(Portal 2).This is what the console writes -
] demoui
Playing demo from kalerab3.dem.
CModelLoader::Map_IsValid: No such map 'maps/1614936779.bsp'
map load failed: 1614936779 not found or invalid
Unknown command "demopauseafterinit"

Any dem recordings and even those just recorded cannot be played
:steamsad:
Each update of the game breaks something (last time the list of signed cards was broken, now the excerpt is not recorded in the demo file.)

**Comment by misyltoad** [comment]
This is already fixed in the `limited_beta` branch.

**Comment by Mitia514** [comment]
Ok, but when will it go to release? Or should I always be on beta now?

**Comment by misyltoad** [comment]
This should be fixed now.

**Comment by Mitia514** [comment]
Yes, the developers have fixed it, I am very glad

**Comment by kisak-valve** [comment]
Closing per the last couple comments.
