### ISSUE TITLE
"limited_beta" branch does not run on Linux

### ISSUE THREAD

**Issue by enveeed** [ValveSoftware/portal2#351]
The `limited_beta` branch which seems to contain changes that are required for certain workshop items (https://steamcommunity.com/sharedfiles/filedetails/?id=2478362247) to function correctly does not start at all while the `public` branch does.

Launching the game from the command line results in the following:
```
# ~/.steam/steam/ubuntu12_32/steam-runtime/run.sh ./portal2.sh -game portal2 -steam
/media/hdd/steam/steamapps/common/Portal 2/portal2_linux: error while loading shared libraries: libtcmalloc_minimal.so.4: wrong ELF class: ELFCLASS64
```

On the public branch the same command starts the game successfully.

Is there anything I'm doing wrong?

**Comment by misyltoad** [comment]
It will be fixed when it is promoted to public.

**Comment by misyltoad** [comment]
This branch no longer exists so it can be closed.

**Comment by kisak-valve** [comment]
Closing per the last comment.
