### ISSUE TITLE
Portal 2 turrets having issues upon map loads

### ISSUE THREAD

**Issue by anexistantperson** [ValveSoftware/portal2#354]
**Portal 2, Newest version as of 5/19/21**

In single player, some turrets just fall over on map start. Happened to me.

In co-op, some turrets are gone completely. Happened to me on mp_coop_turret_ball. I haven't tested every map, but people have said it exists throughout the whole coop campaign. I believe they're falling off of the pillar before the player can see them, but they might not be spawning completely.

To reproduce:
Play a map with turrets in both single player and co-op.

System information:
Windows 10
Nvidia GTX 1650 super
Intel i3-8100

System information does not seem relevant as it happens across all(?) players.

**Comment by misyltoad** [comment]
This is already fixed in the upcoming update.

**Comment by misyltoad** [comment]
Should be fixed now!

**Comment by anexistantperson** [comment]
Seems to work fine now, thanks!
