### ISSUE TITLE
Black Screen after Setting Anti-Aliasing Options

### ISSUE THREAD

**Issue by porkloin** [ValveSoftware/portal2#36]
Reboot doesn't help. Can you point me in the direction of any relevant files where I can reset the anti-aliasing value to none manually?

**Comment by porkloin** [comment]
Fixed it manually - video config file located at ~/.local/share/Steam/SteamApps/common/Portal \2/update/cfg/video.txt

Reset value of  "setting.mat_antialias" to "0"

**Comment by timjp87** [comment]
Could you attach your "System Information" from Help -> System Information? This doesn't happen on my system.

**Comment by jacobmischka** [comment]
Antialiasing worked properly for me at max setting (8xMSAA I think?)

**Comment by dscharrer** [comment]
@rybateman If you use the AMD Catalyst drivers, disable all the 3D setting overrides in amdcccle. Particularly, try setting AA to "Use application settings".

**Comment by porkloin** [comment]
@dscharrer I'm using Nvidia, but disabling overrides fixed it. Forgot I'd set them to override program settings - d'oh!
