### ISSUE TITLE
Emancipation Grill player direction change

### ISSUE THREAD

**Issue by KuriKai** [ValveSoftware/portal2#37]
When walking though an Emancipation Grill the player direction changes about 10% to the right of the direction the player was walking (using right mouse button as move forward)
http://steamcommunity.com/id/kurikai/screenshots#scrollTop=0 for example

**Comment by timjp87** [comment]
Can't confirm this here. I aim for the elevator, let go of the mouse and walk forward. Nothing strange happens.

**Comment by KuriKai** [comment]
video capture of the problem
http://youtu.be/K-RVcBc0NLc

**Comment by dscharrer** [comment]
Looks like a duplicate of #16, or at least some comments there mention the same problem

**Comment by TheDude7053** [comment]
I can confirm this, Using Mouse and Keyboard going through emancipation grill, player turns 180 degrees.

**Comment by Arbitrary007** [comment]
This should now be fixed. I used to have the issue and no longer at resolutions that caused it.

Also, looks to be a duplicate of #16, which is closed.

**Comment by davidw-valve** [comment]
duplicate and should be fixed, so closing this out.
