### ISSUE TITLE
High contrast textures

### ISSUE THREAD

**Issue by chardinson** [ValveSoftware/portal2#372]
Portal 2 shows high contrast textures, when adjusting the texture quality between medium and low this is more pronounced, with and without cache preloading, this only happens when using OpenGL, while with Vulkan (launch parameter -vulkan) it doesn't happen.

**Computer**

    • OS: Fedora Workstation 35
    • Laptop: ASUS X553MA
    • CPU: Intel(R) Celeron(R) CPU N2830 @ 2.16GHz
    • GPU: Intel® HD Graphics (BYT)
    • Steam: Flatpak

**Images**

**- High**
![Shader Detail: High](https://user-images.githubusercontent.com/36754778/154604992-8736e2e5-fe47-41b4-992a-c5f40f756f73.png)

**- Medium**
![Shader Detail: Medium](https://user-images.githubusercontent.com/36754778/154604852-60edf01e-5725-4026-a8b2-494d06ab7840.png)

**- Medium Vulkan**
![Shader Detail: Medium Vulkan](https://user-images.githubusercontent.com/36754778/154604973-98410ef5-9363-4ae9-bbcb-05642b63aa4e.png)

**Comment by munoida** [comment]
Have you tried running it with the RPMFusion client instead of the Flatpak client? Flatpak client has some issues that the .DEB and RPMFusion client doesnt. For example, Left 4 Dead 2 mods that change anything visual do not work.

**Comment by kisak-valve** [comment]
It might be worthwhile to also mention this issue to your video driver vendor.

**Comment by chardinson** [comment]
I tested with Ubuntu 20.04 .deb, Fedora 37 .rpm and Flatpak, as @Munoida said "the version Flatpak has problems that the other mentioned versions don't", so yes, it only happens in the Flatpak version.

Close the issue and I will report it in the Steam Flatpak repository.
