### ISSUE TITLE
Failed to create D3D device error while using -vulkan in the prameters in the game

### ISSUE THREAD

**Issue by TheCoreOnly1** [ValveSoftware/portal2#373]
I had to update my driver and of course and it doesn't work and I used -vulkan and I suddenly changed the resolution to full screen and suddenly, now i just wanted to use portal 2 with bad shaders, thats terribile

For linux it has no issue by using vulkan in fullscreen mode.

![Capture](https://user-images.githubusercontent.com/100382990/155607899-0866aa73-4db8-4f90-a2c1-873e8025f431.PNG)
.

Specs:
CPU: AMD Ryzen 5 3500
Graphics: AMD RX 550
Hard Drive: WD 256 GB SSD and 2TB External TOSHIBA Drive
OS: Windows 10 Home
RAM: 8 GB

**Comment by kisak-valve** [comment]
Hello @TheCoreOnly1, this issue is already being tracked at #342. Closing as a duplicate.

**Comment by TheCoreOnly1** [comment]
> Hello @TheCoreOnly1, this issue is already being tracked at #342. Closing as a duplicate.

Understood
