### ISSUE TITLE
Mouse aiming is broken on wayland

### ISSUE THREAD

**Issue by ChaoticPumpkin** [ValveSoftware/portal2#376]
OS: Fedora 36
Desktop: GNOME (Wayland)

When playing Portal 2 on fedora, it appears that the mouse cursor does not get reset to the center of the screen, so when you move the mouse to the edge of the screen, the camera won't move any further. This problem does not exist when using Gnome on Xorg.

**Comment by misyltoad** [comment]
This ism't a game bug. Looka like whatever compositor you are using does not support viewporter and relative mouse.
