### ISSUE TITLE
Problem run portal 2 on OpenSUSE

### ISSUE THREAD

**Issue by Manazius** [ValveSoftware/portal2#39]
Hi all! Thank you for creating Portal 2 a native version for Linux !
That's only a problem when running on opensuse:
manazius@linux-4ibw:~/data/SteamLibrary/SteamApps/common/Portal 2> sh ./portal2.sh
./portal2.sh: line 2: $'\r': команда не найдена
./portal2.sh: line 8: $'\r': команда не найдена
./portal2.sh: line 10: $'\r': команда не найдена
./portal2.sh: line 16: syntax error near unexpected token `elif'
'/portal2.sh: line 16:`elif [ "$UNAME" == "Linux" ]; then
how to fix? Thanks!

**Comment by Manazius** [comment]
Sorry. I forgot to write: Команда не найдена = command not found

**Comment by Shished** [comment]
Set this as launch option in steam

LANG=C %command% 2> out.txt and launch game from steam

After that post out.txt.

Maybe you need to save portal2.sh with UTF-8 encoding and/or make it executable.

**Comment by UFeindschiff** [comment]
What shell are you using? (I don't know whether this script says what shell to use or not. I'm at another PC right now) Also, have you tried to launch it from the Steam client directly. Some games just fail to launch when not launched directly from Steam

**Comment by timjp87** [comment]
Did you opt into the beta for the game? Right click the game -> properties -> betas -> select "beta" from the dropdown and let it download 60 MB if you haven't done that. It won't start otherwise.

Also try launching it from the client rather than terminal. If you want to use the terminal 
"steam steam://rungameid/620" would be better.

**Comment by Manazius** [comment]
> Maybe you need to save portal2.sh with UTF-8 encoding 
> Yes, it helped!
> Next error:
> manazius@linux-4ibw:~/data/SteamLibrary/SteamApps/common/Portal 2> sh ./portal2.sh
> ./portal2.sh: line 40: /home/manazius/data/SteamLibrary/SteamApps/common/Portal 2/: This catalog

**Comment by Manazius** [comment]
> Did you opt into the beta for the game? Right click the game -> properties -> betas -> select "beta" from the dropdown and let it download 60 MB if you haven't done that. It won't start otherwise.
> Thanks! Work! But for some reason in English, although in settings Set Russian

**Comment by dscharrer** [comment]
> But for some reason in English, although in settings Set Russian

Have a look at #8

Is your Steam language set to English by chance?

**Comment by ZeXx86** [comment]
Please close this issue while it is duplicate.

**Comment by ZeXx86** [comment]
Language support issue was also reported.
