### ISSUE TITLE
Crash with -vulkan on Debian 11 (Mesa 20.3.5): "No adapters found", segfault

### ISSUE THREAD

**Issue by smcv** [ValveSoftware/portal2#397]
## To reproduce

* Debian 11 (current stable release, released 2021)
* AMD GPU (VEGA10, Radeon RX Vega 56/64 according to `lspci`)
* GNOME 3.38 in Wayland mode, if that matters (but Portal 2 is using X11 via Xwayland)
* Mesa 20.3.5 (the version included in Debian 11)
* Steam beta 2023-02-10 (1675997500)
* Portal 2 launch options: `-vulkan`
* Can be using Steam Linux Runtime container (soldier beta 0.20230123.89) or not, the result is the same either way

## Expected result

It runs, possibly with degraded functionality (this is a 2014 game so running it on a 2021 OS seems reasonable)

## Actual result

```
warn:  Skipping Vulkan 1.2 adapter: AMD RADV VEGA10 (ACO)
warn:  Skipping Vulkan 1.0 adapter: llvmpipe (LLVM 11.0.1, 256 bits)
warn:  DXVK: No adapters found. Please check your device filter settings and Vulkan setup.
```

and, later, a segmentation fault (presumably trying to use a NULL Vulkan device).

Is `portal2.sh -game portal2 -steam -vulkan` expected to fail in this way on older host OSs?

## Workaround

Don't use `-vulkan` so that OpenGL will be used, or use a host OS with newer Mesa available, like Debian 12 alpha, Ubuntu 22.04, or a rolling release like Arch.

**Comment by smcv** [comment]
DXVK is correct to say that neither of my available Vulkan devices (GPU or software rendering) advertises Vulkan 1.3 support with this driver:

```
      "graphics-details" : {
        "x11/vulkan" : {
          "messages" : [
            "WARNING: lavapipe is not a conformant vulkan implementation, testing use only."
          ],
          "renderer" : "AMD RADV VEGA10 (ACO)",
          "version" : "Mesa 20.3.5 (ACO)",
          "devices" : [
            {
              "name" : "AMD RADV VEGA10 (ACO)",
              "api-version" : "1.2.145",
              "vulkan-driver-id" : 3,
              "driver-name" : "radv",
              "driver-version" : "Mesa 20.3.5 (ACO)",
              "vendor-id" : "0x1002",
              "device-id" : "0x687f",
              "type" : "discrete-gpu"
            },
            {
              "name" : "llvmpipe (LLVM 11.0.1, 256 bits)",
              "api-version" : "1.0.2",
              "driver-version" : "0x1 (0.0.1?)",
              "vendor-id" : "0x10005",
              "device-id" : "0",
              "type" : "cpu",
              "issues" : [
                "software-rendering"
              ]
            }
          ]
        },
```

[Portal 2 log](https://github.com/ValveSoftware/portal2/files/10742597/portal2-vulkan-debian11.log)

[Help -> System Information](https://github.com/ValveSoftware/portal2/files/10742632/srsi-debian11.txt)

**Comment by kisak-valve** [comment]
Hello @smcv, the [2022-11-18](https://steamcommunity.com/games/portal2/announcements/detail/3488629295080243622) Portal 2 update bumped DXVK to 2.0. [DXVK 2.0](https://github.com/doitsujin/dxvk/releases/tag/v2.0) does require mesa 22.0 or NVIDIA 510.47.03 or newer to run, so this is the expected outcome.

**Comment by smcv** [comment]
Thanks, I'll exclude Portal 2 from future testing of Steam Runtime updates on older OSs.
