### ISSUE TITLE
Cannot choose which monitor to run on in multi-monitor setup

### ISSUE THREAD

**Issue by RecceDG** [ValveSoftware/portal2#40]
Game starts on leftmost monitor in a multi-monitor setup, which on my setup happens to be a portrait mode monitor.

Video Options do not have Fullscreen Monitor (0) or Fullscreen Monitor (1) like Source games do.

Setting game to run in a wind with borders, dragging the window to the right monitor, then setting Fullscreen works, but the resolution is wrong and does not respond to settings.

Ubuntu 12.04 LTS. Catalyst drivers (latest as of this post)

**Comment by Tele42** [comment]
The game launches on the primary monitor here, which is the right monitor of the pair in my setup.

**Comment by RecceDG** [comment]
All Steam games launch on the leftmost monitor on my system. This MAY be something I can change at the Ubuntu/GNOME level (simply reversing cables doesn't work) - I've since found references online to setting a GNOME "primary" monitor that explains a lot of annoying behaviour outside of Steam.

But that's a workaround. All  Steam games should all have a configuration item somewhere that says "open on THIS monitor in THIS mode at THIS resolution".

Source based games (Portal, TF2) DO have this feature. I was able to tell TF2 to open on the right monitor, fullscreen, at 1020P. It works and it is persistant. Portal 2 cannot do this; or if it can, it doesn't do it via the interface.

**Comment by JWWAMBA** [comment]
The best solution is to go to your monitor settings and set the one you want to your primary monitor.  Steam seems to default to the left monitor always, and changing your system settings should fix that and tell steam where to display.

**Comment by Plagman** [comment]
In Portal 2 the way to pick which monitor to run on is to switch the game to windowed, move the window to the desired monitor, then to switch back to fullscreen. This setting is not yet remembered, see this other issue:

https://github.com/ValveSoftware/portal2/issues/1

**Comment by stuartallen** [comment]
> The best solution is to go to your monitor settings and set the one you want to your primary monitor. Steam seems to default to the left monitor always, and changing your system settings should fix that and tell steam where to display.

I'm sure the alternative is better but F11 doesn't seem to work and I can't seem to window the tab. I don't know why this is so horrendously downvoted, when it's Saturday night and you just want the dang game to go on the big screen this is the easiest way
