### ISSUE TITLE
Portal 2 not behaving correctly on kwin wayland with multiple monitors

### ISSUE THREAD

**Issue by zeparu** [ValveSoftware/portal2#407]
![image](https://github.com/ValveSoftware/portal2/assets/21054889/9ac469b8-ff42-4dab-b52e-e47fedc80969)

it assumes that its just one 1440p ultrawide screen instead and will only run inbetween both screens

on current version of arch linux

**Comment by zeparu** [comment]
playing through proton fixes it, this affects the native version specifically

**Comment by dugo3number2** [comment]
Same issue but on X11

**Comment by DavidDGTNT** [comment]
Possible duplicate of #392

**Comment by zeparu** [comment]
yes it is, couldnt find a previous report through the search function

their solution of -vulkan also works
