### ISSUE TITLE
Crashes to Desktop on play, Window with Borders mode

### ISSUE THREAD

**Issue by RecceDG** [ValveSoftware/portal2#41]
Set video to Window With Borders. Set resolution to 1440 x 880 (I Ithink) Play, Single Player, Chapter 1. Various load screens then crash to desktop.

Ubuntu 12.04 LTS. Latest Catalyst drivers. Radeon 7880.

**Comment by RecceDG** [comment]
This turns out to be CTD in _all_ graphics modes. Load screens then CTD.

Where are the logs stored?

**Comment by dscharrer** [comment]
Duplicate of #4

> Where are the logs stored?

Close Steam, then run `steam` from a terminal and start the game. Log output should appear in the terminal.

**Comment by RecceDG** [comment]
Starting steam from console worked.

Trying "The Fall" played the animation of the fall fine, then segfaulted and dumped core after the opening sequence played.

**Comment by dscharrer** [comment]
If this is just the same as #4 you should close this issue and add your information there.

**Comment by davidw-valve** [comment]
Closing as duplicate of #4
