### ISSUE TITLE
puzzlemaker does not build on Linux (but does with Proton)

### ISSUE THREAD

**Issue by homchom** [ValveSoftware/portal2#412]
Attempting to rebuild a chamber in the puzzlemaker opens the screen with the three loading bars, but no progress is ever made. I am playing on Steam Deck, and forcing the use of Proton 8 (to run the Windows executable) causes it to work normally.

I will note that I am not certain whether the cause of the issue lies with Portal 2 itself or with the newest version of Steam Linux Runtime.

Reproduction Steps:
1. Make sure that the "Force the use of a specific Steam Play compatibility tool" checkbox is not checked in the game's properties before launch.
2. Start the game and open the puzzlemaker.
3. Attempt to rebuild the level and observe.

System Information: SteamOS 3.4 (Steam Deck, in Gaming Mode)

**Comment by kisak-valve** [comment]
Hello @homchom, this issue is already being tracked at #403. Closing as a duplicate.

**Comment by homchom** [comment]
ah, I saw that but didn't piece together their sameness. thanks!

**Comment by imization** [comment]
funny seeing you here
