### ISSUE TITLE
Community Test Chambers loads the same maps played before

### ISSUE THREAD

**Issue by kylemonti** [ValveSoftware/portal2#415]
When going for community test chambers, selecting 'Top Rated' now loads the same maps previously played in the same sequence (ie. loads map A, then upon completing, loads map B, then C.... upon closing and reopening the game (or restarting PC), selecting Top Rated will load the same map A, B, C and so on in that order).

Issue repeated itself on both Windows and Linux, with the exact same maps and sequence on both OS's and was first experienced near the end of October 2023. 

No particular method used to reproduce the issue. It just happens by itself by opening the game and playing normally. Playing other game modes and then going back to Top Rated does not change the behaviour.

**Comment by kisak-valve** [comment]
Hello @kylemonti, this issue is already being tracked at #384. Closing as a duplicate.
