### ISSUE TITLE
Cant build custom test chambers on linux

### ISSUE THREAD

**Issue by stigl-cc** [ValveSoftware/portal2#416]
So, i tried to make my custom test chamber, but when i try to build it, its infinetly stuck at 0% (i have tried waiting like 1 hour, still 0%), previously worked just fine
![2023-10-22_13-56](https://github.com/ValveSoftware/portal2/assets/96888050/d9e94f08-5b9c-47a2-96ac-73e3307c034f)

**Comment by kisak-valve** [comment]
Hello @StiglCZ, this issue is already being tracked at #403. Closing as a duplicate.
