### ISSUE TITLE
[Enhancement] Ability to filter-out or auto-skip already played chambers

### ISSUE THREAD

**Issue by GitHubington** [ValveSoftware/portal2#422]
Under

- Community Test Chambers
- Play Single Player Chambers
- Quick Play

It would be helpful and save bandwidth too, to filter-out or auto-skip already played chambers, specifically the chambers that the player has already rated.

**Comment by kisak-valve** [comment]
Hello @GitHubington, this is the same issue as #384. Closing as a duplicate.
