### ISSUE TITLE
Ping in co-op not visible

### ISSUE THREAD

**Issue by Wintermute79** [ValveSoftware/portal2#424]
Neither me nor my friend can see each others ping tool markers in co-op mode. We are playing on the same local area network, sitting next to each other. It was working the last time, we played on 13 January  2024.

**Comment by Zaechus** [comment]
Had the same issue until the [recent update](https://store.steampowered.com/news/app/620/view/4044863966193655321?l=english). Should be working now.

**Comment by Wintermute79** [comment]
Fixed with [last update](https://store.steampowered.com/news/app/620/view/4044863966193655321?l=english). Thank you!
