### ISSUE TITLE
sp_a5_credits no longer boots to the menu at the end of the credits

### ISSUE THREAD

**Issue by vrad-exe** [ValveSoftware/portal2#432]
When playing the credits from the New Game menu (not after completing finale4 normally), it now traps the player in a black box when the credits finish instead of booting to the menu as it did previously. The console indicates that Portal 2 now seemingly enforces the `FCVAR_CLIENTCMD_CAN_EXECUTE` convar flag since a recent update, but the credits weren't changed to call `ClientCmd_Unrestricted` when disconnecting the player so it now fails.

**Comment by kisak-valve** [comment]
Hello @vrad-exe, this issue is already being tracked at #428. Since this issue report adds some more details, I've transferred it to https://github.com/ValveSoftware/portal2/issues/428#issuecomment-2102554133.

Closing in favor of the older issue report.
