### ISSUE TITLE
segfaults after mesa 24, intel a770

### ISSUE THREAD

**Issue by zlice** [ValveSoftware/portal2#439]
Started segfaulting around update to mesa 24. Was in the middle of playing and got to the level with 3 lazer beam target lights but only 2 lazers and it started crashing. Have not been able to play since. My current attempt starts on a catwalk and just crashes moments after starting to play.

Not sure if Intel driver related. Trying to run with native linux `steam linux runtime 1.0 (scout)` and `intel_tbimr=false %command% > /tmp/crash.log 2>&1`

`Sun Jun 30 16:55:07 2024 GMT: file ''/tmp/dumps/crash_20240630125506_14.dmp'', upload yes: ''CrashID=bp-928200fc-0e98-4b0f-94de-e524a2240630''`

[crash.txt](https://github.com/user-attachments/files/16045471/crash.txt)

[minidump.zip](https://github.com/user-attachments/files/16045478/minidump.zip)

#### sys info

- mesa 24.1.1
- kernel 6.9.6
- void linux

**Comment by kisak-valve** [comment]
Hello @zlice, the attached minidump is a SIGSEGV in libgallium_dri.so. This should be part of your video driver.

Please also report this issue to your video driver vendor.

**Comment by zlice** [comment]
Thanks for the confirmation. I'll poke around more and make an issue there.
