### ISSUE TITLE
Game does not open on Fedora 20 (Windows line endings in portal2.sh)

### ISSUE THREAD

**Issue by juliusikkala** [ValveSoftware/portal2#45]
```
ERROR: ld.so: object '/home/julius/SDA/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
/bin/sh: /home/julius/SDA/Steam/SteamApps/common/Portal 2/portal2.sh: /bin/bash^M: bad interpreter: No such file or directory
```

I have set up Steam to use my secondary hard drive, hence 'SDA'. When I press 'Play', the user frame is green for a split second and then goes back to blue. The game does not open. portal2.sh seems to have Windows-style line endings (CR+LF), hence this error.  I ran the file through dos2unix and now I get another error, which I will post another bug report for.

**Comment by dscharrer** [comment]
Did you opt into the beta?

**Comment by juliusikkala** [comment]
Oops, no I did not. I will report back soon after I have downloaded it. 
EDIT: It works now.
