### ISSUE TITLE
Voices do not work

### ISSUE THREAD

**Issue by 0x726f62** [ValveSoftware/portal2#5]
At the beginning of the first mission. Announcer and Wheatley cannot be heard.
Other sounds work just fine. Only subs can be seen.

Got alsa + pulseaudio.

```
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x1e
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  2794 Mhz
    4 logical processors
    4 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.12.9-2-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11500000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2014-02-05

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 470/PCIe/SSE2

    Driver Version:  4.4.0 NVIDIA 331.38
    OpenGL Version: 4.4
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x10de
    DeviceID:  0x6cd
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1080
    Primary Display Size: 23.54" x 13.23"  (26.97" diag)
                                            59.8cm x 33.6cm  (68.5cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 1280 MB
    Supported MSAA Modes:  2x 4x 8x 16x 

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  3949 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  899266 Mb
    Largest Free Hard Disk Block:  74038 Mb

Installed software:

Recent Failure Reports:
```

**Comment by xpander69** [comment]
same here.. except i can hear Wheatly at some point... but announcer not

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x2
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  4200 Mhz
    8 logical processors
    8 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.4-1-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11500000
    X Window Manager:  Xfwm4
    Steam Runtime Version:  steam-runtime-release_2014-02-05

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 660 Ti/PCIe/SSE2

```
Driver Version:  4.4.0 NVIDIA 331.38
OpenGL Version: 4.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x1183
Number of Monitors:  3
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 3200 x 1080
Primary Display Size: 20.51" x 11.54"  (23.50" diag)
                                        52.1cm x 29.3cm  (59.7cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 2048 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC889

Memory:
    RAM:  24098 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  1877664 Mb
    Largest Free Hard Disk Block:  291099 Mb

Installed software:

Recent Failure Reports:

**Comment by bootkiller** [comment]
I have the same problem. Some voices still play, Wheatley speech while room is moving, but other don't.

Console reports it couldn't find/open mixer.

**Comment by woox2k** [comment]
Same here, no Announcer or Wheatley

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x25
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  4199 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Arch Linux" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.12.9-2-ARCH
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11500000
    X Window Manager:  Marco
    Steam Runtime Version:  steam-runtime-release_2014-02-05

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 660/PCIe/SSE2

```
Driver Version:  4.4.0 NVIDIA 331.38
OpenGL Version: 4.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x10de
DeviceID:  0x11c0
Number of Monitors:  2
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1200
Desktop Resolution: 3840 x 1200
Primary Display Size: 20.39" x 12.76"  (24.02" diag)
                                        51.8cm x 32.4cm  (61.0cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 2048 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC888, Sound Blaster Audigy

Memory:
    RAM:  9997 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  1877664 Mb
    Largest Free Hard Disk Block:  880413 Mb

Installed software:

Recent Failure Reports:

**Comment by ChristianHersevoort** [comment]
Same issue here, but some audio dialogs do work for a while after switching to the settings menu. (Not sure if coincidence)

System info: http://pastebin.com/PN5GJsve (I am using alsa without pulseaudio)

Looking at other reports; Arch Linux related?

**Comment by timjp87** [comment]
@Kwastie No. #7 was reported by an openSUSE user.
I use Arch Linux aswell with Gnome 3.10 with pulseaudio and have the same issue.

http://pastebin.com/Gx0cnXdq - System Information

**Comment by fiws** [comment]
@Kwastie I've tested it on Ubuntu. Same issue.

**Comment by last-partizan** [comment]
![portal-error](https://f.cloud.github.com/assets/301015/2263259/9e30ecee-9e63-11e3-9da4-f7f70e2e2c17.png)
probably i found what causing this error. "S_StartSound(): Failed to load sound 'vo/announcer/openingexecrcise01.wav"

**Comment by flugsio** [comment]
Same issue on Archlinux 64-bit, got Alsa WITHOUT pulseaudio.  (and also 32-bit on my laptop with alsa + pulseaudio). http://pastebin.com/qEN6Qszn

Error in ingameconsole:
   VAC secure mode is activated.
Redownloading all lightmaps
[Sound] S_StartSound(): Failed to load sound 'vo/announcer/openingexercise01.wav'. Can't create mixer.
Host_WriteConfiguration: Wrote cfg/config.cfg
Flugsio [Archlinux] unpaused the game
Flugsio [Archlinux] unpaused the game
[Sound] S_StartSound(): Failed to load sound 'vo/announcer/openingexercise02.wav'. Can't create mixer.
Host_WriteConfiguration: Wrote cfg/config.cfg
Flugsio [Archlinux] unpaused the game
[Sound] S_StartSound(): Failed to load sound 'vo/announcer/openingexercise03.wav'. Can't create mixer.
Error: Operator stop_entry, unknown sound operator attribute input_start
Host_WriteConfiguration: Wrote cfg/config.cfg
Flugsio [Archlinux] unpaused the game
[Sound] S_StartSound(): Failed to load sound 'vo/announcer/openingexercise04.wav'. Can't create mixer.

**Comment by flugsio** [comment]
Can it  be related to https://github.com/ValveSoftware/portal2/issues/8 ? missing locale config?

**Comment by xpander69** [comment]
don't think so.. i see all here have English and en_US.UTF-8

**Comment by last-partizan** [comment]
> Can it be related to #8 ? missing locale config?

Probably not, i set English in game properties, nothing changed.

**Comment by flugsio** [comment]
Was peeking in the config files,  and the console seems to output lowercase in the errors. ~/.local/share/Steam/SteamApps/common/Portal 2/portal2/scripts/game_sounds_announcer_auto_generated.txt

console vs config:
vo/announcer/openingexercise01.wav'
vo/announcer/OpeningExercise01.wav

(tried to lowercase it in the config file without success)

**Comment by edmondo** [comment]
Same issue here. 

Are the wav files packed somewhere? If I search for wav files I just find 2 of them:

edmondo@balrog ~/.local/share/Steam/SteamApps/common/Portal 2 $ find . -name "*.wav"
./portal2/sound/br/events/br_crossing_bell_dop.r.wav
./portal2/sound/br/events/br_crossing_bell_dop.l.wav

**Comment by maxpoulin64** [comment]
@edmondo: Most Valve games pack their files in the *.vpk files in /SteamApps/common/Portal 2/portal2/. They are self-contained filesystems, and probably case insensitive so the case difference noted by @flugsio is probably harmless otherwise it would not work on Windows either.

The "Can't create mixer." really sounds like it's the issue. Unable to create sound output for the voices?

**Comment by edmondo** [comment]
@maxpoulin64: Ok, thanks for the explanation. Makes sense. (But Windows is not case sensitive and this could explain why it's no problem there.)

**Comment by rkfg** [comment]
Same on Debian Jessie amd64 with ALSA. I doubt it's because of mixer or sound system, more like the required file not found for whatever reason. The cause and effect here are reversed — can't find the file hence can't create mixer.

**Comment by flugsio** [comment]
@maxpoulin64 yes, you're correct. I changed the filename randomly and got another error "File is missing from disk/repository". So the configs are not case sensitive.

I have also tried changing "channel" and "mixer" without success. It's funny to read all the comments in these files :D

**Comment by powdermilkman** [comment]
Same issue, accidently started a new issue.

The following is from my post:

None of the voice tracks are playing. Wheatley's voice worked for the beginning sequence after he picks the room up until the wall breaks and you enter the testing facility. No voices before that part or after have played.

When Wheatley is talking I can hear his head movements.

I have tried to change my audio settings both in pulseaudio and in-game with no results.

My systems audio device is:
Audio device: Advanced Micro Devices, Inc. [AMD/ATI] SBx00 Azalia (Intel HDA) (rev 40)

and I am using pulseaudio on Elementary OS Luna.

**Comment by flugsio** [comment]
Got this high up in the console.
"Unable to load voice codec 'vaudio_speex'. Voice disabled."

edit: even if installing with "sudo pacman -S speex", i get the same error message. Don't know what to install really.

**Comment by timjp87** [comment]
@flugsio I have speex installed on Arch Linux. Still the same problem as @powdermilkman "Wheatley's voice worked for the beginning sequence after he picks the room up until the wall breaks and you enter the testing facility."

EDIT: I don't have the lib32- installed. Just did that. Trying it out now.

**Comment by Bronsky** [comment]
I also noticed that the only moment the voice worked, there were not captions at all. The rest of the time, the captions worked.

**Comment by edmondo** [comment]
@flugsio I've also have speex installed on Gentoo Linux and have the same issue.

@Bronsky Tried with and without captions. No difference. Issue persist.

**Comment by timjp87** [comment]
lib32-speex doesn't fix it.

**Comment by machinaeZER0** [comment]
The strange thing here seems to be that a couple of people have heard at least one voice? @powdermilkman heard wheatley speak briefly, and in issue #7 @Shished heard cave johnson speak as well (he posted a video of it in that issue report). I haven't heard anyone speak, though I have been opening random acts now in the hope that I'll hear someone...

Is anyone who has heard any dialogue at all getting anything different in the console than the rest of us?

**Comment by bootkiller** [comment]
@dancemasterglenn I was able to reproduce it successfully:

1- Start new game from first chapter.
2- There should be no voices with the errors:

```
[Sound] S_StartSound(): Failed to load sound 'vo/announcer/openingexercise01.wav'. Can't create mixer.
boot unpaused the game
[Sound] S_StartSound(): Failed to load sound 'vo/announcer/openingexercise02.wav'. Can't create mixer.
[Sound] S_StartSound(): Failed to load sound 'vo/announcer/openingexercise03.wav'. Can't create mixer.
[Sound] S_StartSound(): Failed to load sound 'vo/announcer/openingexercise04.wav'. Can't create mixer.
[Sound] S_StartSound(): Failed to load sound 'vo/announcer/openingexercise05.wav'. Can't create mixer.
[Sound] S_StartSound(): Failed to load sound 'vo/announcer/openingexercise06.wav'. Can't create mixer.
boot unpaused the game
[Sound] S_StartSound(): Failed to load sound 'vo/announcer/openingexercise07.wav'. Can't create mixer.
boot unpaused the game
[Sound] S_StartSound(): Failed to load sound 'vo/announcer/openingexercise08.wav'. Can't create mixer.
[Sound] S_StartSound(): Failed to load sound 'vo/announcer/openingcourtesy01.wav'. Can't create mixer.
[Sound] S_StartSound(): Failed to load sound 'vo/announcer/openingcourtesy01.wav'. Can't create mixer.
[Sound] S_StartSound(): Failed to load sound 'vo/wheatley/openinghello01.wav'. Can't create mixer.
[Sound] S_StartSound(): Failed to load sound 'vo/wheatley/openinghello12.wav'. Can't create mixer.
[Sound] S_StartSound(): Failed to load sound 'vo/announcer/openingcourtesy01.wav'. Can't create mixer.
[Sound] S_StartSound(): Failed to load sound 'vo/wheatley/intro_ride01.wav'. Can't create mixer.
[Sound] S_StartSound(): Failed to load sound 'vo/wheatley/intro_ride02.wav'. Can't create mixer.
[Sound] S_StartSound(): Failed to load sound 'vo/wheatley/intro_ride03.wav'. Can't create mixer.
[Sound] S_StartSound(): Failed to load sound 'vo/announcer/evacuationmisc01.wav'. Can't create mixer.
[Sound] S_StartSound(): Failed to load sound 'vo/wheatley/intro_ride04.wav'. Can't create mixer.
boot unpaused the game
[Sound] S_StartSound(): Failed to load sound 'vo/wheatley/openingprepare04.wav'. Can't create mixer.
[Sound] S_StartSound(): Failed to load sound 'vo/wheatley/openingyouallright01.wav'. Can't create mixer.
[Sound] S_StartSound(): Failed to load sound 'vo/wheatley/openingbraindamage01.wav'. Can't create mixer.
[Sound] S_StartSound(): Failed to load sound 'vo/wheatley/intro_ride07.wav'. Can't create mixer.
boot unpaused the game
[Sound] S_StartSound(): Failed to load sound 'vo/wheatley/intro_ride08.wav'. Can't create mixer.
[Sound] S_StartSound(): Failed to load sound 'vo/wheatley/openingbraindamage05.wav'. Can't create mixer.
```

3- You will hear Wheatley speech normally right after the "say apple" part with no errors, you can also hear the annoucer.
4- After the chamber crashes through the wall voices should stop again.

**Comment by flugsio** [comment]
@dancemasterglenn I think we all hear the same wheatley voices, i hear the same voices as @powdermilkman and @blackout24. In contrast to @Bronsky though, i DO get captions when wheatly picks up the room.

I can't hear from the beginning up and including vo/wheatley/OpeningBrainDamage05.wav, then i can hear wheatly, and i guess(no messages) it's OpeningBrainDamageAppleNag01-05, OpeningCloseEnough01, OpeningDoorOpened01 and OpeningGoodbye01.wav. But then i get an error again with OpeningGoodbye02.wav.

I don't see any difference in the config for OpeningGoodbye01 and 02.

**Comment by machinaeZER0** [comment]
Hmm... I guess I wasn't playing far enough into the act. Still strange that part of it will indeed play.

**Comment by flugsio** [comment]
I'm suspecting they use something else to play the sounds when the room is moving. I changed stuff in this file:
~/.local/share/Steam/SteamApps/common/Portal 2/portal2/scripts/game_sounds_sphere03_auto_generated.txt

I changed these filenames to test, but only get error for the 02-file.
vo/wheatley/OpeningGoodbye01.wav
vo/wheatley/OpeningGoodbye02.wav

I'm clueless :P

**Comment by rkfg** [comment]
I've unpacked the entire content with vpk_linux32 from Portal 1 and I can confirm that the sound is actually there and the filename is in lower case (openingexercise01.wav). The file is playable with mplayer and here's an interesting detail: the background music (sound/music/mainmenu/portal2_background01.wav) is in pcm_s16le format. It's played back fine as everyone can hear. But the file sound/vo/announcer/openingexercise01.wav is in mp3 actually (Stream #0:0: Audio: mp3, 44100 Hz, mono, s16p, 80 kb/s). So the issue is probably that the game can't playback mp3-encoded audio.

**Comment by timjp87** [comment]
Developer commentary works. You'd think that's basically the same function call and format.

**Comment by rkfg** [comment]
@blackout24 my theory is backed by that. Commentaries are also encoded as PCM (sound/commentary/com-accents.wav ⇒ Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, mono, s16, 705 kb/s)

**Comment by flugsio** [comment]
@rkfg nice, strange that they got wav extension then. Can you check any of these that i think is working:
OpeningBrainDamageAppleNag01.wav to 05
OpeningCloseEnough01.wav
OpeningDoorOpened01.wav
OpeningGoodbye01.wav

**Comment by rkfg** [comment]
@flugsio They could do it for compatibility. Also, it's not actually WAV container, it doesn't have the RIFF-header and file command says "MPEG ADTS, layer III, v1,  80 kbps, 44.1 kHz, Monaural" while for UI sounds and BGM it says "RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, stereo 44100 Hz". Unfortunately (for the theory) files you mentioned are also in mp3 and have no notable differences. I'm going to sleep for now, will test it all later.

**Comment by jbwyatt4** [comment]
Can confirm. Cannot hear announcer or Wheatly in first chapter, have not tested later chapters.

Ubuntu 13.10 x64. Default drivers and software. Mobile Intel graphics Ivy Bridge.

**Comment by ghost** [comment]
Same issue, Arch Linux 64bit.

**Comment by dos1** [comment]
Same issue here on Debian @ amd64. I'm using plain ALSA, without PulseAudio and I also can hear the dialogs during the part when Weatley moves the room, but not before or after that.

**Comment by davidw-valve** [comment]
Apologies for this issue. We hope to have an update available for it shortly.

**Comment by justinnichols** [comment]
Confirmed here as well.  I'm seeing the following in the Portal 2 console log when the opening announcer is supposed to start:

[Sound] S_StartSound(): Failed to load sound 'vo/announcer/openingexercise01.wav'. Can't create mixer.

Thanks for the beta!

**Comment by timjp87** [comment]
@davidw-valve We are Linux users. We love a good bug. No need to apologize. ;-) It's like an easteregg hunt for us.

**Comment by flugsio** [comment]
@davidw-valve as @blackout24 put it, we love a good bughunt :) Would be nice to hear the reason. Also, everything else seems to work flawlessly, thanks! <3

**Comment by lostogre** [comment]
Portal 2 runs great from the Steam Client, but I too have no sounds from Glados or Wheatly. I have looked all through my home directories and can find none of the files that you are referencing. I have tried running portal2 from the command line and haven't been successful. 

Here are the results of trying to run portal2.sh from the cli.

SDL video target is 'x11'
SDL video target is 'x11'

SDL failed to create GL compatibility profile (whichProfile=0!
SDL failed to create GL compatibility profile (whichProfile=0!

This system supports the OpenGL extension GL_EXT_framebuffer_object.
This system supports the OpenGL extension GL_EXT_framebuffer_blit.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample.
This system DOES NOT support the OpenGL extension GL_APPLE_fence.
This system supports the OpenGL extension GL_NV_fence.
This system supports the OpenGL extension GL_ARB_sync.
This system supports the OpenGL extension GL_EXT_draw_buffers2.
This system supports the OpenGL extension GL_EXT_bindable_uniform.
This system DOES NOT support the OpenGL extension GL_APPLE_flush_buffer_range.
This system supports the OpenGL extension GL_ARB_map_buffer_range.
This system supports the OpenGL extension GL_ARB_vertex_buffer_object.
This system supports the OpenGL extension GL_ARB_occlusion_query.
This system DOES NOT support the OpenGL extension GL_APPLE_texture_range.
This system DOES NOT support the OpenGL extension GL_APPLE_client_storage.
This system DOES NOT support the OpenGL extension GL_ARB_uniform_buffer.
This system supports the OpenGL extension GL_ARB_vertex_array_bgra.
This system supports the OpenGL extension GL_EXT_vertex_array_bgra.
This system supports the OpenGL extension GL_ARB_framebuffer_object.
This system DOES NOT support the OpenGL extension GL_GREMEDY_string_marker.
This system supports the OpenGL extension GL_ARB_debug_output.
This system supports the OpenGL extension GL_EXT_direct_state_access.
This system supports the OpenGL extension GL_NV_bindless_texture.
This system DOES NOT support the OpenGL extension GL_AMD_pinned_memory.
This system supports the OpenGL extension GL_EXT_framebuffer_multisample_blit_scaled.
This system supports the OpenGL extension GL_EXT_texture_sRGB_decode.
This system supports the OpenGL extension GL_NVX_gpu_memory_info.
This system DOES NOT support the OpenGL extension GL_ATI_meminfo.
This system supports the OpenGL extension GL_EXT_texture_compression_s3tc.
This system supports the OpenGL extension GL_EXT_texture_compression_dxt1.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt3.
This system DOES NOT support the OpenGL extension GL_ANGLE_texture_compression_dxt5.
This system supports the OpenGL extension GLX_EXT_swap_control_tear.
Setup file 'GameInfo.txt' doesn't exist in subdirectory 'hl2'.
Check your -game parameter or VCONFIG setting.
Setup file 'GameInfo.txt' doesn't exist in subdirectory 'hl2'.
Check your -game parameter or VCONFIG setting.

**Comment by davidw-valve** [comment]
An update has shipped and this bug has been resolved.

However, if you already downloaded Portal 2, there is one part of the update process which unfortunately cannot be completed automatically and you must do manually:
- navigate to the bin/ directory under your Portal 2 directory (e.g. ~/.local/share/Steam/SteamApps/common/Portal 2/bin
- rename libmiles.so to libMiles.so

New users will work without doing this, and if you prefer you can delete your local game content and then download Portal 2 again (if you don't mind downloading the entire game again).

Apologies for the inconvenience.

**Comment by ghost** [comment]
Works.

mv ~/.local/share/Steam/SteamApps/common/Portal\ 2/bin/libmiles.so ~/.local/share/Steam/SteamApps/common/Portal\ 2/bin/libMiles.so

**Comment by justinnichols** [comment]
Confirmed, worked perfectly.  Thanks @davidw-valve !

**Comment by Arbitrary007** [comment]
Had the same problem. Emphasis on HAD. Went here to report it and it looks like I'm late to the party. It works fine now.

**Comment by oliwarner** [comment]
My Steam lives in ~/Steam/ for some reason so the fix was:

```
mv ~/Steam/SteamApps/common/Portal\ 2/bin/lib{m,M}iles.so
```

**Comment by ghost** [comment]
Fix fixed the issue for me :D

**Comment by josefnpat** [comment]
This sounds like an issue with steam, as opposed to portal 2. Steam has a "Verify Integrity of Game Cache" button. Shouldn't that download the latest file list, and compare the submitted file list against the portal 2 file list, checking for case?

**Comment by rkfg** [comment]
Why are you reopening this issue when it's already fixed? It wasn't only the case in the filename, there was a patch of 20-30 Mb, too. Steam probably checks files case-insensitively like it does on Windows™, so if that's the case it could be reported to the Steam bugs section anyway.

**Comment by josefnpat** [comment]
@rkfg I did not mean to re-open the ticket, I only meant to continue the conversation.

I am not familiar with the protocol, but I would like to suggest that we should document the deeper issue at hand.

**Comment by rkfg** [comment]
@josefnpat Oh, sorry. I thought it was reopened looking at those green "Open" marks though they are references of other opened issues. We can rename a file and check the local cache and if Steam doesn't detect this as an inconsistency then it could be reported.

**Comment by dshadowwolf** [comment]
Seeing this issue in Fedora 22 with everything up to date.

**Comment by victor-oliveira1** [comment]
I know, i'm reviving a old post 
LOL
But this is the problem:

[victor@ASROCK bin]$ ldd libMiles.so 
	linux-gate.so.1 (0xf77b6000)
	libm.so.6 => /lib/libm.so.6 (0xf76bd000)
	libpthread.so.0 => /lib/libpthread.so.0 (0xf76a0000)
	libopenal.so.1 => **not found**
	libc.so.6 => /lib/libc.so.6 (0xf74c5000)
	/lib/ld-linux.so.2 (0x56631000)

The libMiles.so library can't find openal.
Just install openal (On fedora the package is: **openal-soft.i686**) and it runs fine.

**Comment by ghost** [comment]
sudo apt-get install libglu1-mesa:i386 libopenal1:i386 libssl1.0.0:i386
- solved the problem in my case (Kubuntu x64)

**Comment by MurderFromMars** [comment]
THIS IS STILL AN ISSUE IN 2025
