### ISSUE TITLE
To get the linux beta you must opt in to beta

### ISSUE THREAD

**Issue by mpnordland** [ValveSoftware/portal2#53]
The game title says beta, but it's not the correct beta until you go into the game preferences and opt in to the beta.

**Comment by timjp87** [comment]
Not a bug. That's what the Readme says.

https://github.com/ValveSoftware/portal2/blob/master/README.md

**Comment by Arbitrary007** [comment]
Had the same issue, but @blackout24 has a point. If you don't opt in to beta test, why would the beta work? It's probably something with Steam, not Portal 2. I would wager that it is designed to do that.

**Comment by davidw-valve** [comment]
I'm afraid that to run on Linux during the beta period you need to opt-in to the beta.
