### ISSUE TITLE
Unable do build a map with PETI

### ISSUE THREAD

**Issue by YPetremann** [ValveSoftware/portal2#56]
Each time I try to build a map with PETI, it says it has encountered a compile error and in the terminal :
[0226/150217:ERROR:nss_ocsp.cc(588)] No URLRequestContext for OCSP handler.

**Comment by dawwin** [comment]
I also had a problem when I tried to build a chamber. I noticed that libuuid1 (version for i386) was missing. I installed it and it's building now. 
I'm using Ubuntu 13.10 64bit.
I think steam should check if required (not standard) libraries are present and tell user to install it. Unexperienced users may not find what the reason of such problems is and assume that's some bug on linux (which is easy to solve but not obvious for everyone).

**Comment by kisak-valve** [comment]
Hello @YPetremann, @dawwin, are either of you still experiencing this issue on an up to date system?

**Comment by YPetremann** [comment]
Since that time I don't have portal 2 on a linux system anymore.

**Comment by kisak-valve** [comment]
Thanks for the feedback. This was most likely fixed while #335 was being looked at.
