### ISSUE TITLE
No sound in ubuntu 13.10 64bit

### ISSUE THREAD

**Issue by almejo** [ValveSoftware/portal2#60]
I have a fresh install of ubuntu 13.10 in 64 bit and other of ubuntu 32. In the 32 bit version all works well but in 64 bits I have no sound

This is my audio device listed in lspci

00:1b.0 Audio device: Intel Corporation 6 Series/C200 Series Chipset Family High Definition Audio Controller (rev 05)

I can attach any log as needed

**Comment by abt462** [comment]
Have you checked in ~/.local/share/Steam/SteamApps/common/Portal 2/bin that the audio lib is spelled libMiles.so and not libmiles.so ? If that's the case, rename it.

**Comment by davidw-valve** [comment]
I take it that you mean you get _no_ sound at all from the game? Do other Valve games have sound for you?

**Comment by almejo** [comment]
I did the fix to libMile.so...

I do not have sound in half life either.. i also tested bastion and Guacamelee and no sound... but other games have sound..

**Comment by LinuxPony** [comment]
Do you have pavucontrol installed? if not install it from the Ubuntu Software Center (should appear as PulseAudio Volume Control) or if you don't mind using the terminal use the command `sudo apt-get install pavucontrol`

Once installed launch it by searching pavucontrol or PulseAudio Volume Control in the Unity search bar or by locating it in your menu bar if you are not using Unity.

Check out the Playback tab while the game is running (you probably want to run the game in window mode during this) and see if the game is outputting sound, check the Output Devices tab as well. If you see sound being outputted but don't hear it then it probably is outputting to the wrong device, If you have a video card with HDMI output then it may be outputting the sound there, in the Configuration tab use the drop down list and try setting any HDMI controllers to off.

You may also be missing some packages, try installing:
`sudo apt-get install libpulse0:i386`
`sudo apt-get install ia32-libs`

and see if it has any effect.

**Comment by almejo** [comment]
only running pavucontrol fixed the problem!!.. Since it is a misconfiguration of my account I am closing this bug. Thanks to all!
