### ISSUE TITLE
Game fails to start

### ISSUE THREAD

**Issue by Videobeetle** [ValveSoftware/portal2#61]
Game fails to start. Output from the console:

Game update: AppID 620 "Portal 2 (Beta)", ProcID 3238, IP 0.0.0.0:0
ERROR: ld.so: object '/home/fws/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded: ignored.
CGameStreamThread: Added instance ID 3238 for appid 620
CGameStreamThread: Set render instance ID 3238 for appid 620
(steam:3139): LIBDBUSMENU-GLIB-WARNING **: Trying to remove a child that doesn't believe we're it's parent.
/bin/sh: 1: /home/fws/.local/share/Steam/SteamApps/common/Portal 2/portal2.sh: not found
CGameStreamThread: Added instance ID 3239 for appid 620
Game removed: AppID 620 "Portal 2 (Beta)", ProcID 3238 

Checked and confirmed that portal2.sh does exist and permissions are correct. Validated the game cache and it checks out.

**Comment by SleepyAkubi** [comment]
Opt into the beta. I swear if I see another issue like this.

**Comment by DmitryErshov** [comment]
opt-in to the beta
https://github.com/ValveSoftware/portal2/blob/master/README.md

**Comment by davidw-valve** [comment]
Please opt in to the beta and the game will start for you.
