### ISSUE TITLE
Portals visible through walls

### ISSUE THREAD

**Issue by xclaesse** [ValveSoftware/portal2#63]
I don't know if it is normal or not, since I didn't play the game on Window, but it looks buggy to me. See attached screenshot.

This is on ubuntu 14.04 (dev version) with intel chipset (Thinkpad X230).

![capture du 2014-02-26 11 54 24](https://f.cloud.github.com/assets/1379109/2273074/d0fc1d4e-9f0b-11e3-9492-0e49c146062a.png)

**Comment by dscharrer** [comment]
Looks normal to me. Note that you don't see the actual portal through walls, only an outline:
![](http://www.rarityguide.com/articles/content_images/1/portal2/portal2_testchamber02_5.jpg)

**Comment by SleepyAkubi** [comment]
Looks normal.

**Comment by ghost** [comment]
It is the normal behavior.

**Comment by davidw-valve** [comment]
This is a feature of Portal 2 -- makes it easier to keep track of where your portals are.

**Comment by rmbleeker** [comment]
If you really want to though, you can turn it off using the developer console by typing "portal_draw_ghosting 0". See http://forums.steampowered.com/forums/showthread.php?t=1849098
