### ISSUE TITLE
Coop partner in science crashes (Windows 7)

### ISSUE THREAD

**Issue by spjoe** [ValveSoftware/portal2#64]
I play on linux and do not crash, but my partner in science crashes every 5-10 minutes. The partner plays on Windows 7 and have not activate beta. I am not sure if this is an issue, because of the linux client. The same partner and I played about a half year ago (both on windows 7) without crashes. My partner and I did not change Hardware since.

**Comment by SleepyAkubi** [comment]
Try opting him into the beta. I have a hunch that that might be the issue.

**Comment by spjoe** [comment]
My partner opt into beta. Since that no crash occured. thanks :-)
