### ISSUE TITLE
Portal2 won't start with selinux on

### ISSUE THREAD

**Issue by elad661** [ValveSoftware/portal2#66]
When I try to start portal2 with SELinux on Enforcing mode, it crashes on startup.

I ran steam in the terminal and noticed this line 

`
OnFocusWindowChanged to window type: k_EWindowTypeNonSteamDesktop, 0
/home/elad/.local/share/Steam/SteamApps/common/Portal 2/portal2.sh: line 46: 25983 Segmentation fault      (core dumped) ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
`

I can't run it in a debugger to provide you with a backtrace, because when I run the game by moving to it's directory and executing `./portal2.sh` it says

`Setup file 'GameInfo.txt' doesn't exist in subdirectory 'hl2'.
Check your -game parameter or VCONFIG setting.
Setup file 'GameInfo.txt' doesn't exist in subdirectory 'hl2'.
Check your -game parameter or VCONFIG setting.
`

right after listing all my OpenGL capabilities, and exists normally without a crash.

Half Life 2 seems to work perfectly fine with selinux on enforcing, is there any reason Portal 2 wouldn't? Basically, selinux is set to deny execheap permission because it's a very dangerous one when it comes to security. Can Portal 2 run without execheap?

**Comment by dscharrer** [comment]
The SELinux issue is tracked in #50 

As for debugging, this should work:

```
GAME_DEBUGGER=gdb ./portal2.sh -game portal2
```

**Comment by elad661** [comment]
Seems like a duplicate, I'm closing this one then. Will provide backtrace in issue #50 shortly.
