### ISSUE TITLE
Uncommanded 90 degrees clockwise rotation while passing through emancipation grid at exit

### ISSUE THREAD

**Issue by ItsMeOnly** [ValveSoftware/portal2#68]
Basically a thing in description happens: when exiting the level as soon as I touch emancipation grid, suddenly I find myself standing in the middle turned right. That happens only once per level.

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x25
    CPU Stepping:  0x2
    CPU Type:  0x0
    Speed:  3197 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Linux 2.6 (32 bit)
    Kernel Name:  Linux
    Kernel Version:  2.6.34.14
    X Server Vendor:  The X.Org Foundation
    X Server Release:  10605000
    X Window Manager:  <Unknown>
    Steam Runtime Version:  steam-runtime-release_2014-02-05

Video Card:
    Driver:  NVIDIA Corporation GeForce GT 440/PCIe/SSE2

```
Driver Version:  4.4.0 NVIDIA 331.38
OpenGL Version: 4.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0xde0
Number of Monitors:  1
Number of Video Cards Not Detected
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.51" x 11.54"  (23.50" diag)
                                        52.1cm x 29.3cm  (59.7cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 1024 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: TriTech TR28602

Memory:
    RAM:  3921 Mb

Miscellaneous:
    UI Language:  English
    LANG:  C
    Microphone:  Not set
    Total Hard Disk Space Available:  225286 Mb
    Largest Free Hard Disk Block:  68233 Mb

Installed software:

Recent Failure Reports:

**Comment by dscharrer** [comment]
#16

**Comment by ItsMeOnly** [comment]
oops, sorry for duplicate
