### ISSUE TITLE
No voices in game

### ISSUE THREAD

**Issue by Shished** [ValveSoftware/portal2#7]
When game started all sound effects and music presents. But there is no voices, from GLaDOS, Announcer or Wheatley. But Cave Jonson's voice clearly audible.
I loaded old gamesaves, started new game but it still mute.

I recorded [video](https://docs.google.com/file/d/0BwW6c62eL84xdkRJVTF4N2VPYWM)  that shows probem.

My PC specs http://pastebin.com/pyHsNtgK

**Comment by fiws** [comment]
Same problem here.

**Comment by Half-Shot** [comment]
Already reported, see issue 5.

**Comment by 0x726f62** [comment]
duplicity #5

**Comment by machinaeZER0** [comment]
It may be a duplicate, but he did get one voice playing, which is one more than anyone else has heard...
