### ISSUE TITLE
Unable to launch game

### ISSUE THREAD

**Issue by eugeneyche** [ValveSoftware/portal2#70]
Here are the specs of my machine:
Computer: Lenovo T430 with Nvidia graphics
Distro: Arch Linux
Kernel: 3.13.5-1-ARCH
Window Manager: Awesome
Desktop Environment:
Shell: /usr/bin/zsh
CPU: Intel (R) Core(TM) i5-3360M CPU @ 2.80GHz

When I run it from a the install, I get this error:
ERROR: ld.so: object '/home/eugeneyche/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
/usr/bin/primusrun: /home/eugeneyche/.local/share/Steam/SteamApps/common/Portal 2/portal2.sh: /bin/bash^M: bad interpreter: No such file or directory

I figured out how to fix the /bin/bash^M problem by reformatting the sh file to unix. After that, when I run it with the following run configuration:

vblank_mode=0 primusrun %command%

I get the following error:

ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
pid 9885 != 9830, skipping destruction (fork without exec?)
ERROR: ld.so: object '/home/eugeneyche/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: default value of option vblank_mode overridden by environment.
/home/eugeneyche/.local/share/Steam/SteamApps/common/Portal 2/portal2.sh: line 40: /home/eugeneyche/.local/share/Steam/SteamApps/common/Portal 2/: Is a directory
pid 9887 != 9830, skipping destruction (fork without exec?)
CGameStreamThread: Added instance ID 9886 for appid 620
Game removed: AppID 620 "Portal 2 (Beta)", ProcID 9829

**Comment by davidw-valve** [comment]
Did you opt in to the beta? Right click on the game in Steam -> Properties -> Betas -> select "beta" from the dropdown.

**Comment by eugeneyche** [comment]
This fixed it. Thanks!
