### ISSUE TITLE
When exiting sealed levels though huge hatch on the ceiling, cage ropes are tangled.

### ISSUE THREAD

**Issue by dimgel** [ValveSoftware/portal2#76]
See screenshots:
When cage goes down: http://dimgel.ru/images/screenshots/portal2-bug-1.png (notice also incorrect rope shadows on the wall)
When cage goes up: http://dimgel.ru/images/screenshots/portal2-bug-2.png
Cage and top panel rotate in opposite directions.

**Comment by dimgel** [comment]
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  2401 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    "Gentoo Base System release 2.2" (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.10.25-gentoo
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11403000
    X Window Manager:  KWin
    Steam Runtime Version:  steam-runtime-release_2014-02-05

Video Card:
    Driver:  NVIDIA Corporation GeForce GT 650M/PCIe/SSE2

```
Driver Version:  4.4.0 NVIDIA 331.38
OpenGL Version: 4.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID Not Detected
DeviceID Not Detected
Number of Monitors:  2
Number of Video Cards Not Detected
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 15.00" x 8.43"  (17.17" diag)
                                        38.1cm x 21.4cm  (43.6cm diag)
Primary VRAM: 2048 MB
```

Sound card:
    Audio device: Intel PantherPoint HDMI

Memory:
    RAM:  15939 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  450041 Mb
    Largest Free Hard Disk Block:  139952 Mb

Installed software:

Recent Failure Reports:
    Tue Feb 25 21:40:47 2014 GMT: file ''/tmp/dumps/crash_20140226014040_29.dmp'', upload yes: ''CrashID=bp-208260de-b72f-413c-aff5-cbcd52140225''

**Comment by alebahn** [comment]
As I mentioned in the duplicate bug. I have this issue as well.
System information: https://gist.github.com/alebahn/9311707

**Comment by Arbitrary007** [comment]
I thought I saw this before. XD

**Comment by davidw-valve** [comment]
This should be fixed now.

**Comment by Arbitrary007** [comment]
Fix verified. Looks good.
