### ISSUE TITLE
Cannot set Paged Memory Pool higher than low

### ISSUE THREAD

**Issue by GlacialTurtle** [ValveSoftware/portal2#78]
Portal 2 refuses to set the paged memory pool setting above low. Set and apply it, back out of the menu and re-enter it immediately and it will be reset.

Processor is Pentium D 3.00 Ghz dual core

Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0xf
    CPU Model:  0x6
    CPU Stepping:  0x5
    CPU Type:  0x0
    Speed:  3000 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Unsupported
    SSE4a:  Unsupported
    SSE41:  Unsupported
    SSE42:  Unsupported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu Trusty Tahr (development branch) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-11-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11500000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2014-02-05

Video Card:
    Driver:  X.Org Gallium 0.4 on AMD CAICOS

```
Driver Version:  3.0 Mesa 10.1.0-rc1
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x1002
DeviceID:  0x6779
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1440 x 900
Desktop Resolution: 1440 x 900
Primary Display Size: 16.14" x 10.12"  (19.02" diag)
                                        41.0cm x 25.7cm  (48.3cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: ATI R6xx HDMI

Memory:
    RAM:  2505 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  367583 Mb
    Largest Free Hard Disk Block:  26341 Mb

**Comment by T2-Archimedes-Stench** [comment]
I can also confirm this bug. I am running the following system.
My CPU is the AMD FX-8350

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x2
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  4013 Mhz
    8 logical processors
    8 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 12.04.4 LTS (32 bit)
    Kernel Name:  Linux
    Kernel Version:  3.2.0-59-generic-pae
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11103000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2014-02-05

Video Card:
    Driver:  NVIDIA Corporation GeForce GTX 760/PCIe/SSE2

```
Driver Version:  4.4.0 NVIDIA 331.20
OpenGL Version: 4.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID:  0x10de
DeviceID:  0x1187
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 23.54" x 13.23"  (26.97" diag)
                                        59.8cm x 33.6cm  (68.5cm diag)
Primary Bus: PCI Express 16x
Primary VRAM: 2048 MB
Supported MSAA Modes:  2x 4x 8x 16x 
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  7978 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_GB.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  936885 Mb
    Largest Free Hard Disk Block:  376507 Mb

**Comment by spider623** [comment]
Same here, my specs
 My CPU is the AMD FX-8350
Vram is 1024 but not detected by steam
Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x2
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  4000 Mhz
    8 logical processors
    8 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu Trusty Tahr (development branch) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.13.0-12-lowlatency
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11500000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2014-02-05

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 7700 Series  

```
Driver Version:  4.3.12795 Compatibility Profile Context 13.35.1005
OpenGL Version: 4.3
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x683d
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1920 x 1200
Desktop Resolution: 1920 x 1200
Primary Display Size: 20,39" x 11,46"  (23,39" diag)
                                        51,8cm x 29,1cm  (59,4cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC892

Memory:
    RAM:  7940 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_US.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  460828 Mb
    Largest Free Hard Disk Block:  283159 Mb

Installed software:

Recent Failure Reports:

**Comment by cartman-2000** [comment]
Also same here, but I believe this has no effect in Linux if it did stick, paged pool is a windows thing, unless it effected video quality, like in the shadow quality discrepancy in #30 compared to windows. I'm not sure though as I never really messed around with the paged pool setting in the windows version when I had it installed.

**Comment by SleepyAkubi** [comment]
Its because Paged Pool Memory doesn't exist in Linux.

**Comment by davidw-valve** [comment]
This setting has no meaning on Linux. In the next update we will remove it from the menu.
