### ISSUE TITLE
Only English language supported

### ISSUE THREAD

**Issue by DissCent** [ValveSoftware/portal2#8]
I have set the language to German, but the game is English.

Let me know if you need any system information - but I don't think you will need them for this issue :)

**Comment by UFeindschiff** [comment]
I can confirm this issue. When setting the language to German the game still has English texts and no voice (other sounds work fine)

**Comment by last-partizan** [comment]
I can confirm. Probably this is becouse folders portal2_$languagename is empty.

**Comment by Arbitrary007** [comment]
I can imagine the folder is empty due to this being an early beta test in Linux. Probably going to be fleshed out later in testing.

**Comment by timjp87** [comment]
After renaming the libMiles.so on my existing installation, which fixes the audio dialogs in general, German language works on my end. New downloads should work out-of-the-box.

**Comment by DissCent** [comment]
Are you sure? I think libMiles.so is for audio, but also the menus were in English.
I can't check it myself today, so that's why I'm asking.

**Comment by last-partizan** [comment]
I switched language to Russian and waiting until download is complete. I'll report after few minutes.

**Comment by timjp87** [comment]
@WindohsCrasher I have my Steam client in English and set the game to "German" by right clicking it -> Properties -> Language and selecting "German" in the dropdown. It downloaded 600 MB of data. Main Menu is English but voices are German. The menu language might be bound to the client language setting? Will try this now.

EDIT: OK this issue was about the text anyway.

**Comment by last-partizan** [comment]
Russian language doesn't work, i see english text/subtitles. And don't hear any voices.

**Comment by DissCent** [comment]
@last-partizan Have you renamed the libmiles.so file to libMiles.so? It doesn't happen automatically on update unless you reinstall the whole game. If you did, then this issue becomes even more confusing :)

**Comment by last-partizan** [comment]
@WindohsCrasher oh, just renamed file and now i can hear voices, in Russian, but text/subtitles still English.

**Comment by timjp87** [comment]
I just booted into "that other OS" and opted into the [beta] for Portal 2. Text and audio is German when the Steam client and language pack is set to German. On Linux with German client and language pack the text is English but audio is German.

**Comment by Funigtor** [comment]
After adding "-language french" (without quotes) to Launch Options (Not sure if it's called like this in the English client) my game is in French.

I found this solution in Dota 2 bugtracker.

**Comment by timjp87** [comment]
@Funigtor  That works for me, too.

**Comment by DmitryErshov** [comment]
Confirmed.
Game and Steam language: Russian
Menu and subtitles: English
Voice: Russian

with "-language russian" in launch options menu and subtitles in Russian

**Comment by davidw-valve** [comment]
We will try to get this fixed soon. In the mean time you can use the -language option to workaround it.

**Comment by davidw-valve** [comment]
This has now been fixed. You can set the game's language from Steam.
