### ISSUE TITLE
Cannot change resolution

### ISSUE THREAD

**Issue by MichaelAquilina** [ValveSoftware/portal2#81]
Portal  is currently stuck at 1920x1080 for me and refuses to change. If I go in settings, select a different resolution and hit "apply", nothing happens. Restarting the game does not cause it to start in the resolution I specified either.

I am running Kubuntu 13.10 64bit with an Nvidia GT555M (Run over primus)

I would paste my system information here but it doesn't seem to be selectable from steam?

**Comment by almejo** [comment]
This is the same as #2

**Comment by MichaelAquilina** [comment]
Right, thanks for that! I see its actually been fixed with the latest update and I can confirm this.
