### ISSUE TITLE
Changing volume crashes the game

### ISSUE THREAD

**Issue by thinred** [ValveSoftware/portal2#82]
I have Debian Testing x64 and the game seems to work properly, but when I change volume during gameplay (using special keyboard keys), it immediately crashes the game. It may be due to my Gnome-Shell that shows an overlay with volume when I do this - maybe it messes up the game somehow.

EDIT: by "crash" I mean that the audio buffer repeats, and the screen does not change or respond
to any input. The process does not segfault or anything, though.

Please let me know if you need more info.

Thanks for porting Portal 2 anyway! I'm going to play it once again just for the sake of it. :)

**Comment by timjp87** [comment]
I'm running Gnome Shell aswell and have a keyboard with multimedia buttons which are mapped to the sound control. It does not crash my game. Instead when I press vol up/vol down once the screen briefly flashes black before the audio indicator overlay from Gnome Shell is shown. When I press the same volume button repeatedly or hold it the game minimizes. I can switch back into the game and continue without problems. When I press a volume key and wait a second before pressing it again the game does not minimize.

**Comment by davidw-valve** [comment]
Do you get a minidump of the crash that you can post here?

**Comment by thinred** [comment]
Hi, can you elaborate? I've just googled "minidump" and it is something Windows-related.

**Comment by ghost** [comment]
I also have this issue. But I have it for all games running in fullscreen, not just this game. Do you have Intel graphics?

I filed a bug in mesa some months ago: https://bugs.freedesktop.org/show_bug.cgi?id=76321

It's a graphics driver bug for Intel chips (most likely).

**Comment by thinred** [comment]
@alexhultman 
Hi there Alex! I read your bug request and I've tried with fullscreen glxgears and it hanged as you described and as happened to me with Portal. However, contrary to you, I've never had my Gnome-Shell crash - only the OpenGL app hangs.
To make things even funnier, after killing glxgears I can now start it and it works fine when I change volume. I cannot try with Portal now, because I don't have it installed currently, but I'll let you know asap I have it again.

In any case, it seems that this is the same bug.

**Comment by ghost** [comment]
Yeah but mine also sometimes just hangs. But since we both can reproduce this with glxgears, we can close this Portal bug. I'll link this bug report with the mesa report so we can get them more information to fix it in the driver.

Did you run Intel graphics? glxinfo | grep Intel

**Comment by thinred** [comment]
Yes, Intel here:

$ glxinfo | grep Intel
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile

Also:
$ grep 'Intel(R)' /var/log/Xorg.0.log
[  1421.430](II) intel: Driver for Intel(R) Integrated Graphics Chipsets:
[  1421.434](--) intel(0): Integrated Graphics Chipset: Intel(R) HD Graphics 4000

I close the bug then. Don't forget to link at Freedesktop bugtracker.

Cheers,
Tomasz

**Comment by shoe** [comment]
@alexhultman would you also be able to provide a link here to the mesa report?

**Comment by thinred** [comment]
Oh, isn't it https://bugs.freedesktop.org/show_bug.cgi?id=76321 ?

**Comment by ghost** [comment]
I have posted a link to this issue now
