### ISSUE TITLE
Accessing Portal 2 for Linux for PS3 owned copy

### ISSUE THREAD

**Issue by gadLinux** [ValveSoftware/portal2#83]
Hello, 

I see that you only grant access to Portal 2 Linux to the ones that brought the game through Steam. But I own a copy of the excellent game Portal 2 for PS3 and also love Linux so I will appreciate to opt-in for the Beta in this platform. 

Is this possible? I suppose that PS3 and PC copies are not too much different in data contents.

**Comment by Leiaz** [comment]
Portal 2 PS3 came with a code to redeem it on Steam. The instructions are on a paper in the box along with the code.

**Comment by Arbitrary007** [comment]
What Lelaz said. I received my PC copy of Portal 2 through my PS3 copy and it allows me to participate in the Linux beta.

**Comment by gadLinux** [comment]
Lelaz. I will see it. Never realized of the coupon. I will take a look, thank you for the advice. I hope I still can redeem it.
[Update: I got it!!! Thank you guys. I never realized about the code]
