### ISSUE TITLE
Walls etc not visible on IntelHD 4600 on Linux 3.11.10 x64

### ISSUE THREAD

**Issue by evilmav** [ValveSoftware/portal2#84]
Running OpenSUSE (KDE) 13.1 x64
Tried playing with settings but none seemed to change the appearance of the game (including brightness - no effect at all)
![portal2](https://f.cloud.github.com/assets/6803717/2281668/d7a2542a-9fa0-11e3-957d-5122f8c84238.png)

i5-4200m with interal GPU and 8GB memory (Thinkpad L540)

**Comment by Tele42** [comment]
@Maverickx89 you need the 32 bit s2tc package, (http://rpmfind.net/linux/RPM/opensuse/factory/i586/s2tc-20130202-1.1.i586.html maybe?) to get Intel graphics to render properly.

**Comment by evilmav** [comment]
I've installed s2tc (x64) from OBS, tried - no luck, removed and installed the x586 version - still no change.

**Comment by evilmav** [comment]
Got it! Installing  libtxc_dxtn has solved the problem! Thank you!

**Comment by runlevel5** [comment]
You can close the ticket now
