### ISSUE TITLE
portal2.sh - /bin/bash^M: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by oceand** [ValveSoftware/portal2#86]
Script appears to have been edited in windows, running dos2unix fixes the error.

**Comment by ferranobon** [comment]
I had the same problem. It was fixed by opting it into the beta as specified into the online Readme.md file. https://github.com/ValveSoftware/portal2/  (See the description under Portal 2 Linux Port)

**Comment by WhyNotHugo** [comment]
Is there any reason why we have a nonworking beta and have to opt into "Portal 2 (Beta) [beta]"? It's quite counterintuitive.

**Comment by timjp87** [comment]
People would still simply try to start the game if it was called "Portal 2" in the library like it is on Windows. A beta within a beta is a good way to bait Linux users. ;-)

**Comment by davidw-valve** [comment]
You need to opt in to the beta to play as described in the readme here: https://github.com/ValveSoftware/portal2

This process isn't ideal, but it allows us to get a Linux beta of Portal 2 into the hands of our users much faster than if we waited to develop infrastructure in Steam to support automatic opt-in to the beta based on platform. So we think it's a good choice, and hope our customers agree.
