### ISSUE TITLE
White paint is wrong colour

### ISSUE THREAD

**Issue by GlacialTurtle** [ValveSoftware/portal2#89]
White portal paint droplets appear to be the wrong colour. Encountered this in single player but doesn't appear to be in co-op. Doesn't affect painted surfaces, only the paint itself. 

Screenshot:

http://i.imgur.com/cuNVxLL.jpg

System info:

https://gist.github.com/GlacialTurtle/4de36032216a74da3d06

**Comment by Tele42** [comment]
Mesa devs should be brought into the loop for this issue report. Not reproduced in community test chambers on a GTX 460 / nvidia binary blob 331.38.

**Comment by GlacialTurtle** [comment]
I've re-tested in the same area and the bug did not appear again. Not sure if it was fixed by update or just rare/highly specific.

**Comment by davidw-valve** [comment]
I'm closing this out. Please re-file if you find more actionable information on it.
