### ISSUE TITLE
Portal 2 is listed as Left 4 Dead 2 under pulseaudio application list

### ISSUE THREAD

**Issue by xpander69** [ValveSoftware/portal2#9]
Small mistake with the naming..

its  detected as Left 4 Dead 2 slider under pulseaudio application list.

**Comment by timjp87** [comment]
Can confirm here.

**Comment by alebahn** [comment]
I looked for this after reading this and I saw it too. It must be some misconfiguration with SDL for the game.

**Comment by davidw-valve** [comment]
We have shipped an update that should fix this.
