### ISSUE TITLE
Portal 2 won't start

### ISSUE THREAD

**Issue by Chocrates** [ValveSoftware/portal2#93]
When clicking start, nothing happens.
When i go and run portal2.sh i run in to problems with the line endings
After running dost2unix on it, i get this:
portal2.sh: 9: cd: can't cd to portal2.sh
portal2.sh: 13: [: Linux: unexpected operator
portal2.sh: 16: [: Linux: unexpected operator
portal2.sh: 22: [: Linux: unexpected operator
portal2.sh: 34: [: unexpected operator
portal2.sh: 40: portal2.sh: /: Permission denied

I am running Linux Mint 15.
If there is a better way to start it from the command line, let me know.

**Comment by davidw-valve** [comment]
You need to opt in to the beta in Steam. Please see the readme here for details: https://github.com/ValveSoftware/portal2
